### ISSUE TITLE
macOS: Gutter Ctrl-Click does not open contextual menu

### ISSUE THREAD

**Issue by Leland** [jest-community/vscode-jest#1010]
![image](https://user-images.githubusercontent.com/714017/223150914-5717d348-2bc4-4ff4-ae5a-e13b76d7e316.png)

### Environment

1. `vscode-jest version`: v.5.2.3
2. `node -v`: v16.13.0
3. `npm -v`: 8.1.0
4. `npm ls jest` or `npm ls react-scripts` (if you haven’t ejected):
```
    ├── jest@26.6.0
    └─┬ react-scripts@4.0.3
      ├─┬ jest-watch-typeahead@0.6.1
      │ └── jest@26.6.0 deduped
      └── jest@26.6.0 deduped
```
6. your vscode-jest settings if customized:
7. Operating system: macOS 13.2.1

### Steps to Reproduce

1. In a test file, <kbd>Ctrl</kbd>-click a test icon in the line number gutter

### Expected Behavior

A contextual menu appears.

Per macOS system behavior, a <kbd>Ctrl</kbd>-click is equivalent to a right click.

### Actual Behavior

vscode-jest interprets the click as a left click, and reruns the test.

**Comment by noahskelton** [comment]
Encountering same behavior on my M1 Air (MacOS 13.0.1)

**Comment by connectdotz** [comment]
Sorry for the late reply. Context menu activation is controlled by vscode TestExplorer, we provide features through its API only. Suggest filing a bug report in [vscode](https://github.com/microsoft/vscode/issues) directly.

**Comment by Leland** [comment]
Recreated thither: https://github.com/microsoft/vscode/issues/177748

**Comment by Leland** [comment]
Good news, fixed upstream, just not in the release branch yet: https://github.com/microsoft/vscode/pull/176543
