### ISSUE TITLE
First execution of individual test (it block) executes all tests of the file

### ISSUE THREAD

**Issue by FrankVisuals** [jest-community/vscode-jest#1021]
### Environment

1. `vscode-jest version`: `5.2.3`
2. `node -v`: `16.19.0`
3. `npm -v` or `yarn --version`: npm `8.19.3`
4. `npm ls jest` or `npm ls react-scripts` (if you haven’t ejected): `jest@29.5.0` `ts-jest@29.1.0`
5. your vscode-jest settings if customized:
    - jest.jestCommandLine? `` (empty)
    - jest.autoRun? `` (off)
    - anything else that you think might be relevant? no
6. Operating system: `MacOS 13.2.1 (22D68)`

### Prerequisite
- are you able to run jest test from the command line? yes
- how do you run your tests from the command line? `npx jest`

### Steps to Reproduce

https://github.com/FrankVisuals/vscode-jest-issue 

Freshly written Test:

<img width="783" alt="image" src="https://user-images.githubusercontent.com/62556998/232445973-2606f1a3-4d90-43c0-b3a9-274b21638786.png">

Clicking only the test in line 4 

<img width="752" alt="image" src="https://user-images.githubusercontent.com/62556998/232446118-bedea03a-340e-4b28-bd0a-8dfc135bb7fd.png">

But still executes both tests

<img width="738" alt="image" src="https://user-images.githubusercontent.com/62556998/232446256-b5da5024-fe3a-45b2-ac47-80dd9cacb063.png">
<img width="439" alt="image" src="https://user-images.githubusercontent.com/62556998/232446330-25b1dd48-4cd1-4e6e-ab8c-b5f75d5c4281.png">

Afterwards, when clicking only one test, it works.

### Relevant Debug Info

n/a

### Expected Behavior

Also on first click it should execute only one test.

### Actual Behavior

Executes all tests on first click of individual execution.

--- 

The fastest (and the most fun) way to resolve the issue is to submit a pull-request yourself. If you are interested, feel free to check out the [contribution guide](https://github.com/jest-community/vscode-jest/CONTRIBUTING.md), we look forward to seeing your PR...

**Comment by cpwood** [comment]
Also experiencing this at the moment. Is there any workaround that anyone can think of (other than refactoring the tests to one-per-file)?

**Comment by connectdotz** [comment]
Yes, this is a bug. I will patch it soon. Thanks!

**Comment by FrankVisuals** [comment]
Thanks for the update!

**Comment by AlvesJorge** [comment]
This is still happening, worse yet, it is running tests that are meant to be skipped.
If you want to try and reproduce I'm doing this exercise here (but it happens in general) https://exercism.org/tracks/javascript/exercises/dominoes

I click on one test to debug it, and instead it tries to run other tests in the file too, worse even, it runs tests that are marked with an "x" meaning they should be skipped. And it is only telling me this because it is encountering a type error. 

Is this intended?
