### ISSUE TITLE
Feature request: Introduce a power save mode

### ISSUE THREAD

**Issue by CodingSpiderFox** [jest-community/vscode-jest#1025]
When I'm not near a power source, I want to change the configuration of the plugin to a certain set of settings (for example turning off autoRun) via the VSCode command palette

**Comment by connectdotz** [comment]
If I understand you correctly, this feature is already available: 

<img width="616"  src="https://github.com/jest-community/vscode-jest/raw/master/images/testExplorer-5.1.1.png">

See [How to use the Test Explorer?](https://github.com/jest-community/vscode-jest#how-to-use-the-test-explorer), specifically **"How to toggle autoRun for the workspace"**

Please let me know if this is what you are looking for.

**Comment by connectdotz** [comment]
However, I can see this is not very convenient for monorepo projects with multiple folders, which would require manually toggling off each folder... 

It is worth considering adding an autoRun command to toggle on/off selected workspaces via the command palette, so users can toggle autoRun with multiple workspaces if needed. 

Should be a pretty easy PR as we already have all the logic in place

**Comment by connectdotz** [comment]
See the new proposal: #1058
