### ISSUE TITLE
how to completely disable autorun?

### ISSUE THREAD

**Issue by dcsan** [jest-community/vscode-jest#1027]
viewing this it seems you need to manually toggle the annoying autorun OFF every session.

is there a basic workspace settings config file somewhere with an example how to disable this?

https://github.com/jest-community/vscode-jest/blob/master/README.md#how-to-toggle-auto-run

**Comment by connectdotz** [comment]
Yes, you can set autoRun in the settings: please see [autoRun](https://github.com/jest-community/vscode-jest#autorun).

**Comment by airtonix** [comment]
> Yes, you can set autoRun in the settings: please see [autoRun](https://github.com/jest-community/vscode-jest#autorun).

doesn't work.

I have a code-workspace file with : 
```
{
	"folders": [
		{
			"path": "."
		},
		{
			"path": "apps/mobile"
		},
		{
			"path": "apps/mobile-e2e"
		},
		{
			"path": "apps/web-e2e"
		},
		{
			"path": "pkgs/ui/theme"
		},
		{
			"path": "pkgs/ui/tokens"
		},
		{
			"path": "pkgs/ui/box"
		},
	],
	"settings": {
		"jest.autoRun": "off",
	}
}
```

and when i do a `reload-window`

i get see this: 

[Screencast from 2023-12-25 11-40-22.webm](https://github.com/jest-community/vscode-jest/assets/61225/fa15406a-0667-4db0-b99f-620b826936ac)
