### ISSUE TITLE
Test Runner usage of --TestNamePattern missing proper escaping / encoding

### ISSUE THREAD

**Issue by hannasm** [jest-community/vscode-jest#1042]
It seems like the test runner needs to put more specific regex syntax on the --testNamePattern argument. Right now jest runs any tests that have a matching prefix as the test selected. 

It is very likely the same applies for matching suffixes and substrings but i have not test this.

See https://jestjs.io/docs/cli#--testnamepatternregex

### Steps to Reproduce
```ts
test('test004', async() => {
  console.log('hello');
});
test('test004b', async() => {
    console.log('world');
});
```

From test explorer click the run button on test004

### Expected Behavior

test004 is the only test that runs

### Actual Behavior

test004b also runs

**Comment by connectdotz** [comment]
That's true. This should be pretty easy to fix; maybe just add a `$` at the end of the test name pattern... want to give it a try?

**Comment by kajikentaro** [comment]
I think one problem is how to distinguish following example.
```javascript
describe("this is", () => {
  it("a test", () => {
    console.log("hello world");
  });
});
describe("this is a", () => {
  it("test", () => {
    console.log("hello world");
  });
});
```
If I use `this is a test$` for regex, it matches both of them.

**Comment by connectdotz** [comment]
@kajikentaro, that is an interesting use case. But it will require jest to change its full-name matching algorithm, right now, the names are concat with a space separator, therefore it will match both tests as you observed. Please feel free to open an issue in jest to ask for this enhancement.
