### ISSUE TITLE
[Feature Request] Support Monorepo single root workspace

### ISSUE THREAD

**Issue by ciandt-crodrigues** [jest-community/vscode-jest#1044]
### Environment
VSCode - Any version

### Prerequisite
- are you able to run jest test from the command line? Yes, it runs on npm run test or npm run test:coverage
- how do you run your tests from the command line? (for example: `npm run test` or `node_modules/.bin/jest`) Yes, it runs on npm run test or npm run test:coverage

### Expected Behavior

use the nearest configuration (parent packages.json , jest.config.ts) to run the tests

### Actual Behavior

It requires multi root workspace to resolve the node_modules/.bin/jest and config

--- 

The fastest (and the most fun) way to resolve the issue is to submit a pull-request yourself. If you are interested, feel free to check out the [contribution guide](https://github.com/jest-community/vscode-jest/CONTRIBUTING.md), we look forward to seeing your PR...

**Comment by connectdotz** [comment]
Hi, perfect timing. We just pre-released v6.0.0 with `virtualFolders` that specifically targeted these kinds of use cases. It doesn't go by the nearest jest config but require specific jest config called [jest.virtualFolders](https://github.com/jest-community/vscode-jest/blob/master/release-notes/README.md#virtualfolders), which not only enabled users to run multiple jest configs within the single root workspace, but also supported all jest settings for each virtualFolder, such as `autoRun` etc.  Please feel free to give it a try: https://github.com/jest-community/vscode-jest/blob/master/release-notes/release-note-v6.md#v600-pre-release
