### ISSUE TITLE
Disable Auto Open "TEST RESULTS" tab

### ISSUE THREAD

**Issue by hindicator** [jest-community/vscode-jest#1053]
### Environment

1. `vscode-jest version`: [6.0.0]
2. `node -v`: [v18.14.2]
3. `yarn --version`: [3.6.1]
4. script: [yarn test]
5. your vscode-jest settings if customized:
   tried all settings
6. Operating system: debian

### Prerequisite
- are you able to run jest test from the command line? yes
- how do you run your tests from the command line? (for example: `npm run test` or `node_modules/.bin/jest`) -
- yarn test

### Relevant Debug Info

I have a Monorepo with `jest.virtualFolders` configured (btw, great work!),
When I'm running a test, it automatically switch to "TEST RESULTS" tab,
while the output is actually in the terminal (as I want)
![image](https://github.com/jest-community/vscode-jest/assets/73799532/5671c111-e168-427c-8631-9cd4a7f0498d)

How can I disable this "Auto Open `TEST RESULTS` Tab" ?

**Comment by amirulabu** [comment]
How did you fix this?
