### ISSUE TITLE
Test results instantly disappear in the test results panel

### ISSUE THREAD

**Issue by khaosdoctor** [jest-community/vscode-jest#1073]
### Environment

1. `vscode-jest version`: 5.2.3
2. `node -v`: 16.20.1
3. `npm -v` or `yarn --version`: 1.22.10
4. `npm ls jest` or `npm ls react-scripts` (if you haven’t ejected): 29.5.0
5. your vscode-jest settings if customized: default
6. Operating system: MacOS Ventura 13.5

### Prerequisite
- are you able to run jest test from the command line? yes
- how do you run your tests from the command line? (for example: `npm run test` or `node_modules/.bin/jest`) yarn test

### Steps to Reproduce

1. Open any repository with tests
2. Click the sidebar "testing" icon
3. Run a test
4. Focus the `Test Results` panel on the bottom
5. The test results will show the terminal output while the test is running but, as soon as the test ends, the output is cleared
6. The terminal panel will have the results in a separate terminal but not on the Test Results tab

### Expected Behavior

The Test results output keeps the terminal output in the side window

### Actual Behavior

The tab is being cleared as soon as the test ends but the result remains in the Terminal tab

**Comment by connectdotz** [comment]
Yes, "Test Results" tab is not yet fully supported, see similar discussion #1051. Let's continue the discussion there. Closing this for now. Thanks!
