### ISSUE TITLE
Add an option not to automatically show the "Test results" panel

### ISSUE THREAD

**Issue by SimoneGianni** [jest-community/vscode-jest#1074]
### Environment

1. `vscode-jest version`: 5.2.3
2. `node -v`: 
3. `npm -v` or `yarn --version`:
4. `npm ls jest` or `npm ls react-scripts` (if you haven’t ejected): 
5. your vscode-jest settings if customized:
    - jest.jestCommandLine? 
    - jest.autoRun? false
    - anything else that you think might be relevant? 
6. Operating system: any

### Expected Behavior

Add an option NOT to show the "Test results". I prefer to see the tests running in the terminal, and eventually in the "Testing" view, no need for the "Test results".

There is already an option not to show the terminal (Auto Reveal Output), add one not to show the test results (or at least not to focus) the panel too.

### Actual Behavior

The "Test results" panel is just a repetition of the other two, it does not display any relevant information that is not already available in the "Testing" view, in the code lenses and ultimately in the terminal itself.

It does not even show the test output, nor the cause of the failure. But even if it was showing it, I would still prefer not to use it. 

It pops up hiding the terminal each time I run a test, I use the terminal for a lot of things and getting back to it each time is annoying.

There is an option to avoid the Jest terminal popping up exactly for this reason, there should be one for the "Test results" panel given it is even more intrusive.

**Comment by connectdotz** [comment]
There is already a vscode setting  `"testing.openTesting "` to control this tab, please see [comment](https://github.com/jest-community/vscode-jest/issues/1051#issuecomment-1676143068) for details.
