### ISSUE TITLE
Unable to ReRun last test

### ISSUE THREAD

**Issue by Kikketer** [jest-community/vscode-jest#1076]
### Environment

1. `vscode-jest version`: v5.2.3
2. `node -v`: v16.20.2
3. `npm -v` or `yarn --version`: 1.22.19 (yarn)
4. `npm ls jest` or `npm ls react-scripts` (if you haven’t ejected): 
```
├─┬ @testing-library/jest-dom@6.1.3
│ └── jest@29.7.0 deduped
└── jest@29.7.0
```
6. your vscode-jest settings if customized:
    - jest.jestCommandLine? [fill]
    - jest.autoRun? turned off
    - anything else that you think might be relevant? [fill]
7. Operating system: MacOS 10.15.7

### Prerequisite
- are you able to run jest test from the command line? Yes
- how do you run your tests from the command line? (for example: `npm run test` or `node_modules/.bin/jest`) `jest` (node_modules)

### Steps to Reproduce

I have a simple codebase and a few tests.  While I'm debugging and working on a test I like to re-run the specific test that I'm working on because my machine isn't overly powefull and "watch" drags it through the mud.  Also watching a single test/file drags the system as well when I'm rapidly changing and iterating.  My typical process with this machine is to do all my editing, save, run last test, iterate.

Simply attempt to click the "ReRun Last Test" or set a keyboard shortcut to do so.

Clicking the button does nothing:

https://github.com/jest-community/vscode-jest/assets/958042/e02eb650-e061-466e-883f-fc04a563b040

Also attempting the keyboard shortcut does nothing.  However "re-run all" works.

![Rerun Not Working](https://github.com/jest-community/vscode-jest/assets/958042/e4abe697-368c-4bc0-8f07-7f471a0db456)

### Expected Behavior

When I run a single test (from test explorer or in the editor) I would expect the keyboard shortcut or the icon in test explorer to re-run that same test when clicked/pressed.

### Actual Behavior

It does nothing.

**Comment by connectdotz** [comment]
That's true, it is probably related to our `TestRun` integration issue(#1051), we will address this in the upcoming TestResults tab integration PR...
