### ISSUE TITLE
Fails in VSCode 1.12

### ISSUE THREAD

**Issue by tinovyatkin** [jest-community/vscode-jest#108]
![screen shot 2017-05-17 at 21 07 56](https://cloud.githubusercontent.com/assets/5350898/26182290/31c90866-3b45-11e7-8be2-4cae2c595bcb.png)

**Comment by orta** [comment]
I think the fix for this is a PR checking the validity of the JSON before parsing inside the jest-editor-extension `Settings.js`

**Comment by orta** [comment]
If you want to fix it for your setup, update to Jest 20

**Comment by tinovyatkin** [comment]
I have Jest 20.0.3 in this project

**Comment by n-roman** [comment]
I still have the same with jest 20.0.4 from wmonk/create-react-app-typescript

**Comment by seanpoulter** [comment]
Anyone still have these issues?
