### ISSUE TITLE
Different jest.jestCommandLine settings for run vs debug

### ISSUE THREAD

**Issue by nbolton** [jest-community/vscode-jest#1081]
### Feature request

I'm using `fnm` on Linux to select my node version, and I've managed to set `jest.jestCommandLine` in `settings.json` to use the correct Node version according to the `.nvmrc` in my project:

```
  "jest.jestCommandLine": "fnm use --version-file-strategy recursive && npm test --",
```

This works fine for running tests normally (in the Jest 'Testing' activity), and from using 'Run test'.

However, when I use the 'Debug test' shortcut, e.g. to debug a specific test, it uses `jest.jestCommandLine` in a weird way; it prepends the full path of my system default Node binary (which is not the binary used for my project; that's an older Node version), so I get something like this:

```
/run/user/1000/fnm_multishells/1082892_1697542670710/bin/node ./fnm use --version-file-strategy recursive \&\& npm test --
```

This of course gives me a `Cannot find module` error, since `fnm` isn't something Node can run.

In this case, it'd be useful if we could use a different `jest.jestCommandLine` value for run and debug, since the value is used differently in each context.

The relevant line seems to be:
https://github.com/jest-community/vscode-jest/blob/10414abf47d9829d67ef8932fdd12bb472154ed9/src/JestExt/core.ts#L636

### Workaround

For now, I'll just use `fnm default x` to set the Node version globally.

**Comment by connectdotz** [comment]
In debug, vscode uses its own configuration in the `launch.json`. We attempt to generate a debug config based on the `jest.jestCommandLine` if none is provided by users. This is a best effort and most likely won't cover all use cases. If it doesn't work for your project, it is recommended to create an explicit debug config instead: see https://github.com/jest-community/vscode-jest#debug-config-v2 (note the debug config has no dependency on` jest.jestCommandLine`)

**Comment by mion-kr** [comment]
same issue

**Comment by dwiyatci** [comment]
> (note the debug config has no dependency on` jest.jestCommandLine`)

The enlightenment that I've got the most is coming from this line above ☝
