### ISSUE TITLE
tests with parenthesis or other special characters, don't match on individual execution

### ISSUE THREAD

**Issue by olafbuitelaar** [jest-community/vscode-jest#1083]
### Environment

1. `vscode-jest version`: v5.2.3
2. `node -v`: v18.15.0
3. `npm -v`: 7.20.0
4. `npm ls jest`: 
├── jest@29.6.4
└─┬ ts-jest@29.1.1
  └── jest@29.6.4 deduped
7. Operating system: windows 10

### Steps to Reproduce
When a test names contains parenthesis (), it seems the test is not matched, when you try to run (or debug) it from vscode, but directly from the code view, and the test explorer.
example;
`Should return NULL after expiresIn expires (get / getValue Method)` would be skipped
while removing the parenthesis, will get the test to be found and executed, 
like `Should return NULL after expiresIn expires get / getValue Method`

It appears the characters get escaped in the command line, which causes them to not being able to match;
`'--testNamePattern' 'Storage Should return NULL after expiresIn expires \(get / getValue Method\)'`

### Expected Behavior

I would expect test with special characters to be individually being executed (same behaviour also seems to apply to other characters, like `[`)

--- 

The fastest (and the most fun) way to resolve the issue is to submit a pull-request yourself. If you are interested, feel free to check out the [contribution guide](https://github.com/jest-community/vscode-jest/CONTRIBUTING.md), we look forward to seeing your PR...

**Comment by connectdotz** [comment]
Hi, noticed you are using npm 7.x, which had issue with pass-through argument interpretation, see [comment](https://github.com/jest-community/vscode-jest/issues/885#issuecomment-1192161406). Can you try with npm >= 8.15 and let me know if you still have any problems?

**Comment by olafbuitelaar** [comment]
Thank you, that solves the issue

**Comment by connectdotz** [comment]
Great.
