### ISSUE TITLE
Jest times out during debug with fake timers

### ISSUE THREAD

**Issue by romulof** [jest-community/vscode-jest#1085]
### Environment

1. `vscode-jest version`: 5.2.3
2. `node -v`: 18.18.2
3. `yarn --version`: 1.22.19
4. `npm ls jest` or `npm ls react-scripts` (if you haven’t ejected): jest@29.7.0
5. your vscode-jest settings if customized:
    - jest.jestCommandLine? not changed
    - jest.autoRun? not changed
    - anything else that you think might be relevant?
    ```json
        "jest.shell": "/bin/zsh",
        "jest.testExplorer": {
            "showInlineError": true
        },
    ```
6. Operating system: macOS Ventura 13.6

### Prerequisite
- are you able to run jest test from the command line? yes
- how do you run your tests from the command line? `yarn test`

### Steps to Reproduce

1. Checkout repo https://github.com/romulof/jest-fake-timer-timeout
2. `yarn install`
3. Open VSCode
4. Debug test
5. Once debugger stops at `debugger` statement, immediately press continue (aka play button)

### Relevant Debug Info

Not applicable

### Expected Behavior

Test succeed

### Actual Behavior

Test fail with message:
```
thrown: "Exceeded timeout of Infinity ms for a test.
    Add a timeout value to this test to increase the timeout, if this is a long-running test. See https://jestjs.io/docs/api#testname-fn-timeout."
```

Demo:

https://github.com/jest-community/vscode-jest/assets/1225889/5380726a-2b9f-430e-812c-a9e6ee42304e

### Additional information

When I debug this test in Chrome (running `node --inspect-brk node_modules/.bin/jest`) or in WebStorm, this error does not happen.

When I remove the jest config line setting the timeout, the error stops, but then I'm limited to Jest's default 5 second timeout during debug.

Error still happens when I set the timeout to `Number.MAX_SAFE_INTEGER`.

--- 

The fastest (and the most fun) way to resolve the issue is to submit a pull-request yourself. If you are interested, feel free to check out the [contribution guide](https://github.com/jest-community/vscode-jest/CONTRIBUTING.md), we look forward to seeing your PR...

**Comment by romulof** [comment]
Found the issue. Jest breaks when I set `testTimeout` higher than max 32bit signed integer.

**Comment by ericman314** [comment]
Thanks for the example. I ended up adding this to my jest config:

```js
  testTimeout: process.env.NODE_OPTIONS?.includes("inspect") ? 2147483647 : 5000
```

**Comment by romulof** [comment]
I'm using this:

```js
const max32bitSignedInt = 2 ** 31 - 1;
const isDebug =
  process.env.NODE_OPTIONS?.includes('--inspect') ||
  process.execArgv.some((arg) => arg.startsWith('--inspect'));

module.exports = {
  testTimeout: isDebug ? max32bitSignedInt : 5000,
  ...
};
```
