### ISSUE TITLE
jest.nodeEnv does not expand variables

### ISSUE THREAD

**Issue by esmiralha** [jest-community/vscode-jest#1095]
### Environment

1. `vscode-jest version`: v5.2.3
2. `node -v`: v18.18.2
3. `npm -v` or `yarn --version`: 9.8.1
4. `npm ls jest` or `npm ls react-scripts` (if you haven’t ejected): jest@29.7.0
5. your vscode-jest settings if customized:
    - jest.jestCommandLine? npm run test --
    - jest.autoRun? not customized
    -  "jest.nodeEnv": {
    "TESTCONTAINERS_HOST_OVERRIDE": "127.0.0.1",
    "TESTCONTAINERS_DOCKER_SOCKET_OVERRIDE": "/var/run/docker.sock",
    "DOCKER_HOST": "unix://${HOME}/.colima/default/docker.sock"
  }
6. Operating system: Mac OS Ventura

### Prerequisite
- are you able to run jest test from the command line? yes
- how do you run your tests from the command line? TESTCONTAINERS_HOST_OVERRIDE=127.0.0.1 TESTCONTAINERS_DOCKER_SOCKET_OVERRIDE='/var/run/docker.sock' DOCKER_HOST="unix://${HOME}/.colima/default/docker.sock" npm run test

### Steps to Reproduce

set any env var in jest.nodeEnv with a value that relies on another env var and it wont substitute the variable as expected.

### Expected Behavior

Variable should be expanded.

### Actual Behavior

Variable is not expanded.

**Comment by connectdotz** [comment]
Does setting "jest.jestCommandLine" exactly as you run in the terminal work?

```json
"jest.jestCommandLine": "TESTCONTAINERS_HOST_OVERRIDE=127.0.0.1 TESTCONTAINERS_DOCKER_SOCKET_OVERRIDE='/var/run/docker.sock' DOCKER_HOST=\"unix://${HOME}/.colima/default/docker.sock\" npm run test --"
```
You might need to play around with the escape to make the command above work.

The "jest.NodeEnv" is a pass-through that will be added directly to the node's child_process.env property. The extension and Nodejs (I think) don't perform any pre-processing or variable expansion for these variables. It's usually the shells that do the expansion/substitution.

**Comment by esmiralha** [comment]
Yes, it works. Closing the issue!
