### ISSUE TITLE
`clear-all` codicon for `CLear All Results` icon

### ISSUE THREAD

**Issue by PraneshBalasubramaniam** [jest-community/vscode-jest#1104]
Hi, can we change the delete icon for `Clear All Results` as it feels like deleting something than clearing something.
Can we change it with `clear-all` codicon which is much understandable for clearing test results.

![image](https://github.com/jest-community/vscode-jest/assets/44346322/a4061134-0006-4f48-8832-b2d255e0d790)
![image](https://github.com/jest-community/vscode-jest/assets/44346322/3afa0594-4eda-436b-b0ab-f484fe588a4f)

**Comment by connectdotz** [comment]
Hi, this panel is maintained by vscode team. cc @connor4312.

**Comment by connor4312** [comment]
Good point, fixed in https://github.com/microsoft/vscode/pull/202608

**Comment by PraneshBalasubramaniam** [comment]
Ok Thanks, then I will close the issue
