### ISSUE TITLE
Bypass jest command check for non-jest projects

### ISSUE THREAD

**Issue by tbsuht** [jest-community/vscode-jest#1107]
### Environment

1. `vscode-jest version`: [v5.2.3]
3. `npm -v`: [9.2.0]
6. Operating system: [Debian Bookworm]

### Expected Behavior

Use the extension within multi-project workspaces, without complaining about projects which are not "web-projects".

### Actual Behavior

I have a multi-project workspace with various projects (C++, python, javascript ...).

The extension complains on VS Code startup about every project which is not a "web-project" the following with a lot of pop-ups:
```
[warn] not able to find test script or jest/CRA binary in any of the package roots

[error] Abort jest session: Not able to auto detect a valid jest command
```

The extension is working fine for the projects which contain jest tests.

Is there a way to omit this, so that such projects can be skipped? Or that the discovery is not done on startup?
Yes, I can click "Ignore folder", but I want to define this "programmatically".

**Comment by connectdotz** [comment]
Hi, this can be done with `jest.disabledWorkspaceFolders` in 5.x or `jest.enable` in 6.x. See https://github.com/jest-community/vscode-jest?tab=readme-ov-file#settings for more details.

**Comment by tbsuht** [comment]
Thanks!
