### ISSUE TITLE
Extension is unable to locate tests because path segments are omitted from --testPathPattern

### ISSUE THREAD

**Issue by yegorpetrov** [jest-community/vscode-jest#1112]
### Environment

1. `vscode-jest version`: 6.2.0
2. `node -v`: v20.9.0 
3. `npm -v`: 10.1.0
4. `npm ls jest`:
```
├── jest@29.7.0
└─┬ ts-jest@29.1.2
  └── jest@29.7.0 deduped
```
6. your vscode-jest settings if customized:
    - jest.jestCommandLine? no
    - jest.autoRun? "off"
    - anything else that you think might be relevant? nope
7. Operating system: Win 11

### Prerequisite
- are you able to run jest test from the command line? yes
- how do you run your tests from the command line? `npm run unit-ci`
```
"unit": "npm run test",
"unit-ci": "npm run unit --coverage --ci --reporters=default --reporters=jest-junit",
```

### Steps to Reproduce

Upgrade to 6.2.0

### Expected Behavior

Ability to run tests at any level of the tests tree view

### Actual Behavior

Unable to run tests at many levels of the tests tree view. In the "Test results" panel it looks like the extension is omitting path segments for no apparent reason. In comparison with v.5.2.3, the tree view is also missing those segments. The typical output is as follows:

```
No tests found, exiting with code 1
Run with `--passWithNoTests` to exit with code 0
In [REDACTED]\backend\src\nodejs
  298 files checked.
  testMatch: **/__tests__/**/*.[jt]s?(x), **/?(*.)+(spec|test).[jt]s?(x) - 68 matches
  testPathIgnorePatterns: \\node_modules\\ - 298 matches
  testRegex:  - 0 matches
Pattern: [REDACTED]\\backend\\handlers\\store - 0 matches
```
The correct path is \backend\src\nodejs\handlers\store. If I copy the command (as shown on screenshots) and run it manualy with a fixed path, then it works.

![image](https://github.com/jest-community/vscode-jest/assets/10397442/1e19fe1b-6aa4-495c-b269-72e94cb29e8f)

**Comment by connectdotz** [comment]
This looked like a bug, but I can't repro in any of my test projects... Do you have a sample repo we can take a look at? 

Otherwise, we have to dig into it manually:
1. Do you happen to have a `jest.rootPath`setting? 
2. Do you open vscode project workspace from the "backend" folder?
3. Just to confirm that restarting vscode didn't make any difference?
4. Are you able to use the test file editor's gutter menu to run tests?
5. Any other jest settings we should know about?

**Comment by yegorpetrov** [comment]
@connectdotz 
> Do you have a sample repo we can take a look at?

[YES](https://github.com/jest-community/vscode-jest/files/14275949/backend.zip)
- `npm i` in backend/src/nodejs
- Open the "backend" dir in VS Code with vscode-jest 6.2.0
- Navigate to tests
- Execute the root node "backend" for the tree of tests to appear, all tests should run fine (4 test suites, 4 tests)
- Observe that "src" and "nodejs" are omitted from the tree
- Expand to handlers > store > orders and try to run the "orders" node
- **The bug:** observe that 0 tests were found/executed and that `testPathPattern` is incorrect
-----
- "Install another version" of the extension to **downgrade to 5.2.3**, agree to reload
- Observe that "src" and "nodejs" are displayed in the tree view
- Expand to "orders" again and run it
- **As expected**: 3 test suites, 3 tests executed all green

> Otherwise, we have to dig into it manually

I will answer regardless.

> 1. Do you happen to have a jest.rootPathsetting?

Nope.

> 2. Do you open vscode project workspace from the "backend" folder?

Yes.

> 3. Just to confirm that restarting vscode didn't make any difference?

Nope.

> 4. Are you able to use the test file editor's gutter menu to run tests?

Yes, even in 6.2.0 I can run individual tests from the editor and in that case `testPathPattern` is correct and points to the file with all path segments in place. The issue is being unable to run on directories, except may be the root directory.

> 5. Any other jest settings we should know about?

No. I left as much as I could from the problematic project in the repro so you can check. I don't see any relevant OS user settings for jest.

**Comment by etnoy** [comment]
If you need a sample repo I am experiencing this bug in the following repo: https://github.com/immich-app/immich/

Using v6.2.0 I want to run the spec.ts tests in the server/ folder. I set the Jest configuration to the following: 
![image](https://github.com/jest-community/vscode-jest/assets/135728/41b1b41d-a135-4f13-9478-911e02416d09)

I am not using a monorepo setup in vscode-jest even though the repo is a monorepo

I am able to run individual test files from the test panel in vscode, but when I move to running all tests, it removes the server/ folder from the testPathPattern argument, resulting in no tests.

**Comment by etnoy** [comment]
Can confirm that rolling back to 5.2.3 fixes the issue.

On 5.2.3: jest  --testLocationInResults --json --useStderr --outputFile /tmp/jest_runner_immich_1000_2.json --no-coverage --reporters default --reporters /home/etnoy/.vscode-server/extensions/orta.vscode-jest-5.2.3/out/reporter.js --colors --watchAll=false --testPathPattern /home/etnoy/code/immich/server/src

On 6.2.0: jest  --testLocationInResults --json --useStderr --outputFile /tmp/jest_runner_immich_1000_2.json --no-coverage --reporters default --reporters /home/etnoy/.vscode-server/extensions/orta.vscode-jest-6.2.0/out/reporter.js --colors --watchAll=false --testPathPattern /home/etnoy/code/immich/src

note that the testPatPattern is incorrect on 6.2.0

**Comment by connectdotz** [comment]
Thanks for the sample repo! It helped me to locate and fix the issue in [v6.2.1](https://github.com/jest-community/vscode-jest/releases/tag/v6.2.1). 

Please don't hesitate to let me know if there are any other issues.

**Comment by etnoy** [comment]
Thanks, 6.2.1 fixed the issue for me :)

**Comment by yegorpetrov** [comment]
I too, can confirm it was fixed.
