### ISSUE TITLE
Test result is revealed automatically on each save

### ISSUE THREAD

**Issue by javierfmarq** [jest-community/vscode-jest#1113]
### Environment

1. `vscode-jest version`: [6.2.0]
2. `node -v`: [v18.12.1]
3. `npm -v` or `yarn --version`: [fill]
4. `npm ls jest` or `npm ls react-scripts` (if you haven’t ejected): [fill]
5. your vscode-jest settings if customized:
```
  "jest.runMode": {
    "type": "on-save",
    "testFileOnly": true,
    "showInlineError": true
  },
  "jest.shell": { "path": "/bin/bash", "args": ["--login"] },
```
6. Operating system: [Windows 11]

### Prerequisite
- are you able to run jest test from the command line? [yes]
- how do you run your tests from the command line? (for example: `npm run test` or `node_modules/.bin/jest`) [`npm run test`]

### Expected Behavior

I would like to run tests onSave but I don't want that the **Test Results** is open automatically. I like saving and checking the green indicators in gutter, and If something fails I open the output and check.

Something like this in an option:

```
  "jest.runMode": {
    "type": "on-save",
    "testFileOnly": true,
    "revealOutput": "off"
  },
```

### Actual Behavior

Test results pop ups automatically each time I save.

--- 

The fastest (and the most fun) way to resolve the issue is to submit a pull-request yourself. If you are interested, feel free to check out the [contribution guide](https://github.com/jest-community/vscode-jest/CONTRIBUTING.md), we look forward to seeing your PR...

**Comment by connectdotz** [comment]
This is the same issue as #1111, please see answer [here](https://github.com/jest-community/vscode-jest/issues/1111#issuecomment-1939656073)
