### ISSUE TITLE
[BUG] "testing.openTesting": "openOnTestFailure" opens the Test Results viewlet every test suite run, instead of only on failures

### ISSUE THREAD

**Issue by GeorgeWL** [jest-community/vscode-jest#1118]
**Describe the bug**
I tried setting "testing.openTesting": "openOnTestFailure" and the Test Results viewlet still opens every time, instead of only on failures

**To Reproduce**
1. Go to VS code settings 
2. Set "testing.openTesting": "openOnTestFailure"
3. Trigger tests on a test suite that is all successful years
4. The test results viewlet displays when it shouldn't do

Note: A sample repo will help us identify the bug much faster. 🙏

**Expected behavior**
Viewlet only opens on failures, if all are successful, no Test Results viewlet is shown

**Screenshots**

**Environment (please complete the following information):**
- vscode-jest version: LTS
- `node -v`: LTS
- `npm -v` or `yarn --version`: LTS
- jest or react-scripts (if you haven’t ejected) version: LTS
- your vscode-jest settings:
    - jest.jestCommandLine? `yarn test`
    - jest.runMode? `on-save`
    - jest.outputConfig? [e.g., none]
    - anything else that you think might be relevant? [e.g., none]
- Operating system: Windows 11

**Prerequisite**
- are you able to run jest from the command line? Yes
- where do you run jest CLI from? Monorepo folder for specific subprojects
- how do you run your tests from the command line? `yarn test`

**Additional context**

---

The fastest (and the most fun) way to resolve the issue is to submit a pull request yourself. If you are interested, please check out the [contribution guide](https://github.com/jest-community/vscode-jest/CONTRIBUTING.md), we look forward to seeing your PR...

**Comment by GeorgeWL** [comment]
https://github.com/jest-community/vscode-jest/issues/1111#issuecomment-1954422007

**Comment by connectdotz** [comment]
> is there a way to have it auto-close when tests begin succeeding again

Yes, there is a command to close the panel, but neither vscode nor this extension implemented the auto "closing" logic.
