### ISSUE TITLE
[BUG] Extension v6.2.2 does not activate

### ISSUE THREAD

**Issue by MorMundHS-MA** [jest-community/vscode-jest#1121]
**Describe the bug**
When updating the extension to v6.2.2 it does not activate properly anymore. It still logs the activation event in the extension host but commands are not found afterwards. The `Jest (Workspace)` output stream is also not available. Downgrading to `v6.2.1` works.

I'm using the extension through WSL remote in VS Code.

Activation from Extension Host (Remote):
```
info] ExtensionService#_doActivateExtension Orta.vscode-jest, startup: true, activationEvent: 'workspaceContains:**/jest.config.{js,ts,mjs,cjs,json},**/jest.json,**/.vscode-jest'
```

Runtime stats:
```
Activation Event:Startup
Activation Time:3ms
```

**To Reproduce**
1. Open an empty workspace/directory
2. Run the `Jest: Setup extension` command from the palette.
3. You get an error message: `command 'io.orta.jest.setup-extension' not found. 

**Expected behavior**

The command opens the setup actions wizard.

**Environment (please complete the following information):**
- vscode-jest version v6.2.2
- `node -v`: v18.17.1
- your vscode-jest settings: Non defined in user settings. Tested in empty directory.
- Operating system: Windows 10 22H2, WSL-Version: 2.0.0.0, Kernelversion: 5.15.123.1-1, Debian GNU/Linux 12 (bookworm)

**Comment by connectdotz** [comment]
I can't repro this in a regular local workspace, it runs as expected with 6.2.2. The command `io.orta.jest.setup-extension` did not change in 6.2.2 and is present in both the package.json and the code. 

I don't have a remote WSL env to test, and we never did anything special for it, so not sure why 6.2.2 would cause this issue... 🤔

Does restarting the vscode or the remote server with v6.2.2 help?  Does jest activate for non-empty workspace remotely for you?

**Comment by MorMundHS-MA** [comment]
It works correctly now when I updated again. Not sure what the problem was or what fixed it.

> Does restarting the vscode or the remote server with v6.2.2 help? Does jest activate for non-empty workspace remotely for you?

I thought I did a full restart of my system before I submitted the issue, but I guess this fixed it in the end. Thank you for the quick response!
