### ISSUE TITLE
[BUG]the version on open-vsx.org is outdated (5.2.3)

### ISSUE THREAD

**Issue by DetachHead** [jest-community/vscode-jest#1130]
it looks like the version of the extension on the openVSX registry hasn't been updated in a year: https://open-vsx.org/extension/Orta/vscode-jest

![image](https://github.com/jest-community/vscode-jest/assets/57028336/158ac905-2eac-45cc-b391-d604856346c0)

**Comment by connectdotz** [comment]
Indeed. Thanks for the reminder. v6.2.3 has been pushed to VSX now.
