### ISSUE TITLE
[FEATURE] Support for native vscode coverage API

### ISSUE THREAD

**Issue by romap0** [jest-community/vscode-jest#1135]
VSCode released a new [Test Coverage API](https://code.visualstudio.com/api/extension-guides/testing#test-coverage). Do you plan to implement it?

**Comment by connectdotz** [comment]
Yes, it's in the plan...

**Comment by connectdotz** [comment]
Hey everyone,

The fix is out! Check out the pre-release [v6.3.0-next](https://github.com/jest-community/vscode-jest/blob/master/release-notes/release-note-v6.md#v630-pre-release) and let us know if you run into any issues.
