### ISSUE TITLE
[BUG] Cannot debug on VSCode 1.88

### ISSUE THREAD

**Issue by lamuertepeluda** [jest-community/vscode-jest#1136]
**Describe the bug**

Debugging tests seem not to work anymore in VSCode 1.88, macOS 14.4.1 M2 Pro Chipset

Perhaps related to https://github.com/microsoft/vscode/issues/209785

**To Reproduce**
1. Select a test file (file explorer or text explorer or test code)
2. Add some breakpoints
3. Click on 'debug test'
4. The test execution runs without respecting the breakpoints

**Expected behavior**

Debugger stops at test breakpoints

I
**Prerequisite**
- are you able to run jest from the command line? yes
- where do you run jest CLI from? root directory
- how do you run your tests from the command line? (e.g., "npm run test" or "node_modules/.bin/jest")  -> BOTH

**Additional context**

See VSCode issue, see also https://github.com/firsttris/vscode-jest-runner/issues/362 (similar extension, same problem)

---

The fastest (and the most fun) way to resolve the issue is to submit a pull request yourself. If you are interested, please check out the [contribution guide](https://github.com/jest-community/vscode-jest/CONTRIBUTING.md), we look forward to seeing your PR...

**Comment by webhype** [comment]
Similar (or same) problem here, `Debugger attached` no longer appears in the terminal pane as expected, and the little debugger control window (allowing to pause / single step / exit) disappears shortly after initiating a "debug" session. After that the program executes without any debugging help. Had to downgrade to 1.87.2. Not fixed in 1.89 either. Same hardware config as OP.

**Comment by KyleLehtinenDev** [comment]
I also encountered this problem on 1.88 and had to downgrade to 1.87.2 as @webhype mentioned to get debugging back for my typescript apps.

**Comment by connectdotz** [comment]
The underlying issue (microsoft/vscode#209785) is closed, and the fix has been released in vscode 1.88.1. 

@lamuertepeluda, @webhype, @KyleLehtinenDev,  could you guys update the vscode to verify if that resolved your issue?

**Comment by lamuertepeluda** [comment]
> The underlying issue (microsoft/vscode#209785) is closed, and the fix has been released in vscode 1.88.1. 
> 
> @lamuertepeluda, @webhype, @KyleLehtinenDev,  could you guys update the vscode to verify if that resolved your issue?

I updated to 1.88.1 and I am now able to use the debugger again! Thanks

**Comment by connectdotz** [comment]
thanks @lamuertepeluda. closing this issue as resolved.
