### ISSUE TITLE
[BUG] This project cannot be used

### ISSUE THREAD

**Issue by crazyair** [jest-community/vscode-jest#1137]
**Describe the bug**

**To Reproduce**
 https://github.com/react-component/cascader

Note: A sample repo will help us identify the bug much faster. 🙏

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
- vscode-jest version:[e.g., v6.2.1]
- `node -v`: [e.g., 20.9.0]
- `npm -v` or `yarn --version`: [e.g., npm 10.1.0]
- jest or react-scripts (if you haven’t ejected) version: [e.g., jest 29.7.0]
- your vscode-jest settings:
    - jest.jestCommandLine? [e.g., npm test --]
    - jest.runMode? [e.g., on-demand]
    - jest.outputConfig? [e.g., none]
    - anything else that you think might be relevant? [e.g., none]
- Operating system: [e.g., MacOS 14.2.1]

**Prerequisite**
- are you able to run jest from the command line? [e.g., yes]
- where do you run jest CLI from? [e.g., root directory of the project]
- how do you run your tests from the command line? (e.g., "npm run test" or "node_modules/.bin/jest") 

**Additional context**

---

The fastest (and the most fun) way to resolve the issue is to submit a pull request yourself. If you are interested, please check out the [contribution guide](https://github.com/jest-community/vscode-jest/CONTRIBUTING.md), we look forward to seeing your PR...

**Comment by crazyair** [comment]
![image](https://github.com/jest-community/vscode-jest/assets/7971419/bf756c1c-fc64-423b-90ce-08d85576ede8)

```json
{
  "jest.jestCommandLine": "npx rc-test"
}

```

**Comment by crazyair** [comment]
```json
{
  "jest.jestCommandLine": "npm run test"
}

```

![image](https://github.com/jest-community/vscode-jest/assets/7971419/64ec6ec7-04ee-49fa-9212-51b8eceaa1da)

**Comment by connectdotz** [comment]
@crazyair , a few things:

1. "npx rc-test" seems to misinterpret the jest command line option "--watchAll=false". It went into watch mode instead, the opposite of what it should do. You can easily verify this with 
```
npx rc-test --listTests  --watchAll=false
```
Compared with running jest directly:
```
npx jest --listTests  --watchAll=false
```
This is why your first screenshot showed spinning status as the run was never finished. This is similar to the issue [here](https://github.com/jest-community/vscode-jest/issues/1124#issuecomment-2000596099), which will be killed automatically after PR #1134 release.

2. The good news is you can work around this with the following settings:
```
"jest.jestCommandLine": "npm run test --"
or
"jest.jestCommandLine": "yarn test"
```

Your attempt to use "npm run test" is almost correct... just need to add "--" at the end.

Please let me know if you still have any other questions.

**Comment by crazyair** [comment]
https://github.com/jest-community/vscode-jest/pull/1134 When to release, after release I verify that the next run does not stop the problem.

Also, where can I see the execution of the command. Influence. Sometimes I do. Sometimes not.

**Comment by connectdotz** [comment]
Sorry if I didn't make it clear: v6.2.4 hasn't been released yet. 

> Also, where can I see the execution of the command

You can also see the jest commands in the "Jest (xxx)" Terminal; or if you have "jest.debugMode" set to true, it will show the full spawned command in your developer console too.

**Comment by crazyair** [comment]
> Sorry if I didn't make it clear: v6.2.4 hasn't been released yet. I plan to release it this week.
> 
> 
> 
> > Also, where can I see the execution of the command
> 
> 
> 
> You can also see the jest commands in the "Jest (xxx)" Terminal; or if you have "jest.debugMode" set to true, it will show the full spawned command in your developer console too.

Yeah, I know. I'm waiting.

**Comment by connectdotz** [comment]
@crazyair, v6.2.4 has been released. Can you confirm if your problem is resolved?

**Comment by crazyair** [comment]
> @crazyair, v6.2.4 has been released. Can you confirm if your problem is resolved?

yes
