### ISSUE TITLE
[FEATURE] Run Tests button still visible in folded-code

### ISSUE THREAD

**Issue by walston** [jest-community/vscode-jest#1139]
**Describe the solution you'd like**
I want the ▶️ button to the left of line-numbers to persist when code folds (see images).

<img width="187" alt="Screenshot 2024-04-12 at 08 22 19" src="https://github.com/jest-community/vscode-jest/assets/10055135/3a14eeb8-598e-4fde-ad24-a8984128d5f1">
<img width="182" alt="Screenshot 2024-04-12 at 08 21 57" src="https://github.com/jest-community/vscode-jest/assets/10055135/98dd70e3-ecd1-4779-b1ab-b0d155dc3fc4">

**Describe alternatives you've considered**
None

**Additional context**
N/A

**Comment by connectdotz** [comment]
Hmm... I can't reproduce your issue. The gutter menu (status/run) stays regardless of code folding. If it doesn't do that in your environment, it might be a bug. Please provide more details of your env so we can further investigate.

**Comment by walston** [comment]
Certainly,

OS: **MacOS Sonoma 14.4.1**
VS Code: **Version: 1.88.1**
Plugin: **Orta.vscode-jest**
> Last released: **2024-04-11, 12:35:23**
> Last updated: **2024-04-12, 06:15:49**
> Identifier: **orta.vscode-jest**

### Recording
https://github.com/jest-community/vscode-jest/assets/10055135/7454dd9d-88e5-49f8-9eb3-f0f8b66d1d4b

Please let me know if there's anything else that could help diagnose it.

**Comment by connectdotz** [comment]
Oh, I see what you mean now. Thanks. 

This is not controlled by this extension. cc vscode @connor4312 for insight.

**Comment by walston** [comment]
Is this an issue I should post on VSCode? or Monaco?

**Comment by connectdotz** [comment]
@walston Yes I think you should open this issue with vscode directly.

**Comment by connor4312** [comment]
Thanks, this is already tracked in https://github.com/microsoft/vscode/issues/187834
