### ISSUE TITLE
[BUG] "Play" icons move after running test suite

### ISSUE THREAD

**Issue by mortske** [jest-community/vscode-jest#1142]
**Describe the bug**
Ive been using your extension for several years not but about a month ago, this issue started. When i first run a selected part of the test suite using the extension. Either via the test explorer or directly from the icons in the file. The icons move around seemingly randomly. It also does not highlight where the test failed as per usual either.
I realize this bug might be hard for you guys to reproduce if it's not something you are already aware of but i cant find any info on this online so i'm hoping you know of some steps to take to solve this issue.

**To Reproduce**
1. Run the test-suite and wait for it to finish
2. Icons move around

**Expected behavior**
I expect the icons to stay at the same spot (1 for each describe, it and test defined in the file).

**Screenshots**
As you can see, it seems to have moved to a random line in the middle of a test.
![Screenshot 2024-04-22 at 16 47 34](https://github.com/jest-community/vscode-jest/assets/10628742/72201ea5-8a10-4808-86d6-7838d0ffddcd)

Notice how it moves to row 509. 
https://github.com/jest-community/vscode-jest/assets/10628742/d9af1353-9db2-46ec-aa65-53a1f61c54c0

**Environment (please complete the following information):**
- vscode-jest version: v6.2.4
- `node -v`: v20.10.0
- `npm -v` or `yarn --version`: v10.2.3
- jest or react-scripts (if you haven’t ejected) version: jest 29.5.0
- your vscode-jest settings:
    - jest.jestCommandLine? none
    - jest.runMode? on-demand
    - jest.outputConfig? none
    - anything else that you think might be relevant? none
- Operating system: MacOS Sonoma 14.4.1

**Prerequisite**
- are you able to run jest from the command line? yes
- where do you run jest CLI from? root directory of the project
- how do you run your tests from the command line? "npm run test" which just runs "jest"

**Additional context**

---

**Comment by connectdotz** [comment]
@mortske, you're correct in noting that we haven't observed this behavior in our environments.

The icon location is determined by the lexical analysis of `@babel/parser` and our matching algorithm. I won’t dismiss the possibility of an edge case bug; however, it's challenging to pinpoint the issue without a reproducible example.

Does this issue occur with every test, test file, or workspace? Are there any errors or warnings in the console log? Can you identify any dependency or source-map-related changes that might correlate with the appearance of this bug? Providing a sample repository would greatly help us to investigate further.

**Comment by mortske** [comment]
I cannot seem to reproduce this issue in other workspaces, but at the same time, my coworkers that work in the same workspace do not have this issue (which makes me think it's not related to how the workspace is set up), so i don't think providing you with a sample repo would be possible in this case :/
But in this workspace, it is indeed for me concistent over all files and all tests. I don't see anything unusual in the console log, and when i run the "regular" jest from the terminal everything works as per usual.
I realize this is a long shot and i'm sure a super obscure edge case in some manner, and i totally get if you cannot help me further, i was mostly hoping this is something you've run into before :) Is there something i can do to debug my own setup that would help in pinning this down?

**Comment by mortske** [comment]
After debugging the whole day, I actually seem to have found the causing issue. We had a whole lot of tests with dynamic names, similar to it(`should do something when foo is ${FOOTYPES.BAR}`). Removing all of these dynamic types seem to resolve all strange issues with it moving around 🤔 So im closing this for now, and thank you for trying to help! really appreciate it!
