### ISSUE TITLE
[BUG] vscode-jest-tests.v2 Debug Configuration does not replace variables when restarting session

### ISSUE THREAD

**Issue by tim-helloquickly** [jest-community/vscode-jest#1148]
**Describe the bug**

**To Reproduce**
1. Debug a test with the default v2 configuration
2. Set a breakpoint and let it stop
3. Click the "restart" button on the menu bar
4. See error, command runs but with the litt

**Expected behavior**
Expect the same test to run the same way as the first time:
jest --runInBand --watchAll=false --testNamePattern 'redacted$' --runTestsByPath /Users/redacted.test.tsx --testTimeout=100000000 --coverage=false

But the second time around, 

jest --runInBand --watchAll=false --testNamePattern '${jest.testNamePattern}' --runTestsByPath '${jest.testFile}' --testTimeout=100000000 --coverage=false

**Screenshots**
Here is an output

**Environment (please complete the following information):**
- vscode-jest version: v6.2.5
- `node -v`: v18.18.0
- `npm -v` or `yarn --version`: yarn 1.22.19
- jest or react-scripts (if you haven’t ejected) version: jest 29.3.1
- Operating system: MacOS 14.2.1

**Prerequisite**
- are you able to run jest from the command line? Yes
- where do you run jest CLI from? Root
- how do you run your tests from the command line? jest

**Additional context**

**Comment by connectdotz** [comment]
@tim-helloquickly, thanks for bringing this to our attention, I can confirm this is a reproducible bug. I am working with the vscode team to see how we can best resolve it (https://github.com/microsoft/vscode/issues/212005).

**Comment by connectdotz** [comment]
@tim-helloquickly, I can't seem to be able to reproduce this issue today. Thinking maybe vscode has fixed it already. Can you confirm in your env?

**Comment by tim-helloquickly** [comment]
I gave it a shot, I can still reproduce  -- here is my configuration: 
```
    {
      "type": "node",
      "name": "vscode-jest-tests.v2",
      "request": "launch",
      "args": [
        "test",
        "--watchAll=false",
        "--forceExit",
        "--testNamePattern",
        "${jest.testNamePattern}",
        "--testTimeout=100000000",
        "--runTestsByPath",
        "${jest.testFile}"
      ],
      "cwd": "${workspaceFolder}",
      "console": "integratedTerminal",
      "internalConsoleOptions": "neverOpen",
      "runtimeExecutable": "yarn",
      "skipFiles": [
        "<node_internals>/**",
        "${workspaceFolder}/<node_internals>/**",
        "${workspaceFolder}/node_modules/**"
      ]
    },
    ``` 
    
    
One thing to note -- if I omit adding a jest configuration to the launch.json and just go with the default, it works properly (so it's specifically the variable substitution

**Comment by tim-helloquickly** [comment]
I think maybe I was on an outdated version. It works perfectly now!
