### ISSUE TITLE
[FEATURE] Single test result output

### ISSUE THREAD

**Issue by akrolasik-bc** [jest-community/vscode-jest#1149]
Hello!

I tried to use the outputConfig settings to remove the column with "test run at..." on the right of the test results panel; unfortunately, I couldn't. Please provide the configuration to do so. Seeing test results in two places seems to be redundant and limits the actual test results output.

Best regards,
Aleksander

**Comment by akrolasik-bc** [comment]
1. What is the exact use case for the test run history?
2. Why can I no longer click on a test in the test explorer and see the test result?
3. The icon aesthetics are nice, but with low contrast or in bright conditions, the green/red status is barely distinguishable.
4. Is it possible to explicitly use the previous version of the extension?

**Comment by connectdotz** [comment]
Hi @akrolasik-bc,

To disable the "test run at..." panel, also known as the "Test Results" panel, you need to disable the VSCode setting `"testing.openTesting"` in addition to `jest.outputConfig` (see [Handling Conflicts with "TEST RESULTS" panel setting](https://github.com/jest-community/vscode-jest#outputconfig-conflict)).

**Regarding your other questions:**

Please note that the "Test Results" panel is provided by the VSCode testing framework. This extension provides the test content to be displayed in the Test Explorer treeView and Test Results panel via the VSCode API.

> 1. What is the exact use case for the test run history?

The test run history allows users to see the results of previous test runs and re-run them if needed. For more detailed use cases, you might want to follow up with the VSCode team.

> 2. Why can I no longer click on a test in the Test Explorer and see the test result?

As far as I remember, it used to reveal the last run results, and now that feature has been moved to the "Test Results" history list. You can still open the entire "Test Results" panel from the Test Explorer's display buttons. 

> 3. The icon aesthetics are nice, but with low contrast or in bright conditions, the green/red status is barely distinguishable.

You can submit a request directly to the VSCode team to address this issue. Improving icon contrast is important for accessibility.

> 4. Is it possible to explicitly use the previous version of the extension?

Yes, you can install a previous version of the extension. In VSCode, go to the Extensions view (`Ctrl+Shift+X`), find the Jest extension, click on the gear icon next to it, and select "Install Another Version...". From there, you can choose the version you want to install.

I hope this helps! Feel free to ask if you have any more questions.

**Comment by akrolasik-bc** [comment]
This is very helpfull. Thank you for the answers!
