### ISSUE TITLE
Search for "jest" in the Test Explorer matches every test

### ISSUE THREAD

**Issue by dinofx** [jest-community/vscode-jest#1150]
**Describe the bug**
I work on a dev tool that other developers use to run the jest tests in their repos. Some of our tests have "jest" in the name.  There seems to be no way to filter for these tests.  My guess is that VSCode is matching "jest" against the test provider.

Substrings like "jes" or "est" also match every test.

**To Reproduce**
1. Have a bunch of tests, some of which have "jest" in their name.
2. Search for "jest" in the test explorer view.

**Expected behavior**

Ideally any labels implicitly added to every test would be some kind of tag like `@jest`, and wouldn't match when searching for the string "jest"

**Environment (please complete the following information):**

- vscode-jest version:[e.g., v6.2.5]

**Comment by connectdotz** [comment]
This is interesting. However, the Test Explorer search function is managed by the VS Code team. Please open the issue directly with [VS Code](https://github.com/microsoft/vscode/issues) to get proper traction.
