### ISSUE TITLE
[FEATURE]: Allows to update the configuration per projects

### ISSUE THREAD

**Issue by thuandohoang** [jest-community/vscode-jest#1159]
**Is your feature request related to a problem? Please describe.**

I'm working on multiple projects (web FE with ReactJS and mobile with ReactNative). Each project has a different root file. It's quite annoying when updating the rootPath every time I switch to work on each project.

**Describe the solution you'd like**
I would be nice if the plugin allows me to configure the rootPath for each project.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by connectdotz** [comment]
This extension's configuration is stored in VSCode's settings.json (single-root workspace) or .code-workspace ([multi-root workspace](https://code.visualstudio.com/docs/editor/multi-root-workspaces)) file. You should be able to configure the extension per project today by setting the `jest.rootPath` in the respective configuration file of each project.

If you can provide more details on how your projects are set up in VSCode, such as whether you're using single or multi-root workspaces and any specific configurations, we can offer more tailored assistance.

Looking forward to helping you further.

**Comment by thuandohoang** [comment]
Thanks @connectdotz, I found out we can have project configuration using `.vscode/setting.json` file.
