### ISSUE TITLE
[FEATURE] Hide terminals

### ISSUE THREAD

**Issue by SpencerKaiser** [jest-community/vscode-jest#1166]
**Is your feature request related to a problem? Please describe.**
My team is frustrated by the large number of terminals opened by the Jest extension within our mono repo. We use a code-workspace' file to logically organize our child project directories and each has a jest root associated with it. Everything works as expected, however, there are a large number of terminals that open.

**Describe the solution you'd like**
A config flag to prevent a terminal from being created in favor of something that just runs in the background.

**Describe alternatives you've considered**
Several members of my team have chosen to disable auto-run and instead rely on the buttons provided by jest-runner to trigger individual executions on demand, which in turn, don't populate errors inline 😔

**Comment by connectdotz** [comment]
This is a duplicate request as #1143. Let's resume the discussion there...
