### ISSUE TITLE
Running individual test on windows uses a caret (^) as escape character in the testNamePattern

### ISSUE THREAD

**Issue by necjosh** [jest-community/vscode-jest#1175]
**Describe the bug**
Instead of a backslash, a caret is used to escape special characters in the `testNamePattern` when running an individual test through the UI.
This causes the test to be skipped.

What I also find curious is that the `testNamePattern` is included in the command at all. I'm running the entire test file, I don't understand why it's including it since the `testPathPattern` already narrows it down to the file exclusively.

``` js
describe("foo >", () => {
    it("bar", () => {
        expect(1).toBe(1);
    });
});
```
```
Test Suites: 1 skipped, 0 of 1 total
Tests:       1 skipped, 1 total
Snapshots:   0 total
Time:        1.262 s
Ran all test suites matching [omitted]jest-repro\\src\\App\.test\.js/i with tests matching "foo ^> bar$".
```

Spawn command: `[Extension Host] spawning process with command=npm test -- --testLocationInResults --json --useStderr --outputFile [omitted] --testNamePattern "foo ^> bar$" --no-coverage --reporters default --reporters "[omitted]" --colors --watchAll=false --testPathPattern "[omitted]\\src\\App\.test\.js"`

I added more special characters to see which ones are affected:
``` js
describe("foo ` ~ ! @ # $ % ^ & * ( ) { } [ ] / = ? + _ - , . < > ' \"", () => {
    it("bar", () => {
        expect(1).toBe(1);
    });
});
```

```
Test Suites: 1 skipped, 0 of 1 total
Tests:       1 skipped, 1 total
Snapshots:   0 total
Time:        1.712 s
Ran all test suites matching [omitted]\\src\\App\.test\.js/i with tests matching "foo ` ~ ^! @ # \$ % \^^ ^& \* \( \) \{ \} \[ \] / = \? \+ _ - , \. ^< ^> ' " bar$".
```

`! ^ & < >` are affected.

**To Reproduce**
[Sample repo](https://github.com/necjosh/jest-repro)

1. Run the single test in the UI

**Expected behavior**
Backslashes are used to escape special characters in the testNamePattern.

**Environment (please complete the following information):**
- vscode-jest version: _v6.2.5_
- `node -v`: _21.6.1, also tested on LTS 20.17.0_
- `npm -v` or `yarn --version`: _npm 10.2.4_
- jest or react-scripts (if you haven’t ejected) version: _react-scripts 5.0.1 (also tested on company's repo using Jest v29.7.0, no react-scripts)_
- your vscode-jest settings:
    - jest.jestCommandLine? _N/A_
    - jest.runMode? _on-demand_
    - jest.outputConfig? _none_
    - anything else that you think might be relevant? _The error was reproduced by all my colleagues, with varying setups, although all running Windows 11._
- Operating system: _Windows 11 Business version 23H2_

**Prerequisite**
- are you able to run jest from the command line? _yes_
- where do you run jest CLI from? _root directory of the project_
- how do you run your tests from the command line? `npm run test`, `npx jest`

**Comment by necjosh** [comment]
I had no idea that `^` is used as an escape character in CMD....
Anyway, it seems that there is no need to use an escape character in the testNamePattern, I suppose because it's in quotes?

CMD does not interpret `^` as an escape character in this portion of the command, so it's passed on as an actual part of the regexp.

**Comment by necjosh** [comment]
I confirmed this by running a few commands in CMD.

``` yml
#command:
Echo THIS & THAT

#output:
THIS
'THAT' is not recognized as an internal or external command,
operable program or batch file.

#command:
Echo THIS ^& THAT

#output:
THIS & THAT

#command:
Echo "THIS & THAT"
#output:
"THIS & THAT"

#command:
Echo "THIS ^& THAT"
#output:
"THIS ^& THAT"
```

As you can see in the last example, the caret does not act as an escape character in this case.

**Comment by connectdotz** [comment]
yes, this looks like a bug... thanks for raising the issue, I will take a look.

**Comment by connectdotz** [comment]
@necjosh, I think I have a fix. Do you mind confirming if the new build fixes your issue:
[vscode-jest-6.3.0.vsix.zip](https://github.com/user-attachments/files/16938482/vscode-jest-6.3.0.vsix.zip)
