### ISSUE TITLE
[Feature request] Ability to just run the last changed test file

### ISSUE THREAD

**Issue by jackfranklin** [jest-community/vscode-jest#119]
Just had a case where I was working on file `foo.js` and `foo.spec.js`. Foo is used in a bunch of places, so upon changing it Jest correctly figures out that it has 10 spec files that it should run. This is great most of the time, but it means that I have to wait longer to know if `foo.spec.js` has passed or not. An option to turn on a "single file" mode where it only runs the last changed spec file on each change would be quite useful.

I'm quite happy to attempt some work on this if you think it's a reasonable addition :)

**Comment by orta** [comment]
Yep, sounds good to me.

This would need to be something where the extension itself controls what test is being ran, which it currently doesn't. It'd require turning off it's `--watch` process and starting to handle it's own, very feasible.

**Comment by jackfranklin** [comment]
Probably something that you'd want to be able to trigger via the command window, so alongside 'Jest start watching' + 'Jest stop watching' you might have 'Jest run last test file mode' or something better worded !

I'm very new to VSCode + extensions but I'll try to start hacking something soon.

**Comment by orta** [comment]
Yeah, makes sense, and maybe add a button on the bar to turn it off:

![screen shot 2017-06-08 at 18 56 56](https://user-images.githubusercontent.com/49038/26943082-42d08358-4c7c-11e7-99ac-51580f86183c.png)

**Comment by orta** [comment]
I've been having a think about this:  I'd like the ability to toggle on a single file mode on the watcher - perhaps this could be an action button in the top right (https://github.com/orta/vscode-react-native-storybooks/issues/26), which closes the current watcher and a version of the watcher that includes a suffix of the filepath.

**Comment by seanpoulter** [comment]
I love the idea of being able to run one file. If we wanted to be able to test the unsaved changes to the document, we'd need to be able to test just one file first.

The other option we may not have explored yet is setting up our own reporter to stream tests results as they happen with IPC.

**Comment by goodbomb** [comment]
Any updates on this?

**Comment by haroonKhan-10p** [comment]
+1

**Comment by seanpoulter** [comment]
@marcinczenko's PR has been merged if anyone wants to have a go at a PR.

**Comment by connectdotz** [comment]
after 3 years, we finally added this feature... Please feel free to give  [v4.0.0-alpha.5](https://github.com/jest-community/vscode-jest/releases/tag/v4.0.0-alpha.5) a try and let us know if it works for you.

**Comment by sneko** [comment]
@connectdotz I read multiple times https://github.com/jest-community/vscode-jest/blob/master/README.md#how-to-trigger-the-test-run and I'm able to turn off the autorun as mentioned in the original post I'm looking for running only the last file/test that has changed.

By default `--watch` will run all uncommitted test files, I'm looking for option to say "let's focus just on last runs". Is it possible?

**Comment by connectdotz** [comment]
@sneko, the default autoRun is to run only changed files (the watch mode). Did I miss something?
