### ISSUE TITLE
Toggling coverage overlay requires refreshing page 

### ISSUE THREAD

**Issue by smith** [jest-community/vscode-jest#177]
### Environment

1. `node -v`: v8.6.0
2. `npm -v`: 5.3.0
4. `npm ls react-scripts` (if you haven’t ejected): (empty)

1. Operating system: macOS 10.13.1

### Steps to Reproduce

Coverage overlay is not shown. Do `Toggle coverage overlay`. Still not shown. Switch to another file. Switch back. Overlay is shown.

### Expected Behavior

Coverage overlay is not shown. Do `Toggle coverage overlay`. Overlay is shown.

### Actual Behavior

See above.

In overlay.ts we're just doing `() => (showCoverage = !showCoverage)`, but I don't think that makes anything happen, like the page refreshing (or whatever you're supposed to do with the extension API.) How would one add that?

Also, if someone were to add an indicator that the coverage overlay were on or off, where would be the best place to do that? I was thinking maybe the lens at the top could show `lines: ..., branches: 95%, overlay: true` but I'd like some better opinions. Thanks!

**Comment by orta** [comment]
I don't think it makes sense to add a codlins (like the debug buttons) but I think it does make sense to fix the bug where it doesn't show the coverage on your first run. Want to look at it?

**Comment by smith** [comment]
> I don't think it makes sense to add a codelens (like the debug buttons)

I really think that *somewhere* it should tell me whether the coverage overlay is on or off. Doesn't need to be in a lens at all, but there's no way of telling right now and it's frustrating.

> I think it does make sense to fix the bug where it doesn't show the coverage on your first run. Want to look at it?

Yes, but I'm not at all familiar with the extension API. Where would I start? I understand the code that's there but am having trouble finding how to trigger a refresh or whatever the proper thing to do would be.

**Comment by seanpoulter** [comment]
For the feature request to indicate the coverage overlay, how about adding a "Coverage" status bar item that will show a menu with "Enable", "Disable". The line endings menu already has something like this when you click on it:

![2017-12-01 -- vscode-jest 177 - line endings](https://user-images.githubusercontent.com/2585460/33511689-561372bc-d6ed-11e7-9b1b-3f20e178d1d9.gif)

**Comment by seanpoulter** [comment]
Huh, if you try and toggle the code coverage off the highlighting doesn't clear. :upside_down_face:

**Comment by seanpoulter** [comment]
@smith, you found the right spot in the code to toggle the overlay. You're also right that we're missing the call to refresh the code coverage [`showCoverageOverlay(...)`](https://github.com/orta/vscode-jest/blob/973cd5bf3a4cb0603f6b21db0043f685641f6a79/src/Coverage/overlay.ts#L23). It's called in `JestExt.ts` and passed a reference to the editor and the current coverage data. It's a bit of a mess to unwind but do-able. Have you made any progress?

**Comment by smith** [comment]
This was fixed a while ago. Thanks!

**Comment by seanpoulter** [comment]
But the quick pick menu ... 😉
