### ISSUE TITLE
Debug command doesn't use jest.pathToConfig setting

### ISSUE THREAD

**Issue by Guymestef** [jest-community/vscode-jest#191]
### Environment

1. `node -v`: v9.2.0
2. `npm -v`: 5.5.1
4. `npm ls react-scripts` (if you haven’t ejected): -- (empty)

1. Operating system: Windows 10 x64

### Steps to Reproduce

- Set jest.pathToConfig setting: "jest.pathToConfig": "ClientApp\\test\\config\\jest.config.js"
- Write a failing test
- Click on Debug tag over the test first line

### Expected Behavior

Run the test in debug by using the provided jest config

### Actual Behavior

Run the test with default jest config and so in my case doesn't find the test

--- 

Note we are looking for someone to take responsibility around keeping create-react-app up to date and working, could this be you?

**Comment by VinceOPS** [comment]
Hi!

Sorry to wake this up but the plugin stopped working here, since a few days. It looks like `pathToConfig` is not taken into account anymore by the "Debug" command. My testMatch regex (which is different from the default) is not displayed anymore in the output (the jest default is shown).

**Comment by dejancrn** [comment]
This does not work in latest version. It seems code was refactored some time ago and it no longer adds "--config" param to args
