### ISSUE TITLE
Debug CodeLens doesn't use jest.pathToJest

### ISSUE THREAD

**Issue by seanpoulter** [jest-community/vscode-jest#193]
### Steps to Reproduce
- Clone `git clone https://github.com/seanpoulter/vscode-jest--193`
  - This is a bare repo bootstrapped for issue #190 with "jest.pathToJest" set and a failing test
- Open the repo in Visual Studio Code
- Click on the Debug CodeLens

### Expected Behavior
- Debug the test
- [`JestExt#resolvePathToJestBin()`](https://github.com/orta/vscode-jest/blob/e166c3718307efc85589a656dcdcd2fd8808c175/src/JestExt.ts#L491) can handle more complicated commands like `npm test --`

### Actual Behavior
![image](https://user-images.githubusercontent.com/2585460/33959961-26b2cecc-e017-11e7-9271-b3beecdc1317.png)

**Comment by stephtr** [comment]
This is now by design (#287).
