### ISSUE TITLE
Should we hide the Debug CodeLens on skipped tests?

### ISSUE THREAD

**Issue by seanpoulter** [jest-community/vscode-jest#197]
The "Debug" CodeLens is shown for skipped tests in version 2.5.4. Does that make sense? Is there a way to configure Jest to run skipped tests?

![image](https://user-images.githubusercontent.com/2585460/34158756-b0979dd0-e494-11e7-9fe3-51b7ad8326f1.png)

**Comment by orta** [comment]
Yep
