### ISSUE TITLE
when I click "Debug" the jest runs in the wrong directory

### ISSUE THREAD

**Issue by capaj** [jest-community/vscode-jest#199]
1. Operating system: ubuntu 17.10

### Steps to Reproduce

when I click
![image](https://user-images.githubusercontent.com/1305378/34295517-107da9e4-e70e-11e7-9baf-f2d5b07beb9f.png)

### Expected Behavior

I expect jest to run in `In /home/capaj/git_projects/looop/project-alpha/back-end`

### Actual Behavior

jest runs in the other folder I have in my workspace
![image](https://user-images.githubusercontent.com/1305378/34295560-42d3b56e-e70e-11e7-90f8-9a36365f2c23.png)
and fails to find any tests

I have these three folders in my workspace:
![image](https://user-images.githubusercontent.com/1305378/34295600-81737f02-e70e-11e7-87fb-3be7b7f93958.png)

**Comment by orta** [comment]
I don’t think this plugin supports workspaces, you’re welcome to give adding it a shot

**Comment by stephtr** [comment]
Using today's update you should be able to debug Jest in a custom directory by generating and modifying a debug configuration (See [How do I debug tests?](I'm closing it since it got resolved with today's update.)).

**Comment by stephtr** [comment]
> Just commenting to add some keywords for future searchers, as this wasn't as clear from the readme as the above comment made it, and this issue took ages to track down :)

Making it clear in the readme would be even better 😉.
Would it help if one extends the first paragraph in [How do I debug tests?](https://github.com/jest-community/vscode-jest/blob/master/README.md#how-do-i-debug-tests) by the case that debugging runs within the wrong directory?
