### ISSUE TITLE
dot decorations not working properly

### ISSUE THREAD

**Issue by uucue2** [jest-community/vscode-jest#206]
### Environment

1. `node -v`: 8.9.1
2. `npm -v`: 5.6.0
3. Operating system: Windows Server 2016

### Issue

The dot decorations aren't working correctly after upgrading to 2.5.7. Inline failure messages also don't seem to be working.

### Expected Behavior (using 2.5.6)

![image](https://user-images.githubusercontent.com/12840079/34391529-cda578fc-eb0b-11e7-8656-efffde0179d0.png)

![image](https://user-images.githubusercontent.com/12840079/34391541-e3a017b6-eb0b-11e7-851a-036b26893696.png)

### Actual Behavior (using 2.5.7)

![image](https://user-images.githubusercontent.com/12840079/34390398-37efd47a-eb05-11e7-91f3-4b7c8f244b1b.png)

![image](https://user-images.githubusercontent.com/12840079/34390413-44606904-eb05-11e7-927b-eb46e5a5a6fd.png)

**Comment by seanpoulter** [comment]
@uucue2, could you do me a huge favor and share the JSON output from Jest on that PC? This will get the results on the clipboard:
```
node node_modules/.bin/jest --json | clip
```
<br/>

The only change that went out in 2.5.7 was a bug fix that assumed Jest would always return filenames with uppercase drive letters. I'm expecting that's not the case. :cry:

**Comment by uucue2** [comment]
@seanpoulter, running `node node_modules/.bin/jest` just throws an error:

![image](https://user-images.githubusercontent.com/12840079/34392178-29c9e506-eb10-11e7-9dc8-29ca3e64644e.png)

I'm not 100% clear on what you need. Do you just want the JSON output of jest being run? If so, here you go:

{"numFailedTestSuites":0,"numFailedTests":0,"numPassedTestSuites":1,"numPassedTests":1,"numPendingTestSuites":0,"numPendingTests":0,"numRuntimeErrorTestSuites":0,"numTotalTestSuites":1,"numTotalTests":1,"snapshot":{"added":0,"didUpdate":false,"failure":false,"filesAdded":0,"filesRemoved":0,"filesUnmatched":0,"filesUpdated":0,"matched":0,"total":0,"unchecked":0,"uncheckedKeys":[],"unmatched":0,"updated":0},"startTime":1514406123820,"success":true,"testResults":[{"assertionResults":[{"ancestorTitles":[],"failureMessages":[],"fullName":"1 + 2 should equal 3","location":null,"status":"passed","title":"1 + 2 should equal 3"}],"endTime":1514406126656,"message":"","name":"C:\\_code\\Intranet\\trunk\\Web\\FrontEnd\\front-end-testing\\src\\components\\Main\\Main.test.tsx","startTime":1514406124726,"status":"passed","summary":""}],"wasInterrupted":false}

**Comment by seanpoulter** [comment]
Thanks @uucue2, the JSON output is what I was hoping for. If that's the output from Server 2016 it rules out my hunch. I've assumed that the Jest results always have an uppercase drive letter, which is what the `"name":"C:\_code\..." rules out. [The change](https://github.com/jest-community/vscode-jest/pull/204/files#diff-5682a320f977b353b51a2de78c6f6b1f) for 2.5.7 should only apply to that.

Since it seems like there's something else going on, could you help debug the extension when you've got some time? It takes a few minutes to clone the repo and install the node modules, but after that it's just starting the "Launch Extension" debug task and setting a breakpoint to see what's up. I'd expect there's a problem around that `getAssertions` call in the `TestResultsProvider`.

**Comment by uucue2** [comment]
Okay, so the problem seems to be that when this is called with a lowercase drive letter, as such:

![image](https://user-images.githubusercontent.com/12840079/34393869-59182b96-eb1b-11e7-8010-b802be95f367.png)

it passes the uppercase transformed path to `assertionsForTestFile`, but that function seems to still be expecting the lowercase version:

![image](https://user-images.githubusercontent.com/12840079/34393919-aa7ab814-eb1b-11e7-94f0-3d7a6876e3b1.png)

so `results` is undefined

**Comment by seanpoulter** [comment]
Thanks @uucue2! The screenshots are very helpful and frustrating. I made the wrong call putting the adapter where we lookup the test results. I'll move it into `updateTestResults` to fix the keys there.
