### ISSUE TITLE
"update snapshots" message doesn't show up if multiple snapshot tests fail

### ISSUE THREAD

**Issue by uucue2** [jest-community/vscode-jest#209]
### Issue

This may be by design, but the message that pops up that asks the user if he/she wants to update a failing snapshot doesn't show up if multiple snapshot tests fail.

The issue is pretty simple - `JestExt.ts` only tests for whether snapshot tests failed by doing this:

```noANSI.includes('snapshot test failed')```

Which i believe is operating under the assumption that your jest output will have something like this in it:

› 1 snapshot test failed.

The problem is that when there are multiple failing snapshot tests, the jest output looks something like this:

› 4 snapshot tests failed.

So that condition obviously isn't met and the message never pops up.

### Proposed Solution

`noANSI.includes('snapshot test failed')` -> `/snapshot tests? failed/i.test(noANSI)`

**Comment by seanpoulter** [comment]
Thanks for the PR @uucue2.
