### ISSUE TITLE
enable auto-start if jest.config.js is found in the workspace

### ISSUE THREAD

**Issue by uucue2** [jest-community/vscode-jest#210]
### Issue
Currently, if your node_modules folder isn't in the project directory (i.e. you need to use the "jest.pathToJest" option for this extension to work), you pretty much just have to live with the fact that you need to start this extension manually. However, i think it makes sense to also enable auto-start by checking if a jest.config.js file exists in the workspace. 

We have a bit of a non-traditional setup, but basically, our node_modules are shared between multiple projects, so we don't necessarily want individual node_modules folders in each project directory, but if moving the config out of the shared package.json to individual jest.config.js files would enable this extension to run on project-open, i'd happily do that.

### Proposed Solution
add...

```workspaceContains:jest.config.js```

...to the `activationEvents` array in `package.json`

**Comment by uucue2** [comment]
The same should also probably go for jest.json files in the workspace

**Comment by orta** [comment]
Yep 👍

**Comment by seanpoulter** [comment]
Closed by #216.
