### ISSUE TITLE
Plugin not reading jest.config.json file even when settings are updated

### ISSUE THREAD

**Issue by doomsbuster** [jest-community/vscode-jest#223]
The plugin is not honoring the `jest.config.json` file that has configurations for Less pre-processing.

```
FAIL ui/tests/components/Home.spec.js

  ● Test suite failed to run

    /Users/asdesai/Documents/coding/yeoman/react-boilerplate/ui/styles/components/home.less:8
     @fullWidth: 100%;
     ^
    SyntaxError: Invalid or unexpected token

    > 1 | import React from 'react'
      2 | // import DemoComponentLeft from './DemoComponentLeft'
      3 | // import DemoComponentRight from './DemoComponentRight'
      4 | import s from '../styles/components/home.less'
      
      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/script_transformer.js:318:17)
      at Object.<anonymous> (ui/components/Home.js:1:428)
      at Object.<anonymous> (ui/tests/components/Home.spec.js:2:320)


Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        0.546s
Ran all test suites related to changed files.
```

**Comment by seanpoulter** [comment]
Thanks for taking the time to report your issue @doomsbuster. Unfortunately there's not enough for me to help troubleshoot or recreate the problem. Could you please share the link to a repository with a minimal amount of code that reproduces the problem that we can clone and open in VS Code? If that's not an option, please provide detailed instructions to recreate your problem.

If I had to guess, it seems to me like you're using a non-standard config file. The [configuring Jest](https://facebook.github.io/jest/docs/en/configuration.html) docs say the expected file is called `jest.config.js` with a `.js` extension. You'll have to include the `--config` option in the `pathToJest` extension setting.

**Comment by doomsbuster** [comment]
@seanpoulter I uninstalled and re-installed the plugin and set the pathToConfig in the configuration file again. Then it worked. Not sure what the issue really was.

**Comment by seanpoulter** [comment]
Glad you've got it working!

Any chance you remember changing the Jest config and then it stopped working? Looking through the code it seems we load the settings when the extension starts (#225).

**Comment by doomsbuster** [comment]
I tried this on another instance of VSCode where i installed this plugin fresh, i ran into similar challenges. I configured the `jest.config.json` in the config path and it didnt work. This time around I am also seeing strange errors in the console like below:

```

--watch is not supported without git/hg, please use --watchAll 

Closed Jest
Jest exited unexpectedly, restarting watch mode
Closed Jest

--watch is not supported without git/hg, please use --watchAll 

Closed Jest
Jest exited unexpectedly, restarting watch mode
Closed Jest

--watch is not supported without git/hg, please use --watchAll 

Closed Jest
Jest exited unexpectedly, restarting watch mode
Closed Jest

--watch is not supported without git/hg, please use --watchAll 

Closed Jest
Closed Jest
```

**Comment by seanpoulter** [comment]
> --watch is not supported without git/hg, please use --watchAll 

The `--watch` option detects files changed since the last commit. When the folder you're working in hasn't been initialized as a git or Mercurial repo you'll get that message.
<br/>

**Comment by doomsbuster** [comment]
I am aware of the `watch` vs `watchAll` difference. I am using the `watchAll` for the test:watch script in `package.json` however, i have not provided any such specific settings for the Jest extension. Is it picking up default settings from somewhere?

```
  "scripts": {
    "test": "cross-env NODE_ENV=test LOG_LEVEL=debug jest --config jest.config.json --coverage",
    "test:watch": "cross-env NODE_ENV=test LOG_LEVEL=debug jest --config jest.config.json --watchAll --coverage"
  },
```

**Comment by seanpoulter** [comment]
The extension doesn't know about your `test:watch` script. At this time there's no way to pass the `--watchAll` option to Jest.
<br/>

Here's [this method](https://github.com/jest-community/vscode-jest/blob/master/src/helpers.ts#L12) to decide what to run when the `pathToJest` setting is undefined. We use:
* `npm test --` when the folder has been bootstrapped with `create-react-app`, `react-native-scripts`, or `react-scripts-ts`
* `node_modules/.bin/jest` otherwise

All tests are run then we restart with the `--watch` flag.

**Comment by doomsbuster** [comment]
I am not sure why the plugin would fail in that case. Without having tinkered with any plugin configurations it results in these errors when I fire it up. The only change I made to the configuration was to point it to the `jest.config.json` file.

**Comment by seanpoulter** [comment]
Which configuration did you change? The VS Code `settings.json` or in `package.json`?
This seems to be the same behavior as #157.

**Comment by doomsbuster** [comment]
This plugin's configuration property `jestConfigPath` in user preference settings in VSCode.

**Comment by stephtr** [comment]
> @orta, how do you feel about extending the Runner in jest-editor-support to support --watchAll? I'm thinking start() can also accept {watch: boolean, watchAll: boolean}.

So it probably would be best to look for `"please use --watchAll"` in the error output and restart with `--watchAll` instead of `--watch`? Should that change be done before, in combination or after merging #215?
