### ISSUE TITLE
Reload Jest when extension settings change

### ISSUE THREAD

**Issue by seanpoulter** [jest-community/vscode-jest#231]
### Steps to Reproduce

The behavior described in #157 and #223 leads me to believe that Jest is not updated when the extension settings change in VS Code's `settings.json`. It may also be the case when the Jest config changes, as defined in the defaults `package.json` or `jest.config.js`, or the user-defined value in `pathToConfig`.

### Expected Behavior

Changing extension settings or Jest configuration should not require users to relaunch the editor.

### Actual Behavior

Users may have to reload the window or relaunch VS Code.

**Comment by orta** [comment]
Shipped in #265
