### ISSUE TITLE
It's impossible to debug test cases with names containing quotes.

### ISSUE THREAD

**Issue by Aliaksei-Martinkevich** [jest-community/vscode-jest#236]
### Environment

1. `node -v`: [8.9.1]
2. `npm -v`: [5.5.1]
4. `npm ls react-scripts` (if you haven’t ejected): [fill]

1. Operating system: [Windows 10 Enterprise Version 10.0.15063 Build 15063 x64]

### Steps to Reproduce
1. Create test (it) with name that contains " symbol. For example: `it('Should return "undefined", ...')`
2. Press the 'Debug' link above test case.

### Expected Behavior
Debugger is connected and selected test is running.

### Actual Behavior
All test are skipped.

Note: `testNamePattern` value isn't escaped in terminal.

**Comment by orta** [comment]
Sounds pretty reasonablely scoped, want to try making a pr?

**Comment by Aliaksei-Martinkevich** [comment]
Why not.
