### ISSUE TITLE
"debug" tooltip only shows when test is failing

### ISSUE THREAD

**Issue by offero** [jest-community/vscode-jest#240]
I would like to run tests in the debugger even when they are passing so that I can inspect variables and add more cases. The plugin only adds the "debug" tooltip 

### Environment

1. `node -v`: v8.7.0
2. `npm -v`: 5.6.0

1. Operating system: OSX 10.13.2

### Steps to Reproduce

Create a test with describe/it. Make it pass.

### Expected Behavior

"debug" tool tip shows up.

### Actual Behavior

"debug" tool tip does not show.

**Comment by orta** [comment]
This was a conscious decision, perhaps you could consider a PR making an option for this?

**Comment by orta** [comment]
A great way to do that could be enum option of `"all", "failed", "none"` with failed as the default

**Comment by iMarv** [comment]
Would also really like an option to always enable debugging, as there are cases when tests pass, even though they should not.

**Comment by seanpoulter** [comment]
When #292 ships you'll have a new setting to configure when the Debug CodeLens appears @offero and @iMarv. Hopefully it's a pleasant user experience. 😉
