### ISSUE TITLE
Status bar message in red in case of errors

### ISSUE THREAD

**Issue by Litee** [jest-community/vscode-jest#250]
Hi,

What do you think about highlighting broken tests with red color in status bar? Here how it looks like in my experiment:

![image](https://user-images.githubusercontent.com/400234/35780434-6b6fe23a-09ec-11e8-8a77-4f2e54bc6bf9.png)

**Comment by stephtr** [comment]
In my opinion it is an interesting approach, but since the native error and warning signs are also kept in white, I would stick with that.

**Comment by orta** [comment]
Yeah, I agree, also we have no idea what color people's status bars are
