### ISSUE TITLE
Debug Requires test names to be a valid regex

### ISSUE THREAD

**Issue by BLamy** [jest-community/vscode-jest#251]
I have a test named `reset() -> Reset`. This really confuses the jest plugin because it takes the name of my test as a string and just assumes it's a valid regex. 

If I change my test name to:`test("reset( -> Reset", () => {})`

Debug will crash with this error:
![image](https://user-images.githubusercontent.com/324928/35813992-fbd9ab50-0a62-11e8-9f71-b59dc9ff3e8b.png)

**Comment by seanpoulter** [comment]
Thanks for identifying the problem @BLamy. Could you submit a PR to fix the problem? There's an example method to escape regular expression characters in the [MDN RegExp docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions).
