### ISSUE TITLE
Test status bullets don't get cleared, resulting in mutiple bullets

### ISSUE THREAD

**Issue by Hillshum** [jest-community/vscode-jest#259]
### Environment

1. `node -v`: 8.9.3
2. `npm -v`: 5.6.0
3. Ejected create-react-app
4. Operating system: Ubuntu 16.04

### Steps to Reproduce

https://github.com/Hillshum/double-bullets

1. Clone the repo, run `npm i`, open `foo.test.js` in VSCode with the Jest extension enabled.
2. Start the jest runner.
3. Stop the jest runner.
4. Start the jest runner again.

### Expected Behavior

When the jest runner gets stopped, I expect to see the green/red status bullets disappear from my tests. When I start the runner again, I expect to see only one bullet for each test.

### Actual Behavior

The bullets never get cleared, leading to multiple bullets per test until I close the file and reopen it.

![image](https://user-images.githubusercontent.com/185958/36225784-05749c7e-1189-11e8-8c8b-c17660087eef.png)

--- 

>Note we are looking for someone to take responsibility around keeping create-react-app up to date and working, could this be you?

Uhh...maybe.

**Comment by seanpoulter** [comment]
Thanks for reporting that @Hillshum. That sure doesn't seem right. It seems there's coupling between starting Jest and creating the dot decoration styles. Would you be willing to have a look at fixing that? It should be a quick PR.
<br/>

>> Note we are looking for someone to take responsibility around keeping create-react-app up to date and working, could this be you?

> Uhh...maybe.

We should chat with @orta about the best way to keep that up to date. I think he's started a PR to use Greenkeeper to bump versions. I was thinking it might be a good plan to try and run our CI with a few versions of create-react-app.

**Comment by niieani** [comment]
The same thing happens when the plugin is upgraded to a newer version (or temporarily disabled), the old bullets lag forever and even if you type, they will live on and have misaligned position.

**Comment by seanpoulter** [comment]
Thanks for pointing that out @niieani. We'll have to make sure they're cleared when the extension is disposed.

**Comment by orta** [comment]
Yeah, that last one feels a lot like https://github.com/jest-community/vscode-jest/issues/238

**Comment by Hillshum** [comment]
Well, I haven't encountered this lately.
