### ISSUE TITLE
Proper documentation for required restart when changing jest.pathToJest

### ISSUE THREAD

**Issue by gcangussu** [jest-community/vscode-jest#262]
### Environment

1. `node -v`: v8.9.4
2. `npm -v`: 5.6.0
3. `npm ls react-scripts` (if you haven’t ejected): n/a
4. Operating system: Ubuntu 16.04
5. Extension: 2.6.1

### Steps to Reproduce

1. Change workspace option `jest.pathToJest`
2. Stop runner
3. Start runner
4. Old configuration persists (new configuration is ignored).
5. Close and reopen vscode.
6. Start runner
7. New configuration is used

### Expected Behavior

Either `jest.pathToJest` documentation (comments on vscode settings) warns users about required restart or it won't require a restart.

### Actual Behavior

Losing 30 minutes trying to figure out why it isn't working.

**Comment by orta** [comment]
Hi, you're welcome to take a look at a PR at either having the config updating the config at runtime or at improving the docs 👍

**Comment by gcangussu** [comment]
@orta Thanks. I'll also look into changing the config at runtime. Shoud I make other issue before making another PR?
