### ISSUE TITLE
"Snapshot missing" for named snapshots

### ISSUE THREAD

**Issue by kanehara** [jest-community/vscode-jest#263]
### Environment

1. `node -v`: 9.5.0
2. `npm -v`: 5.6.0

4. Operating system: Osx High Sierra 10.13.2

### Steps to Reproduce

1. Create a test with a `.toMatchSnapshot('some name')`
2. Extension indicates snapshot is missing

### Expected Behavior

* Show snapshot for named snapshots

### Actual Behavior

* Indicates snapshot is missing for named snapshots
![screen shot 2018-02-19 at 3 49 24 pm](https://user-images.githubusercontent.com/5545166/36398385-7c3a5b3a-158c-11e8-8469-79113ccc4c4c.png)

**Comment by seanpoulter** [comment]
At first glance, it seems to me like this will need a PR to change the way the snapshot names are handled in `jest-editor-support` in [this file](https://github.com/facebook/jest/blob/master/packages/jest-editor-support/src/Snapshot.js#L164). Want to take a shot at it? The [Want to Contribute](https://github.com/jest-community/vscode-jest#want-to-contribute) section of the README has everything you need to debug vscode-jest and jest-editor-support at the same time.

**Comment by kanehara** [comment]
Awesome, I'll give it a go.

**Comment by connectdotz** [comment]
vscode-jest [2.9.0](https://github.com/jest-community/vscode-jest/blob/master/CHANGELOG.md#290) has shipped, which should address this issue. Feel free to reopen if otherwise.

**Comment by stmillMSFT** [comment]
I'm using version 2.9.2 on windows and seeing this issue, has there been a regression?
