### ISSUE TITLE
Discussion: What do you think about adding a code coverage integration?

### ISSUE THREAD

**Issue by seanpoulter** [jest-community/vscode-jest#272]
Has anyone from jest-community talked about setting up CodeCov in the other repos @orta? I think it would be useful for folks to see on a PR if they're not already using coverage it in their own development.

**Comment by orta** [comment]
I don't recall anyone talking about it, we can do if you want, I'm an admin on the org

**Comment by seanpoulter** [comment]
I was rebasing my changes after Marcin's PR and realized we dropped [these 2 tests](https://github.com/jest-community/vscode-jest/commit/11fa6864a9218bc3c806407121a684d20b5f8566#diff-4795aa03f0ac9493e09e360c95d97d1fL172). I'd say we go for it since it's low cost - the tooling is free, quick to set up, and if you don't have confidence in the test quality it's not much noise to ignore.

What's your experience with it?

If you're up for it and authorize it, I'll set it up to send coverage reports after a successful build on Travis.

**Comment by orta** [comment]
I personally don't use them, but I'm fine with installing it on the repo

**Comment by seanpoulter** [comment]
Now we'll all have a chance. 👨‍👩‍👧‍👦
