### ISSUE TITLE
Error when trying to debug directly with Code Lens

### ISSUE THREAD

**Issue by lodybo** [jest-community/vscode-jest#277]
### Environment

1. `node -v`: v8.9.1
2. `npm -v`: v5.6.0
3. `npm ls react-scripts` (if you haven’t ejected): 1.0.17

4. Operating system: OSX 10.13.3 High Sierra

### Steps to Reproduce

- Clone reproduction repo: https://github.com/lodybo/vscode-jest-debug-error
- `npm install`

The repo is actually a fresh `create-react-app` app, with the only additions being a function in the `App` component and a failing test. In VS Code with `vscode-jest` being installed, the Code Lens "Debug" will appear above the test.

### Expected Behavior

When clicking on the "Debug" Code Lens in the spec file, I expected that test to be run in Jest and stopping on added breakpoints for debugging.

### Actual Behavior

`vscode-jest` doesn't run the test, and instead at the top of the screen the message "Debugging of tasks is currently only available when directly running jest!" appears.

When Googling for that message, I get a result for the actual line in `JestExt.ts` (line 518) which sets the error. It appears that function is searching for the path to a `jest` executable in my project folder but isn't able to find one (only the `npm test` script). I tried installing both `jest` and `jest-cli` in my project, but no dice. I even added a `jest: jest` script in my `package.json` file but still to no avail.

Am I correct in my assumption of the goal of `resolvePathToJestBin()`? Is it trying to figure out the path to Jest but is `create-react-app` making that impossible? I remember using the "Debug" Code Lens with `create-react-app` a few weeks ago and it worked perfectly then.

**Comment by connectdotz** [comment]
@lodybo this is already in progress... see #271

**Comment by lodybo** [comment]
Ah, apologies. When going through the list of issues this one didn't seem to click with me.
I'll track the progress in there, thanks!
