### ISSUE TITLE
Remove obsolete snapshots

### ISSUE THREAD

**Issue by ryanlittle** [jest-community/vscode-jest#280]
### Environment

1. `node -v`: v8.4.0
2. `npm -v`: 5.3.0
3. `npm ls react-scripts` (if you haven’t ejected): N/A

4. Operating system: macOS High Sierra Version 10.13.3

### Steps to Reproduce

1. Open a test file that contains a snapshot expectation
2. Add a snapshot expectation (this will get generated)
3. Remove snapshot expectation (this will not get removed)

### Expected Behavior

Removal of snapshot expectation would remove obsolete snapshot (or a dialog would appear asking if I'd like to update my snapshots and remove obsolete)

### Actual Behavior

Removal of snapshot expectation does not remove obsolete snapshot (or show a dialog asking if I'd like to update my snapshots and remove obsolete)

--- 

Am I misunderstood? It seems that if I add a new snapshot expectation, I will be prompted to update my snapshots and this will remove any obsolete; however, this is not an ideal workflow.

I started using this extension to replace the need to run my tests in the terminal, but it seems I may need to still do this in the case where I have obsolete snapshots.

**Comment by orta** [comment]
Makes sense, want to try take a look at adding this?

**Comment by ctoppel** [comment]
+1

**Comment by connectdotz** [comment]
This is a really old thread. Since [v5.1](https://github.com/jest-community/vscode-jest/blob/master/release-notes/release-note-v5.x.md#5-enhanced-snapshot-support), you should be able to update snapshots to update and remove obsolete snapshots. 

Close this as this feature is available now.
