### ISSUE TITLE
'Debug' does not filter on 'Describe' block

### ISSUE THREAD

**Issue by TheAlmightyBob** [jest-community/vscode-jest#281]
### Environment

1. `node -v`: 9.4.0
2. `npm -v`: 5.6.0

4. Operating system: macOS Sierra

### Steps to Reproduce

1. Have tests (in the same file, or two files that have the same name but live in different directories) of the style:
```
describe('component 1', () => {
  it('does the thing', () => { ... });
});
describe('component 2', () => {
  it('does the thing', () => { ... });
});
```
2. Have one of the tests fail
3. Click the 'Debug' button

### Expected Behavior

Only the failing test is run with the debugger.

### Actual Behavior

Both tests are run with the debugger, because it is matching 'does the thing' (and filename) and ignoring the `describe` scope.

**Comment by seanpoulter** [comment]
Thanks for reporting the issue. If we split this up into two parts:

- It looks like we don't actually use the file name when filtering the file. That'd be a quick PR if you'd like to have a go at it.

- To differentiate between two tests with the same name in one file -- can Jest do that from the command line? Does it match the `testNamePattern` argument match text in `describe`?

**Comment by TheAlmightyBob** [comment]
1. It's using the file _name_ (at least, I think so?), just not the file _path_. I don't know how common this is with other projects, but we allow test files to have the same name and use the path to differentiate.
2. Yes, `testNamePattern` matches a combined string of "<describe text> <it text>". As long as vscode-jest knows the `describe` context, it should be able to use that.

**Comment by TheAlmightyBob** [comment]
Finally looking more into this, it actually doesn't look like vscode-jest has access to the `describe` context... so that may be a problem... `IParseResults` from `jest-editor-support` only appears to include the `it` text...
