### ISSUE TITLE
Add node_modules/.bin to PATH when run test

### ISSUE THREAD

**Issue by KSXGitHub** [jest-community/vscode-jest#284]
Sometime I want to execute some cli commands.

Sample code:

```javascript
const myPath = process.env.PATH
  .split(path.delimiter)
  .concat(...module.paths.map(x => path.resolve(x, '.bin')))
  .join(path.delimiter)

child_process.spawn(cmd, argv, {
  env: {
    ...process.env,
    PATH: myPath
  }
})
```

It wouldn't have to be that verbose if test runner already add `node_modules/.bin` to `PATH`

**Comment by seanpoulter** [comment]
That's an interesting idea @KSXGitHub. I guess `yarn` and `npm` do that for you but not our runner?

Would you like to try making that change? We'll need to make sure the PATH is passed to the Runner from `jest-editor-support.

**Comment by KSXGitHub** [comment]
> I guess `yarn` and `npm` do that for you but not our runner?

Exactly, my cli tests passed when I run `jest` in terminal but failed in VS Code.

**Comment by connectdotz** [comment]
seems like env related issue, see https://github.com/jest-community/vscode-jest/issues/741#issuecomment-921222851
