### ISSUE TITLE
Unrecognized characters in messages

### ISSUE THREAD

**Issue by chrisbarnes** [jest-community/vscode-jest#286]
The messages produced by this extension contain some characters that are unrecognized on my system. Please see the screenshot below for an example.

### Environment

1. `node -v`: 8.9.4
2. `npm -v`: 5.6.0
3. Operating system: Windows 10

### Behavior

![image](https://user-images.githubusercontent.com/642906/37833133-ebc9df54-2e80-11e8-82d6-aeb6d3538d12.png)

**Comment by orta** [comment]
Same thing as #279 

Did jest's CLI change?

**Comment by seanpoulter** [comment]
I'm going to close this since it's a duplicate.
