### ISSUE TITLE
No bullets next to it/describe blocks 

### ISSUE THREAD

**Issue by fedorinoGore** [jest-community/vscode-jest#289]
### Environment

1. `node -v`: [8.9.0]
2. `npm -v`: [5.7.1]
3. `npm ls react-scripts` (if you haven’t ejected): [not using it, having my own build setup]

4. Operating system: [OS X 10.13.3]
5. VS Code 1.21.1

### Steps to Reproduce
Starting my old React project as usual. Cannot see the bulets next to tests blocks
Started new project, installed Jest and again - no bullets 

### Expected Behavior

Expecting to see red/green bullets next to failed/passed tests

### Actual Behavior

No bullets

**Comment by seanpoulter** [comment]
What version of Jest do you have @fedorinoGore? Is this the same problem as #282?

**Comment by fedorinoGore** [comment]
Im using "jest": "^20.0.4"
And I noticed, that bullets disapear only in tests that are named not after component name, but with some other statement - store.test.js or Store.test.js 
But with tests named after components - `General.test.js` everything works as expected...
So, I believe, that there is some file naming restriction logic in this plugin that Im not aware about...

**Comment by seanpoulter** [comment]
Is this happening in a repo you can share? I'm happy to take a look.

The test results are looked up in this function. They are looked up based on the file path:
  > https://github.com/jest-community/vscode-jest/blob/master/src/TestResults/TestResultProvider.ts#L33

**Comment by seanpoulter** [comment]
Thanks @bmgandre. 👍 That stack trace is pretty helpful like that. For some reason there's a test name that is `undefined`. I'll have to fire up my Windows box tonight and see how many `it(undefined, () => { ... })` tests you have in your repo.

**Comment by Ventajou** [comment]
I get the issue as well, tried the same repo on Windows and Linux and the bullets were only missing on Windows. and I don't have any test named `undefined`.

**Comment by WolfspiritM** [comment]
I had this issue, too.

After digging deep into jest-editor-support and the jest calling code I noticed that it fails cause it trys to run .bin/jest instead of .bin/jest.cmd and that fails.

After adding the line (changing the default from jest to jest.cmd)
```
"jest.pathToJest": "node_modules/.bin/jest.cmd"
```
to the user config it's now working

**Comment by stephtr** [comment]
It took me quite a while to debug. The issue was a combination of two bugs, one of them was related to `pathToJest`. However even without that your repo has the problem, that it uses interpolated strings as test names, which don't get correctly parsed by `jest-test-typescript-parser`.

**Comment by seanpoulter** [comment]
To confirm, you do you mean [template literals](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals)?

**Comment by stephtr** [comment]
Yes, exactly. As soon as they contain a placeholder (`${…}`) it seems like the parser can't evaluate it without running the code, returning undefined.

Therefore ```it(`works`, () => {});``` show the Debug CodeLens while ```it(`doesn't work${'!'}`, () => {});``` doesn't show it.

**Comment by seanpoulter** [comment]
This is a known issue and has been documented in #247 and facebook/jest#4910. We'd love some help with a PR on the `jest-editor-support` side of things when we're parsing the AST. If I recall correctly, the discussion stalled in November while discussing what test cases we'd have to support.

Please continue discussion on either of those two issues.
