### ISSUE TITLE
Run and test the extension locally

### ISSUE THREAD

**Issue by AleksShirokov** [jest-community/vscode-jest#290]
Not an issue, but more of a general question about running and testing the extension locally:

After cloning the repo and going through **Contribute** section, what do I need to do to actually test the extension's functionality locally?

After I press F5, I can only see the output of the tests. Normally, I would expect VS Code to open another window (the [Extension Development Host] window) in which this extension will be loaded. However, nothing really happens after tests are completed. 

![tasks_json_ _vscode-jest](https://user-images.githubusercontent.com/29286719/38038720-ea0f0214-32ab-11e8-92b9-fbdbfb05ef88.png)

Maybe I am missing something here and I would be happy to get some guidance

### Environment

1. `node -v`: v9.8.0
2. `npm -v`: 5.6.0
4. Operating system: osx high sierra

**Comment by orta** [comment]
I wonder if you're running the right scheme in the debugger?

**Comment by AleksShirokov** [comment]
Thank you for getting back to me!

Just to clarify: what do you mean by "the right scheme"? Which scheme are we talking about?

**Comment by seanpoulter** [comment]
I think what @orta means by "the right scheme" is the right debugging "[launch configuration](https://code.visualstudio.com/docs/editor/debugging#_launch-configurations)".

There are two debugging configurations defined in [`.vscode/launch.json`](https://github.com/jest-community/vscode-jest/blob/master/.vscode/launch.json):
  - Debug Tests
  - Launch Extension

I've found when you press <kbd>F5</kbd> VS Code will start the first debug configuration and run the tests. You'll need to [change the launch configuration](https://code.visualstudio.com/docs/editor/debugging#_launch-configurations) to **Launch Extension** and start debugging to open the "Extension Development Host" window you're expecting.

**Comment by AleksShirokov** [comment]
Thank you both very much! This was extremely helpful!
