### ISSUE TITLE
How to get just the problem matcher?

### ISSUE THREAD

**Issue by bendtherules** [jest-community/vscode-jest#295]
Is there an already included problemMatcher that can be used within tasks.json?

I would like to use just that if possible, without the rest of the features that the package provides. Can it be made available as a separate vscode extension, maybe?

**Comment by orta** [comment]
I’m not sure I understand your question here

**Comment by bendtherules** [comment]
Vscode has this concept of problem matchers https://code.visualstudio.com/docs/editor/tasks#_defining-a-problem-matcher, which can work on running task's console output to add a problem to the native problem windows (usually first tab in bottom section of vs code where console sits).

I am not sure if this extension is internally using the same thing to show errors in the file. Is it using problem matcher internally? 

If not, does it fall within the scope of this project? This will definitely be useful for those who already have a test script defined in package.json

**Comment by orta** [comment]
Ah, OK, no it's not, we have Jest output JSON and then parse that to get full details via the jest-editor-support module (which is re-used in other tools) - I can imagine to get everything from the text output we'd need there'd be a pretty significant regex 🍡

**Comment by bendtherules** [comment]
Thanks, understood. Closing the issue.

**Comment by stephtr** [comment]
> This will definitely be useful for those who already have a test script defined in package.json

I'm not quite sure what your use case would be, but when having a test script defined, which somehow runs Jest, it should be enough to set `jest.pathToJest` to `npm test --` (provided your script forwards additional arguments to jest instead of swallowing them).
