### ISSUE TITLE
Typescript from Windows Network Share 

### ISSUE THREAD

**Issue by jhr007** [jest-community/vscode-jest#304]
I'm posting this here to get the ball rolling... its most likely a problem in an upstream `jest` module. 

The problem starts when `vs code` opens code from a windows network share. 

Closely related to upstream's https://github.com/facebook/jest/issues/5563

from the above issue: 
> **[he]** tried to debug the issue and find the core of the problem, and it seems 
>the following is happening:
> 
> the network-drive is mounted as a disk-drive in windows, so the directory with the tests is available at (for example) G:\src\ . 
> but the real name of that place is \\server1\src . when i go to G:\src\, and start jest, it looks up the 
> full-name of the current-directory, and somehow it gets the network-ish name (\\server\src). and 
> it gets confused by the double-backslash at the beginning. but if i run it as jest --rootDir ., 
> i assume it stays with the G:\src\ name, and then everything is ok.

### Environment

1. `node -v`: **v8.10.0**
2. `npm -v`: **5.7.1**

4. Operating system: 
**Windows 7 & windows 10**

### Steps to Reproduce

Copy your TypeScript project to a Windows mapped drive... one pc uses a samba mapped drive, one uses a windows server mapped drive. same results

__
This is my first typescript and first jest project. I followed the online getting started guides to get it working on Windows 10. I assume any project dependent on the config transform `ts-jest` will cause same error. My config is in package.json like the getting started guides. 

I had it working as normal on a Windows 10 PC, code on same hdd. The tests were passing/failing while coding. 

Later I switched to a Windows 7 PC but the code was on a shared samba drive and got the error below. 

I went back to original windows 10 PC, copied code to a **network share** and got the error. 
Same Windows 10 PC, copied code to a 2nd hdd and the **extension worked.** 

### Expected Behavior
Passing/Failing tests during coding. 

### Actual Behavior
I get this error in `vscode`'s jest output window:
```
--Snipped this repeated Validation Error--
● Validation Error:

  Module ts-jest in the transform option was not found.

  Configuration Documentation:
  https://facebook.github.io/jest/docs/configuration.html

Starting Jest in Watch mode failed too many times and has been stopped. Please check your system configuration.
```

**Comment by orta** [comment]
This is very likely not a vscode-jest issue, it's just running your jest/test command

**Comment by jhr007** [comment]
I think I found the problem in jest.
https://github.com/facebook/jest/issues/6051
