### ISSUE TITLE
Not working with typescript files

### ISSUE THREAD

**Issue by yarkovaleksei** [jest-community/vscode-jest#306]
### Environment

1. `node -v`: v9.8.0
2. `npm -v`: 5.8.0
3. Operating system: Ubuntu 14.04

### Steps to Reproduce

1. Install extension to VSCode and restart
2. Open `module.spec.ts`
3. Do not work Jest autostart

**Comment by yarkovaleksei** [comment]
@seanpoulter Oh sure. Jest is used to perform tests from the command line.

**Comment by seanpoulter** [comment]
If Jest is installed globally it will not trigger the extension to start. Any chance that's the problem?

As you'll see in the list below that is taken from the [`activationEvents`](https://github.com/jest-community/vscode-jest/blob/b4fb57e9a50217584426244702ea732d29c539ae/package.json#L23) in package.json, Jest will start when:
* the workspace contains any of:
  - `jest.config.js`
  - `jest.json`
  - `node_modules/.bin/jest`
  - `node_modules/react-scripts/node_modules/.bin/jest`
  - `node_modules/react-native-scripts`
* the user runs the **Jest: Start Runner** command

Does that help?

**Comment by yarkovaleksei** [comment]
My file is here: `test/unit/jest.config.js`.
Could this be a problem?

**Comment by seanpoulter** [comment]
That's the problem. We're only checking at the root level because Jest only checks at the root level unless you provide it a CLI option.
