### ISSUE TITLE
"The system cannot find the path specified." What path?

### ISSUE THREAD

**Issue by bobwalker99** [jest-community/vscode-jest#311]
### Environment

1. `node -v`: v9.11.1
2. `npm -v`: 5.6.0
3. `npm ls react-scripts` (if you haven’t ejected): [fill]

4. Operating system: Windows 10 x64

### Steps to Reproduce
```

Jest runner regularly fails with the following output:
The system cannot find the path specified.

Finished running all tests. Starting watch mode.
The system cannot find the path specified.

The system cannot find the path specified.

The system cannot find the path specified.

The system cannot find the path specified.

The system cannot find the path specified.

Starting Jest in Watch mode failed too many times and has been stopped. Please check your system configuration.
```

### Expected Behavior

Either 
a) it doesn't fail in the first place or
b) it gives me a little more information about what's gone wrong (the path of the file it can't find would help, and what it's trying to do when it's looking for it? 

### Actual Behavior
See above. Most of the time it works fine, and I'm not knowingly changing configuration prior to it happening. I can't find anything in VS Code logs that explains any further or gives me other insight.

--- 

Note we are looking for someone to take responsibility around keeping create-react-app up to date and working, could this be you?

**Comment by seanpoulter** [comment]
I'm happy to help troubleshoot your problem but your steps to reproduce the problem are incomplete. Can you please provide the required steps to set up your workspace the same way you have. An example repo with a minimal set of code to reproduce the problem will help.

**Comment by bobwalker99** [comment]
Hi Sean - thanks for responding so quickly, sorry for the lack of detail - I do appreciate the attention :-)

I've just tried to create a reproducible case and I think I've found the problem.

It seems to be setting "jest.pathToJest" that demonstrates this behaviour. If you add a workspace setting pointing to a path that doesn't exist, you will see the same - try 
`"jest.pathToJest": "_node_modules/.bin/jest"` (note the leading underscore)

Other invalid, non-path values do echo - e.g. `"jest.pathToJest": "invalid"` brings:
```
'invalid' is not recognized as an internal or external command,
operable program or batch file.
```
I'm assuming this is the windows command shell being unhelpful, but maybe we could trap it earlier and report? I've just checked out the code, I'm happy to have a go at enhancing it, and submit a PR if you can push me in the right direction? I was looking at `pathToJest` in `vscode-jest\src\extension.ts` - is this the right place? 

Regards
Bob

**Comment by seanpoulter** [comment]
Ugh, that is a pretty terrible user experience.

Yes, you've found it. `pathToJest` is where you can start debugging.

What's your plan of attack to catch it early? Does that plan change if you know that `pathToJest` can include command line options or executables on the `PATH`?

**Comment by connectdotz** [comment]
this is a staled old issue, it should be resolved by the action button in the error notification that points to the setup tool. Close.
