### ISSUE TITLE
"Jest: Start Runner" only works when a file is open

### ISSUE THREAD

**Issue by garyking** [jest-community/vscode-jest#318]
I have `jest.autoEnable` set to `false`. When I open a workspace with Jest installed, and I run `Jest: Start Runner`, nothing happens. If I open a file then run it, then it works fine.

So, it doesn't seem to run if there is no file open. It doesn't matter if the file that's open is a test file or not, either.

**Comment by seanpoulter** [comment]
Thanks for reporting the issue @garyking. It turns out this is a quick fix from fix by changing a few calls from `registerTextEditorCommand` to `registerCommand`.

> Text editor commands are different from ordinary commands as they only execute when there is an active editor when the command is called. Also, the command handler of an editor command has access to the active editor and to an edit-builder.
