### ISSUE TITLE
Show failed test output if test has been failing since before last commit

### ISSUE THREAD

**Issue by sarahscott** [jest-community/vscode-jest#32]
This test is a legit fail:

![screen shot 2016-12-02 at 12 42 55 pm](https://cloud.githubusercontent.com/assets/2712962/20844235/e5dca376-b88c-11e6-87b7-c37dc2ea6e01.png)

But since it was in the last commit as a failed test, the jest output doesn't tell you about it. It does know that the fail exists because the dot is red, though, and if you run testing from terminal, you'll see the failure report.

**Comment by orta** [comment]
I'm afraid that's not how Jest's watcher works, without running an entire test run the extension just can't know whether all tests have passed or failed

**Comment by sarahscott** [comment]
Right, but after it runs the suite at least once, shouldn't it update the copy here in the console to reflect the failure?

**Comment by orta** [comment]
Yeah - good point, I guess we'll need to ensure all state is cleaned between builds

or @cpojer - does the jest cache contain the results of all tests runs, e.g. could I use some of Jest's code inside jest-support to look up whether that test has failed / passed in a previous run?

**Comment by cpojer** [comment]
Currently we only cache the failed test suite not the individual tests in a file. We do this so we know which test suites to run first on the next run (failed ones, then slowest to fastest).

**Comment by connectdotz** [comment]
Much has changed and this issue doesn’t seem to be applicable any more, closing...
