### ISSUE TITLE
Use new test action bar panel to show test results and overview of all tests.

### ISSUE THREAD

**Issue by nklayman** [jest-community/vscode-jest#321]
In the April update, a test panel on the action bar was added to show unit test fail/pass results. [https://code.visualstudio.com/updates/v1_23#_extension-authoring](https://code.visualstudio.com/updates/v1_23#_extension-authoring). This should be used to display test results and for easy navigation to different tests.

**Comment by seanpoulter** [comment]
Can someone please have a look if we'll need to change the test parsing to pick up the `describe` blocks?

**Comment by connectdotz** [comment]
resolved by TestExplorer
