### ISSUE TITLE
No way to use jest installed within Windows Subsystem for Linux

### ISSUE THREAD

**Issue by therazor** [jest-community/vscode-jest#331]
### Environment

1. `node -v`: no version installed
2. `npm -v`: no version installed
3. `npm ls react-scripts` (if you haven’t ejected): N/A

4. Operating system: Windows 10 + WSL

### Steps to Reproduce

Use Windows 10 + Windows subsystem for linux. Install node/npm/jest within the subsystem only, not in windows.

### Expected Behavior

There should be a way to use the version of jest installed within WSL rather than duplicating the installation of all the tools required, once within linux and once in windows

### Actual Behavior

```
'jest' is not recognized as an internal or external command, operable program or batch file.
```
(Quite rightly, as there's absolutely no node/jest/npm installed outside WSL)

--- 

I've tried to look through docs and other open bugs but cannot find anything similar, apologies if I've missed it!
Note that I'm not sure if there are any guidelines for extension authors around using WSL, but it's e.g. possible to [debug files using node installed within WSL](https://code.visualstudio.com/updates/v1_17#_node-debugging), so assuming it's doable for extensions as well.

**Comment by stephtr** [comment]
Is your whole project residing within WSL or did you just run npm install within WSL?

**Comment by stephtr** [comment]
That answers my question. You could set `"jest.pathToJest": "node node_modules/jest/bin/jest.js"`, which should work with your setup.

**Comment by therazor** [comment]
That doesn't work, and I would've been surprised if it did, because the command still runs within the windows context, which does not have `node`. Only WSL has it installed.  
This is the error that I'm getting, which is interesting:

```
'npm' is not recognized as an internal or external command,
operable program or batch file.
```

Note how it refers to `npm`. Where does that come from?  
That made me try calling something that doesn't exist, e.g. `"jest.pathToJest": "foobar"`.

Same error, referring to `npm`. In fact, absolutely everything I try as a value for `"jest.pathToJest"` results in the same error, which makes me think it might not be working correctly in windows?

I _believe_ I've found the correct command that should be used by the extension: [`wsl`](https://docs.microsoft.com/en-us/windows/wsl/interop#run-linux-tools-from-a-windows-command-line) `jest`. It does not seem to be executed when I change that property, however.  
Thoughts?

**Comment by seanpoulter** [comment]
If you want to get yours hands dirty it's simple to debug the extension and see if `wsl jest` will work. From [CONTRIBUTING.md](https://github.com/jest-community/vscode-jest/blob/293f97712e8a4548533d15d962cb3580e456998f/CONTRIBUTING.md):

```
git clone https://github.com/jest-community/vscode-jest
cd vscode-jest
yarn install
code .
```
When you get vscode-jest open in VS Code, run the **Debug: Select and Start Debugging** command and start the **Launch Extension** configuration. That'll open up a new workspace where you can load your own project. Jump back into the extension and set set a breakpoint at [`this.runner.start(...)`](https://github.com/jest-community/vscode-jest/blob/293f97712e8a4548533d15d962cb3580e456998f/src/JestProcessManagement/JestProcess.ts#L26) and step in to the point where it's going to `spawn` the command and change the values to try your hand at the `wsl` prefix.
<br/>

Alternatively, I'd suggest creating a minimal JS file from Windows that spawns a process that can access the WSL. They're likely going to be the same amount of work.

**Comment by stephtr** [comment]
Since the whole node_modules folder is already present, what speaks against installing just Node? I think that would be the only tool needed.

**Comment by connectdotz** [comment]
vscode-jest [2.9.0](https://github.com/jest-community/vscode-jest/blob/master/CHANGELOG.md#290) has shipped, which could help addressing this issue. Please give it a try and let us know if it works for you.

**Comment by therazor** [comment]
![image](https://user-images.githubusercontent.com/848778/43286427-e84dab8e-9119-11e8-8e2c-dcfeebd9a3ac.png)

@connectdotz please see the screenshots above - it still doesn't work, with the same error.

What I find bizarre is that the following user setting _should_ work, as I explained with a little more info [above](#issuecomment-391117563)

```json
{
    "jest.pathToJest": "wsl jest"
}
```

But instead, it says

```
'wsl' is not recognized as an internal or external command,
operable program or batch file.
```

The same `wsl jest` used with cmd.exe within the integrated vs code terminal works

![image](https://user-images.githubusercontent.com/848778/43286727-ddf844d6-911a-11e8-9774-6e694efceec7.png)

Which means that whatever context this extension is running with, it's missing something, possibly the correct PATH

**Comment by seanpoulter** [comment]
If you follow the README docs to setup this report and the Jest repo, you'll be able to debug the process launch and see how we're calling `child_process.spawn`. The give some clues..

**Comment by viebel** [comment]
any update on this issue?

**Comment by mojadev** [comment]
I set up the extension for development/debugging and will see if I find a fix or workaround tomorrow

**Comment by viebel** [comment]
Thanks @mojadev

**Comment by mojadev** [comment]
See https://github.com/jest-community/vscode-jest/pull/361 - although I would also be ok with this PR to be rejected and updating jest-editor-support where necessary. Opinions/Suggestions on how to improve path detection and mapping are welcome.

With that state I was able to get it running locally:
![grafik](https://user-images.githubusercontent.com/412767/44160473-cd170800-a0ba-11e8-9409-b3237bed452c.png)

![grafik](https://user-images.githubusercontent.com/412767/44160508-e91aa980-a0ba-11e8-9310-a6339c486581.png)

**Comment by unparagoned** [comment]
@viebel &  @mojadev please can you help me with this problem.

I've read the thread twice and it's like the solution is hidden. I had a look at the PR but that sort of stuff seems to be beyond my level. I've got jest running in the console but not properly integrated into vscode. 

```
bash
npm test
command prompt
node node_modules\jest\bin\jest.js
```
The following runs in the debug console but it does throw up an error. 

```
        {
            "type": "node",
            "request": "launch",
            "name": "Launch via NPM",
            "runtimeExecutable": "node",
            "runtimeArgs": [
                "${workspaceFolder}\\node_modules\\jest\\bin\\jest.js",
            ],
            "cwd": "${workspaceFolder}",
            "port": 9229
        },
```
I also had a linked at the PR but that didn't help me much. Please could someone explain to me how to get the jest integrated with vscode properly.

**Comment by kevinmarrec** [comment]
@mojadev Any update on this issue ? I'm looking forward having this extension working with WSL 😄

**Comment by stephtr** [comment]
Yes, support is currently in work (at them moment in [facebook/jest](https://github.com/facebook/jest/pull/6941)).

**Comment by kevinmarrec** [comment]
@stephtr Thanks, gonna wait for this PR merge then :)

**Comment by bogdan-calapod** [comment]
Any updates on this ? It seems that jest has added support [in this issue](https://github.com/facebook/jest/pull/6941) (If I'm not mistaken, this is the PR that was talked about in previous comments)

**Comment by bogdan-calapod** [comment]
Sure, I'll check it out tomorrow

**Comment by bogdan-calapod** [comment]
Sure, I'll check it out tomorrow

**Comment by seanpoulter** [comment]
I overlooked that we'll need a change to jest-community/jest-editor-support as well. Check for a PR there first. https://github.com/jest-community/jest-editor-support/pulls

**Comment by mojadev** [comment]
@seanpoulter : Did you find time to look over the issues in the PR?

**Comment by seanpoulter** [comment]
No, sorry. I got as far as confirming the tests are failing in the jest-editor-support repo.

**Comment by offero** [comment]
I receive the following error when trying to run it in WSL
```
Error: ENOENT: no such file or directory, open '/mnt/c/Users/cjk/Development/projects/myapp/C:/Users/cjk/AppData/Local/Temp/jest_runner.json'
```

It looks like it's trying to run tests with the node/jest in WSL, but some path stuff is getting messed up.

Workspace Settings:
```
		"jest.pathToJest": "node node_modules/jest/bin/jest.js",
```

User settings:
```
    "terminal.external.windowsExec": "C:\\WINDOWS\\System32\\bash.exe",
    "terminal.integrated.shell.windows": "C:\\WINDOWS\\System32\\bash.exe",
```

**Comment by pluma** [comment]
I was able to trick jest into working by telling vscode-jest to run the following script:
```js
"use strict";
const cp = require("child_process");
const args = [];
for (const arg of process.argv.slice(2)) {
  if (arg.startsWith("C:\\")) {
    args.push(`/mnt/c/${arg.slice(3).replace(/\\/g, "/")}`);
  } else args.push(arg);
}
cp.spawnSync("wsl", ["node", "node_modules/.bin/jest", ...args], {
  cwd: process.cwd(),
  stdio: "inherit"
});
```

However vscode-jest doesn't seem to apply the failures -- most likely because it doesn't understand the file paths in the test results JSON (which use WSL `/mnt/c´ paths rather than Windows `C:\` paths).

I think I can adjust the script to intercept the JSON file though.

Telling vscode-jest to use wsl directly didn't work because it used Windows paths. The output indicated the backslashes are being swallowed at some point but either way jest wouldn't know what to do with the `outputFile` Windows path.

**Comment by mojadev** [comment]
I already created a fix for this half a year ago that got stuck after reworks in the base repo and breaking tests (that weren't really affected by the changes)- see https://github.com/mojadev/jest-editor-support/tree/WSL_Support . Technically it's easy, but getting it into the master seems to be the actual issue :) 

I'll try to pull the current master of the editor support once and see if the base repo is more stable now.

**Comment by jsonMartin** [comment]
Any updates on this? I'm having the same issue. Thanks! 🙏

**Comment by mojadev** [comment]
@connectdotz just informed me that the jest-editor-support changes are about to be finished, afterwards I'll check my PR again for conflicts and we should be able to close this issue.

**Comment by mikelyons** [comment]
Any updates on this? I'm having the same issue. Thanks! 🙏

**Comment by bogdan-calapod** [comment]
I've been using the Remote WSL extension and it's been working fine with that.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by pluma** [comment]
Note that the extension currently only works with the Insiders version. But now that VS Code is getting native support for WSL via the Remote WSL extension I think this ticket can be closed.

**Comment by mojadev** [comment]
I agree. I could update my fix now that the 3.0.0. release is out but given that the Remote WSL extension is out (soon) I think using that one is the better solution.

I used my wsl-support branch for development in WSL until now and will also switch to the remote extension, as this is the better solution imho.

**Comment by stephtr** [comment]
Even Microsoft is now [deprecating the use of `useWSL`](https://code.visualstudio.com/updates/v1_36#_nodejs-debug-configuration-attribute-usewsl-is-deprecated) for Node.js debug configurations in favor of the Remote-WSL extension.
I'll therefore finally mark this issue as solved. For further details on how to use VS Code on WSL, see [their documentation](https://code.visualstudio.com/docs/remote/wsl).

Finally thank you all, especially @mojadev, for the effort put into trying to solve this issue!

**Comment by airtonix** [comment]
> That answers my question. You could set `"jest.pathToJest": "node node_modules/jest/bin/jest.js"` in VS Code's settings, which should work with your setup (since `jest.cmd` basically just runs that command).

```
[Window Title]
Visual Studio Code

[Main Instruction]
Visual Studio Code

[Content]

Version: 1.46.0 (system setup)
Commit: a5d1cc28bb5da32ec67e86cc50f84c67cc690321
Date: 2020-06-10T09:03:20.462Z (5 days ago)
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

[OK] [Copy]
```

Thanks @stephtr this Works.

Since we are mostly developing and deploying Docker, this also exposed some assumptions we've made about handling dates too.
