### ISSUE TITLE
Coverage Overlay not visible in project with ts-jest

### ISSUE THREAD

**Issue by mjwwit** [jest-community/vscode-jest#333]
### Environment

1. `node -v`: 8.11.1
2. `npm -v`: 5.8.0
3. `npm ls react-scripts` (if you haven’t ejected): n/a
4. Operating system: macOS High Sierra (10.13.3)

### Steps to Reproduce

1. Clone demo [repository](https://github.com/mjwwit/vscode-jest-typescript-coverage)
2. Run `npm install`
3. Open project in Visual Studio Code with vscode-jest installed

### Expected Behavior

Either the coverage is displayed immediately (as the configuration `showCoverageOnLoad` suggests), or after running the `Jest: Toggle Coverage Overlay`.

### Actual Behavior

The Code Coverage Overlay is not visible, and no order of starting/stopping or toggling coverage overlay will change that.

**Comment by stephtr** [comment]
Did you add the flag to collect coverage information somewhere, what's your current `jest.pathToJest` setting? Setting it to `npm test -- --coverage` should probably do the job.

**Comment by mjwwit** [comment]
I tried setting `jest.pathToJest` to your suggested value and `node_modules/.bin/jest --coverage`, but neither resulted in the displaying of a Coverage Overlay.

**Comment by stephtr** [comment]
Oh sorry, I didn't notice that you are using a jest.config.js. In that case revert the `pathToJest` setting and just add `collectCoverage: true` to your jest.config.js. Additionally you could also add `coverageReporters: []` if you don't want to automatically generate an xml, json and html report.

**Comment by mjwwit** [comment]
https://github.com/mjwwit/vscode-jest-typescript-coverage/pull/1#issuecomment-393423108
> This still doesn't work for me... At some point I did get a small header above the file content showing coverage stats, but no overlay is being shown.
