### ISSUE TITLE
Jest version detection fails for global Jest installs

### ISSUE THREAD

**Issue by stephtr** [jest-community/vscode-jest#335]
### Environment

1. `node -v`: v10.1.0
2. `npm -v`: 5.6.0

4. Operating system: Windows x64

### Steps to Reproduce

Install Jest globally and set `jest.pathToJest` to `"jest"`

### Expected Behavior

[`getJestVersion`](https://github.com/jest-community/vscode-jest/blob/293f97712e8a4548533d15d962cb3580e456998f/src/JestExt.ts#L452) should report the correct version of Jest.

### Actual Behavior

[`pathToJestPackageJSON`](https://github.com/jest-community/vscode-jest/blob/293f97712e8a4548533d15d962cb3580e456998f/src/helpers.ts#L98) doesn't care about globally installed packages
The error message 'This extension relies on Jest 20+ features, it will continue to work, but some features may not work correctly.' is being shown, even though the setup works fine.

**Comment by jeff-kilbride** [comment]
This also happens on `create-react-app` installs. See:

https://github.com/jest-community/vscode-jest/issues/313#issuecomment-395622978

**Comment by stephtr** [comment]
That's not related to this bug but a regression introduced by #324 and will get fixed by #332.

**Comment by connectdotz** [comment]
we should not need to resolve jest version via `pathToJestPackageJSON`, see #341, welcome to discuss there.

**Comment by connectdotz** [comment]
with 2.9.0, this should not be an issue anymore... please confirm
