### ISSUE TITLE
"Test has not run yet, due to Jest only running tests related to changes."

### ISSUE THREAD

**Issue by ericbiewener** [jest-community/vscode-jest#336]
### Environment

1. `node -v`: 8.8.1
2. `npm -v`: 5.4.2
3. `npm ls react-scripts` (if you haven’t ejected): N/A

4. Operating system: Mac 10.13.4

### Steps to Reproduce
Test repo: https://github.com/ericbiewener/vscode-jest-debug/tree/master
I haven't added any custom config to the vscode-jest plugin.

### Expected Behavior
Tests run

### Actual Behavior
I get an empty green circle next to my test. Hovering over it states: "Test has not run yet, due to Jest only running tests related to changes." I have tried making changes both in the test file and in the file it imports from, but nothing happens. Running jest from the command line works fine.

--- 

Note we are looking for someone to take responsibility around keeping create-react-app up to date and working, could this be you?

**Comment by connectdotz** [comment]
are you able to run jest test manually, i.e. run `npm test` or `yarn test` via commandline ? 

I cloned your repo and the test script gave the following error:
```
$yarn test
yarn run v1.6.0
warning package.json: No license field
$ jest
 FAIL  __tests__/index.test.js
  ● Test suite failed to run

    Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://facebook.github.io/jest/docs/en/configuration.html

    Details:

    /Users/vsun/Downloads/vscode-jest-debug-master/__tests__/index.test.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import foo from '../app';
                                                                                             ^^^^^^

    SyntaxError: Unexpected token import

      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/script_transformer.js:402:17)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        2.686s
Ran all test suites.
error Command failed with exit code 1.
```

**Comment by ericbiewener** [comment]
Man, I'm not sure what I was doing. Once I fix it so that the tests actually run with `yarn test` then your extension works fine. Sorry for wasting your time!
