### ISSUE TITLE
create-react-app-typescript displays:'extension relies on Jest 20+ features'

### ISSUE THREAD

**Issue by cmenekse** [jest-community/vscode-jest#337]
### Environment

1. `node -v`: **8.11.1**
2. `npm -v`: **5.6.0**
3. `npm ls react-scripts` (if you haven’t ejected): 
it is from create-react-app-typescript so 
**react-scripts-ts@2.16.0**

4. Operating system:  **Windows 10**

### Steps to Reproduce
run 
`create-react-app my-app --scripts-version=react-scripts-ts`
add in vscode settings: 
```
  "jest.pathToJest": "npm run test --",
  "jest.debugCodeLens.showWhenTestStateIn": [
    "fail",
    "pass",
    "skip",
    "unknown"
  ],
  "jest.enableCodeLens": true,
```
then CTRL+SHIFT+P, Jest:Start Runner.

I do not see `jest ` installed globally when doing `npm ls -g --depth 0 `

### Expected Behavior
No Jest 20+ error and dots to appear near tests

### Actual Behavior
Displays : `This extension relies on Jest 20+ features, it will continue to work, but some features may not work correctly`
and no dots are appearing, everything else seems to be fine.

**Comment by connectdotz** [comment]
this indeed is a bug, #341 should fix it once released.

**Comment by connectdotz** [comment]
vscode-jest [2.9.0](https://github.com/jest-community/vscode-jest/blob/master/CHANGELOG.md#290) has shipped with [jest 23.x support and more](#341), which should address this issue. Feel free to reopen if otherwise.
