### ISSUE TITLE
jest extension says tests fail when they are actually passing

### ISSUE THREAD

**Issue by Almenon** [jest-community/vscode-jest#346]
### Environment

1. `node -v`: 9.4.0
2. `npm -v`: 6.0.0

4. Operating system: Windows 10

Jest extension version: 2.8.0
VSCode version: 1.25.0

### Steps to Reproduce

https://github.com/Almenon/AREPL-react/tree/0866685bbe8c69d4b413df16db8eb202f55436de

Check out the unitTests branch (specifically, commit 0866685 if that matters) and the jest extension will recognize the unit tests and try to run them.

### Expected Behavior

All tests pass, as they do from command line when running npm test

### Actual Behavior

Some tests fail

**Comment by connectdotz** [comment]
vscode-jest [2.9.0](https://github.com/jest-community/vscode-jest/blob/master/CHANGELOG.md#290) has shipped with [jest 23.x support and more](#341), which could help this issue. please give it a try and let us know if it works for you.

**Comment by Almenon** [comment]
I'm not working with jest currently and I don't have time to test it, sorry.  I'll just close the issue.
