### ISSUE TITLE
VSCode stuck at installing vscode-jest.

### ISSUE THREAD

**Issue by mpcmarques** [jest-community/vscode-jest#353]
### Environment

1. `node -v`: 10.7.0
1. `npm -v`: 6.2.0
1. `npm ls jest` or `npm ls react-scripts` (if you haven’t ejected): react-scripts@1.1.4

1. Operating system: OSX High Sierra

### Prerequisite
- are you able to run jest test from command line? 
Yes.
- how do yo run your tests from command line? (for example: `npm run test` or `node_modules/.bin/jest`) 
yarn test

### Steps to Reproduce

Try to install vscode-jest extension in vscode using OSX High Sierra. All other extensions works without error.

### Expected Behavior

Install extension.

### Actual Behavior

VSCode shows that it is installing but it never finishes.

![Image](https://preview.ibb.co/dwGm4T/Captura_de_ecr_2018_07_26_s_15_09_55.png)

--- 

The fastest (and the most fun) way to resolve the issue is to submit a pull-request yourself. If you are interested, feel free to check out the [contribution guide](https://github.com/jest-community/vscode-jest/CONTRIBUTING.md), we look forward to seeing your PR...

**Comment by connectdotz** [comment]
I can't reproduce this on my mac... what vscode version you are running? does the problem persist after you restart vscode?

**Comment by mpcmarques** [comment]
Yes, it persisted after restart. I managed to make it work installing via command line with 
`code --verbose --install-extension orta.vscode-jest`

I'm closing the issue 😄
