### ISSUE TITLE
Test status indicator issue

### ISSUE THREAD

**Issue by yantakus** [jest-community/vscode-jest#36]
When there's a failing test, the indicator turns red:

![test js - first-agenda 2016-12-05 11-41-18](https://cloud.githubusercontent.com/assets/2179726/20878408/ce8262c4-badf-11e6-93a1-596d24f69343.png)

When I fix it, the comment disappears, but the indicator is still red:

![test js - first-agenda 2016-12-05 11-41-38](https://cloud.githubusercontent.com/assets/2179726/20878413/d1f66162-badf-11e6-8dd2-932422fdfde6.png)

**Comment by orta** [comment]
oh yeah, that's weird, I've not seen this before - can you clone the repo and have a look with the debugger at the status of that it? Is there two wit the same name by any chance?

**Comment by bookman25** [comment]
When you fix it, are the files you're modifying back to an unchanged state in git (unstaged/uncommited)?

I've seen one case if you fix and either commit, or the fix goes back to unchanged state.  Jest is only acting on unstaged/uncommited files and as a result the editor doesn't *currently* update the decorators for files it thinks have no changes.

**Comment by bookman25** [comment]
We made some improvements here, if you're still seeing the issue feel free to reopen.

**Comment by thedgbrt** [comment]
Still seeing this with latest version

**Comment by bookman25** [comment]
I've also seen variations of this as well.  I'm going to try to find some time to track down the specific repro and hopefully fix.

**Comment by englandschorsch** [comment]
Same problem here with vscode 1.16.1 and Jest extension 2.4.2 under Linux:

![status_indicator_not_updating](https://user-images.githubusercontent.com/24250824/31453662-3b056d8e-aeb3-11e7-8319-e7cb3398ad76.png)

**Comment by daldridge-cs** [comment]
I've seen this occur in the following scenario:
- Start with a test that is passing
- Edit the test and save, causing the watcher to detect the change and run the test.  Test is correctly shown as failing.
- Undo the edits to the failing test, reverting the file back to what it was (no difference in git working tree).  Because the file matches SCM, the watcher doesn't re-run the test, so it fails to go back to green.

**Comment by jfcere** [comment]
@daldridge-cs I noticed the same thing and it has been reported here: #308
