### ISSUE TITLE
Jest coverage info appears for a second then disappears

### ISSUE THREAD

**Issue by garyking** [jest-community/vscode-jest#371]
### Environment

1. `node -v`: v8.11.2
1. `npm -v`: 6.4.0
1. `npm ls jest` or `npm ls react-scripts` (if you haven’t ejected): jest@23.5.0
1. your vscode-jest settings if customized:

```
  "jest.enableCodeLens": false,
  "jest.pathToJest": "node_modules/.bin/jest",
```

`jest.config.js`

```
module.exports = {
  collectCoverage: true,
};
```

1. Operating system: Mac 10.13.5 (17F77)

### Prerequisite
- are you able to run jest test from command line? Yes
- how do yo run your tests from command line? (for example: `npm run test` or `node_modules/.bin/jest`) `npx jest`

### Steps to Reproduce

Open a project with Jest and the settings mentioned above. Open a file that has a test, and coverage info for it.

The GIF illustrates that when I open a project and then a file with coverage, the info appears at the top, then disappears. Why? After it disappears, I can't toggle the coverage overlay.

![jest disappears](https://user-images.githubusercontent.com/343940/44684344-dd15dc80-aa16-11e8-8108-ece96df047b4.gif)

**Comment by Sytten** [comment]
Same here :(

**Comment by garyking** [comment]
Issue fixed [per this comment of mine](https://github.com/jest-community/vscode-jest/issues/370#issuecomment-554595209).
