### ISSUE TITLE
New release soon?

### ISSUE THREAD

**Issue by randycoulman** [jest-community/vscode-jest#377]
I've experienced the problem described in #368 and #276.  It appears to be fixed by #356 which has been merged but not released.  I checked out a local copy of master to verify, and it certainly fixes the problem for me.

Would it be possible to get a new release of this extension that includes this fix?

Is there anything I can do to help make that happen?

Thanks!

**Comment by orta** [comment]
Yep - makes sense shipped!

**Comment by randycoulman** [comment]
@orta Thanks!  I'm not seeing it in the marketplace yet, though.  Is there usually some kind of delay before that happens?

**Comment by smrpr** [comment]
I can't see it either. cc @orta

**Comment by orta** [comment]
Alright.- yeah, looks like my vscode push access token hit it's annual expiration - just shipped it, thanks for the reminders
