### ISSUE TITLE
Backticks makes gui hang.

### ISSUE THREAD

**Issue by H-a-w-k** [jest-community/vscode-jest#384]
it(`checking jest`, () => {
});

Tests work, but vscode green/red circle does not. Hangs on empty circle waiting for changes.

**Comment by connectdotz** [comment]
this is a known issue, the current test parser doesn't handle templateLiteral (backtick) yet, I am working on a parser PR that will include this fix.

**Comment by connectdotz** [comment]
duplicate of #247
