### ISSUE TITLE
jest runner doesn't runInBand as per defined in package.json

### ISSUE THREAD

**Issue by fillon** [jest-community/vscode-jest#389]
### Environment

1. `node -v`: 8.11.4
1. `npm -v`: 5.6.0
1. `npm ls jest` or `npm ls react-scripts` (if you haven’t ejected): jest@23.6.0
1. your vscode-jest settings if customized:
    - jest.pathToJest? empty
    - jest.pathToConfig? empty
    - anything else that you think might be relevant? [fill]

//jest.config.js
```
module.exports = {
    moduleNameMapper: {
        '@/(.*)$': '<rootDir>/src/$1',
        'neo/(.*)$': '<rootDir>/neo/$1',
    },
    testEnvironment: 'node',
    setupTestFrameworkScriptFile: './test/bootstrap.js',
    verbose: false,
};
```

//package.json
```
    "scripts": {
...
        "test": "jest --runInBand src",
        "test:setup": "babel-node build/jest_build_test_files.js",
        "test:watch": "jest --runInBand --watch server",
        "coverage": "jest --collectCoverageFrom=server/**.js --coverage server"
    },
```

1. Operating system: macOS 10.14

### Prerequisite
- are you able to run jest test from command line? yes
- how do yo run your tests from command line? `npm run test`

### Expected Behavior

To run the tests with same options defined in my package.json and get the same results when I run in command line (npm run test)

### Actual Behavior

When I start Jest runner, it finds some errors because the tests are run in parallel (not with --runInBand)

--- 

The fastest (and the most fun) way to resolve the issue is to submit a pull-request yourself. If you are interested, feel free to check out the [contribution guide](https://github.com/jest-community/vscode-jest/CONTRIBUTING.md), we look forward to seeing your PR...

**Comment by connectdotz** [comment]
if you expect this plugin to run `npm run test` but haven't configured the `jest.pathToJest` accordingly, chances are it is not using it... You can [check it yourself](https://github.com/jest-community/vscode-jest#plugin-not-running-as-expect-try-self-diagnosis) by turning on the debug mode to see the exact command the runner is using.

**Comment by fillon** [comment]
Thank you. It's working now as expected.

In settings, I added:

jest.pathToJest = node_modules/.bin/jest --runInBand

**Comment by connectdotz** [comment]
great!
