### ISSUE TITLE
Integrate with vscode's Test Explorer UI

### ISSUE THREAD

**Issue by offero** [jest-community/vscode-jest#402]
It would be great if this extension could integrate with https://marketplace.visualstudio.com/items?itemName=hbenl.vscode-test-explorer

**Comment by IGx89** [comment]
Someone just recently made their own it looks: https://github.com/rtbenfield/vscode-jest-test-adapter. Works pretty well!

**Comment by hbenl** [comment]
@agnoam sorry, this is the wrong place for your question - you should open an issue in the [repository for the jest adapter](https://github.com/rtbenfield/vscode-jest-test-adapter).

**Comment by airtonix** [comment]
> Someone just recently made their own it looks: https://github.com/rtbenfield/vscode-jest-test-adapter. Works pretty well!

repo deleted

**Comment by hbenl** [comment]
FYI: A new [Jest Test Explorer](https://marketplace.visualstudio.com/items?itemName=kavod-io.vscode-jest-test-adapter) extension (forked from the removed one) has been published to the marketplace.

**Comment by j-m** [comment]
> FYI: A new [Jest Test Explorer](https://marketplace.visualstudio.com/items?itemName=kavod-io.vscode-jest-test-adapter) extension (forked from the removed one) has been published to the marketplace.

That extension does not work with Typescript and needs its own config for anything more complex than tests in root. 
I would love to see this extension use the Test Explorer UI

**Comment by JordanLongstaff** [comment]
The strange thing to me is, the documentation and release notes claim that the Test Explorer already exists (and includes GIFs of it) and other people seem to be having issues with its operations, yet we (in this thread) can't even seem to get it to work at all??

**Comment by connectdotz** [comment]
vscode released the official TestExplore in 2021 July release - v1.59, which was supported since [vscode-jest@v4.1](https://github.com/jest-community/vscode-jest/releases/tag/v4.1.0) in Aug/2021.

As you can see, all comments are prior and this is just an old thread, we should have closed it in 4.1. thanks for the reminder.
