### ISSUE TITLE
Bugs when `test`s are in loops

### ISSUE THREAD

**Issue by garyking** [jest-community/vscode-jest#405]
### Environment

1. `node -v`: v8.11.2
1. `npm -v`: 6.4.1
1. `npm ls jest` or `npm ls react-scripts` (if you haven’t ejected): jest@23.6.0
1. your vscode-jest settings if customized:
    - jest.pathToJest? `node_modules/.bin/jest`

1. Operating system: macOS 10.13.6 (17G3025)

### Prerequisite
- are you able to run jest test from command line? `Yes`
- how do you run your tests from command line? (for example: `npm run test` or `node_modules/.bin/jest`) `jest`

### Steps to Reproduce

`a.js`:

```js
module.exports = [true, true];
```

`a.test.js`:

```js
const a = require('./a');

describe('test', () => {
  a.forEach((item) => {
    test(String(item), () => {
      expect(item).toBe(false);
    });
  });
});
```

### Expected and actual Behavior

The icon next to `test(` should be red, indicating a failed test. But it's a hollow green. 

Errors should be reported in the `Problems` panel, but it's empty.

---

There seems to be a few problems when tests are inside loops. The bubbles are always hollow green, rather than solid green/red. If there's an error, then it correctly says in the status bar `1 test suite failed`, but nothing is shown in the `Problems` panel.

Test with the code above, and see the screenshot below.

![vs code - jest - loops](https://user-images.githubusercontent.com/343940/48511980-3b887500-e826-11e8-9813-edfd0e65b5ca.png)

**Comment by seanpoulter** [comment]
From what I remember we're only matching test names as strings. I'd suggest the next steps for this would be to have a look at how we're parsing the test names from the source code when it's an expression like that.
