### ISSUE TITLE
rerunning a failed test using Debug link, runs all tests with the same description/name

### ISSUE THREAD

**Issue by jayarjo** [jest-community/vscode-jest#406]
I'm not sure if that's issue or intended behaviour, so I thought I'd ask first. When a particular test fails and I click `Debug` on top of it, assuming that only that specific test will run, process runs this very test and also all identically named tests from all other identically named test/spec files (absolute paths differ).

Any advice/recommendation on this?

**Comment by seanpoulter** [comment]
Thanks for reporting the issue. The tests are parsed using `jest-editor-support`. About a year ago only the test names were being parsed (e.g.: `it(testName)`). There was talk about parsing the test suite names (e.g.: `describe(testSuiteName)`), but I'm not sure where the state of those changes are. 🤔 

Before we can qualify the tests, we'll need to have a look at that. Would you be willing to run the extension locally and see what's returned when your tests are parsed?

**Comment by connectdotz** [comment]
this should not be an issue with the TestExplorer's gutter context menu. close the old issue.
