### ISSUE TITLE
Test is not recognized as failed/deviates from Jest CLI

### ISSUE THREAD

**Issue by ford04** [jest-community/vscode-jest#416]
### Environment

1. `node -v`: v10.13.0
1. `npm -v`: 6.4.1
1. `npm ls jest`: jest@23.6.0
1. your vscode-jest settings if customized:
    - anything else that you think might be relevant?  ts-jest 23.10.5,  typescript 3.2.2, VS Code 1.3.0

1. Operating system: Win10 Pro

### Prerequisite
- are you able to run jest test from command line? yes
- how do you run your tests from command line? `npx jest / npx jest --watch`

### Steps to Reproduce
https://github.com/ford04/vscode-jest-issue-sample.git
- Run `npx jest` - there should be 3 failed tests in 1 suite
- Go to __tests__\A.ts via editor - vscode-jest shows only 2 failed 🤔
- If I rename the test on [line 17](https://github.com/ford04/vscode-jest-issue-sample/blob/master/__tests__/A.ts#L17) for example in "t3", the third test is correctly recognized as failed in vscode-jest ( = equal with CLI).

### Expected Behavior
- should show all 3 tests as failed in vscode-jest (same as with jest CLI)

### Actual Behavior
- shows only 2 failed tests
- It seems that the error indirectly thrown by `container.throwSomething()` on  [line 19](https://github.com/ford04/vscode-jest-issue-sample/blob/master/__tests__/A.ts#L19) is kinda swallowed
- But if I throw an error directly within an equally named test, it still recognises it [line 23](https://github.com/ford04/vscode-jest-issue-sample/blob/master/__tests__/A.ts#L23)

Thats my first try on vscode-jest and I am kinda confused. Is Typescript supposed to be fully supported by vscode-jest?

**Comment by zoemoran** [comment]
I have this issue and am not using TypeScript. This is a very simple illustration of the problem:
```
function expectTrue(value) {
  return expect(value).toBe(true);
}

describe('1', () => {
  it('a test', () => {
    expectTrue(true);
  });
});

describe('2', () => {
  it('a test', () => {
    expectTrue(false);
  });
});
```
![screenshot 2019-01-24 at 11 17 51](https://user-images.githubusercontent.com/11923207/51674830-bb228500-1fc9-11e9-90a2-edb8bd85768c.png)

Clearly the 2nd test should be failing (and does from the CLI).

**Comment by connectdotz** [comment]
this is most likely caused by the same test description... Currently, the plugin doesn't take "context", such as the describe block, into consideration, the fix is on the way... For now, try to give each test block a unique description.
