### ISSUE TITLE
Extension fails to run tests on Windows, works from command line

### ISSUE THREAD

**Issue by enlyth** [jest-community/vscode-jest#424]
I've come across a situation with our project where tests work when doing 'npm test' from the command line, but the plugin will fail to run them, regardless of what settings are used (trust me I've tried every configuration under the sun).

The relevant parts of our config are:
1. Using babel-jest, with `env`, `react`, `typescript` presets
2. Including RAF polyfill, Babel polyfill and Enzyme

The issue is when the extension tries to run the tests, I get errors saying it cannot resolve any modules. I've traced this to the lowercase drive letter given by vscode's `vscode.workspace.rootPath`. The following code which recreates this extension's spawning process should demonstrates the issue:

```
const childProcess = require("child_process");
cwd = "C:\\src2\\myproj";
// cwd = "c:\\src2\\myproj"; // Lowercase drive letter, this will FAIL, unable to resolve modules when running

const proc = childProcess.spawn(
  "npm",
  [
    "test",
    "--",
    "--json",
    "--useStderr",
    "--outputFile",
    "C:\\Users\\BORIS~1.POP\\AppData\\Local\\Temp/jest_runner.json",
    "--watch",
    "--no-color"
  ],
  { cwd: cwd, shell: true, env: process.env }
);
```
First of all I've noticed in the VSCode Docs that `vscode.workspace.rootPath` is deprecated, and `vscode.workspace.workspaceFolders` should be used instead, with the zeroth one in the array having the equivalent information as rootPath. I'd be happy to raise a PR for this (can't remember if it's this package or `jest-editor-support` that handles this part, regardless).

The issue is this won't fix this issue though, when reading the VSCode documents, it says that the `WorkspaceFolder.uri.fsPath` normalizes windows drive letters to lower case, which is what causes this problem.

Any ideas on a fix?

### Environment
1. `node -v`: 11.6
1. `npm -v`: 6.5.0.next.0
1. `npm ls jest` or `npm ls react-scripts` (if you haven’t ejected): irrelevant
1. your vscode-jest settings if customized:
    - jest.pathToJest? `npm test --`

1. Operating system: Windows 10

### Prerequisite
- are you able to run jest test from command line? Yes
- how do you run your tests from command line? npm run test

### Steps to Reproduce
Use babel-jest, set jest.pathToJest to `npm test --` for example, and the extension will fail to run the tests correctly.

**Comment by connectdotz** [comment]
this should be fixed in v4 where you can run npm test directly from the debug config.
