### ISSUE TITLE
Plugin won't run on Windows when project is in a path with a space in it.

### ISSUE THREAD

**Issue by paulfelton** [jest-community/vscode-jest#426]
### Environment

1. `node -v`: [v8.11.3]
1. `npm -v`: [v6.8.0]
1. `npm ls jest` or `npm ls react-scripts` (if you haven’t ejected): [n/a]

1. Operating system: [Windows 8.1]

### Prerequisite
- are you able to run jest test from command line? [yes]
- how do you run your tests from command line? (for example: `npm run test` or `node_modules/.bin/jest`) [npm run test]

### Steps to Reproduce

1. Place your project in a folder containing a space, eg: e:\My Websites\myproject.
Plugin attempts to run multiple times before giving up, saying it can't find 'e:\My'.

### Expected Behavior

Plugin should be able to handle Windows paths

### Actual Behavior

Complains it can't find 'e:\My'

--- 

The fastest (and the most fun) way to resolve the issue is to submit a pull-request yourself. If you are interested, feel free to check out the [contribution guide](https://github.com/jest-community/vscode-jest/CONTRIBUTING.md), we look forward to seeing your PR...

**Comment by beatgates** [comment]
Same issue as #360, #342
Work-around was to add in vs code settings "jest.pathToJest": "npm run test --"
I don't believe #342 should be closed with just a work-around?
