### ISSUE TITLE
Add full support for parametrized tests

### ISSUE THREAD

**Issue by andris-zalitis** [jest-community/vscode-jest#427]
### Environment

1. `node -v`: v11.10.0
2. `npm -v`: 6.7.0
3. `npm ls jest`: └── jest@24.1.0 
4. Operating system: macOS Mojave

### Prerequisite
- are you able to run jest test from command line? yes
- how do you run your tests from command line? (for example: `npm run test` or `node_modules/.bin/jest`) `npm test`

### Expected Behavior

When using syntax `test.each(table)(name, fn, timeout)` [described here](https://jestjs.io/docs/en/api.html#1-testeachtable-name-fn-timeout) test status circles show the status of tests and failed test error appears in-line.

### Actual Behavior

When using syntax `test.each(table)(name, fn, timeout)` test status circles are not shown and test errors are not displayed inline.

### Workaround
If applying parametrization to `describe` with `describe.each`, test status information seems to be showed correctly.

In the image below all three tests should have been marked as failed. As it can be seen, the second does not show any test status information and the third (workaround) seems to work. Since I don't want to wrap all my separate tests into `describe.each` workaround is not that useful in my case.

<img width="429" alt="screenshot 2019-02-25 at 10 34 51" src="https://user-images.githubusercontent.com/1741865/53324287-186f6600-38e9-11e9-97ab-97ee3a0b1580.png">

**Comment by malnor** [comment]
Was just looking for the same thing. it.each/test.each does not work, but it would be really helpful if it would. To use describe.each instead is not an applicable workaround for me as it defeats the purpose of having several things to test for one describe.

**Comment by dgreene1** [comment]
Upvote

**Comment by KyranRana** [comment]
Upvote and bump 👍

**Comment by hakubo** [comment]
upvote

**Comment by exapsy** [comment]
Upvote, but not really a workaround the one you described @andris-zalitis . The whole `test.each` purpose is to prevent having to write 100 different `it()/test()`, and the workaround is exactly just making a cycle back to this practice. :P

**Comment by connectdotz** [comment]
for people who are interested in this issue, please try [v4-alpha](https://github.com/jest-community/vscode-jest/releases/tag/v4.0.0-alpha.1) that should have addressed this issue.

**Comment by DScheglov** [comment]
@connectdotz , I'm using `vscode-jest-4.0.0-alpha.2`.

it seams when there is only one `it.each` per `describe` the status is displayed correctly, when two or more the status is `?`.

1. `node -v`: **v14.15.4**
1. `npm -v`: **6.14.11**
1. `npm ls jest` or `npm ls react-scripts` (if you haven’t ejected): **jest@25.5.4** 
1. your vscode-jest settings if customized:
    - jest.pathToJest? `not customized`
    - jest.pathToConfig? `not customized`
1. OS: **Ubuntu 20.04** (64 bit).
1.Jest Config:
```json
{
    "preset": "ts-jest",
    "testEnvironment": "node",
    "collectCoverage": true,
    "collectCoverageFrom": [
      "src/**/*.ts"
    ]
  }
```

![Screenshot from 2021-01-15 13-12-52](https://user-images.githubusercontent.com/9888941/104719357-042eef00-5735-11eb-94fb-8b06a53f6124.png)
![Screenshot from 2021-01-15 13-14-16](https://user-images.githubusercontent.com/9888941/104719373-098c3980-5735-11eb-9291-dbea5b257e75.png)
![Screenshot from 2021-01-15 13-25-05](https://user-images.githubusercontent.com/9888941/104719440-1f99fa00-5735-11eb-8c06-b0be832372b8.png)

```typescript
describe('id', () => {
  it.each([
    [true],
    [false],
  ])('returns %s for %s', value => {
    expect(value).toBe(value);
  });
});
describe('not', () => {
  it.each([
    [true],
    [false],
  ])('%s not equal to reverse', value => {
    expect(!value).not.toBe(value);
  });
});
```

**Comment by connectdotz** [comment]
indeed we have some gaps to cover... see #649

**Comment by connectdotz** [comment]
[v4.0.0-alpha.3](https://github.com/jest-community/vscode-jest/releases/tag/v4.0.0-alpha.3) is released today. The main change is to support the parameterized tests. Feel free to give this release a try and open new issues if needed...

**Comment by DScheglov** [comment]
> [v4.0.0-alpha.3](https://github.com/jest-community/vscode-jest/releases/tag/v4.0.0-alpha.3) is released today. The main change is to support the parameterized tests. Feel free to give this release a try and open new issues if needed...

I will try it today some later. Thanks a lot for a quick fix!

**Comment by DScheglov** [comment]
@connectdotz , hey

Now correctly works only the first in the file `it.each`:

![Screenshot from 2021-01-27 21-20-33](https://user-images.githubusercontent.com/9888941/106042403-acee2e80-60e5-11eb-8cc9-22640a65fdad.png)

**Comment by connectdotz** [comment]
@DScheglov I tried your snippet above and all seems to be fine:

<img width="684" alt="Screen Shot 2021-01-27 at 4 45 30 PM" src="https://user-images.githubusercontent.com/891093/106058494-4e15be80-60bf-11eb-9acd-1300e3d35984.png">

Something else is at play here... which jest version your project is on? I should have mentioned that for parameterized tests to be properly reported, you need to have jest version >= 26.5.0 (see migration notes for alpha.3 release). Otherwise, can you post the relevant debug message from the developer console or OUTPUT channel?

**Comment by DScheglov** [comment]
> @DScheglov I tried your snippet above and all seems to be fine:
> Something else is at play here... which jest version your project is on? I should have mentioned that for parameterized tests to be properly reported, you need to have jest version >= 26.5.0 (see migration notes for alpha.3 release). Otherwise, can you post the relevant debug message from the developer console or OUTPUT channel?

Hey, @connectdotz thanks. I had 25.x.x version of jest. Upgrading it to the 26.6.3 helped. Now it works well.
Thank you for your help.
