### ISSUE TITLE
Feature Request: Support having multiple test configs

### ISSUE THREAD

**Issue by yatki** [jest-community/vscode-jest#428]
### Expected Behavior

I have a project that in test folder I have unit, integration and functional tests. Each test folder has its own configuration and setup files. 

It would be great to have possibility to map different configuration for different test folders.

Example: 
```
{
  jest.instances: {
    "test/unit/*": "jest --config=./test/unit/config.js",
    "test/integration/*": "jest --config=./test/integration/config.js",
    "test/functional/*": "jest --config=./test/functional/config.js",
  }
}
```

So this way, for the test files under `test/unit` folder, extension will execute the corresponding command.

### Actual Behavior

It doesn't support this at the moment.

**Comment by yatki** [comment]
Seems like we can achieve this after this https://github.com/jest-community/vscode-jest/issues/129 issue were closed. But i don't see any action on it.

**Comment by renestalder** [comment]
I have the exact same setup and would love being able to configure that.

**Comment by jsphstls** [comment]
@yatki I wonder if the issue is order is reversed, that this option could be implemented in way that closes #129.

**Comment by saeidzebardast** [comment]
Any news about this feature?

**Comment by FERNman** [comment]
I have a very similar problem. In my opinion, the best way to solve this would be to take the config file closest to the current test file as the responsible config file.

**Comment by wrslatz** [comment]
I think this could potentially help with monorepo projects where the CLI is configured to run jest using `jest.config.js` files in subdirectories.

See https://github.com/nrwl/nx/issues/2803 and https://github.com/nrwl/nx/issues/2344

**Comment by askirmas** [comment]
Done with https://jestjs.io/docs/en/configuration#projects-arraystring--projectconfig

**Comment by connectdotz** [comment]
#129 basically supports vscode's [multiroot workspaces](https://code.visualstudio.com/docs/editor/multi-root-workspaces), which can be used for monorepo project (each package can be configured as a folder). 

I can see a few possible ways to do this today:

1. create a vscode folder for each of the test folder. Then configure each folder to use its own `jest.pathToJest` or `jest.pathToConfig`
1. try to use @askirmas suggestion of `--projects` to treat them as separate projects. Make sure you can run the CLI in terminal first, then customize the `jest.pathToJest` to use the same command.

Please let us know if any of the above works for you.

**Comment by askirmas** [comment]
@connectdotz I have some issues settings 'propagation' in multiroot mode. Additional things to check for 1st point - in launch options use some vscode path variable that points to current workspace not root

**Comment by askirmas** [comment]
If jest config is not common for all subprojects, then their all other configs should be different - extensions, settings, launches. So rather natural to make them their own 'scope' with workspace

**Comment by JPeer264** [comment]
Following (as @askirmas suggested) works out of the box with jest. I adapted everything according to @yatki's needs:

```js
const createProject = (type) => ({
  transform: {
    '^.+\\.(t|j)sx?$': 'ts-jest',
  },
  globals: {
    'ts-jest': {
      isolatedModules: true,
    },
  },
  displayName: type,
  preset: 'ts-jest',
  globalSetup: `./__setup__/${type}/jest.global-setup.ts`,
  setupFilesAfterEnv: [`./__setup__/${type}/jest.setup-after-env.ts`],
  testRegex: `(/test/${type}/.*| (\\.| /)(test|spec))\\.[jt]sx?$`,
});

module.exports = {
  projects: [
    createProject('unit'),
    createProject('integration'),
    createProject('functional'),
  ],
};
```

With that config debug works just as expected on each folder.

**Comment by markwalsh-liverpool** [comment]
Is there a documented way in which to configure this; if the projects differ?

@JPeer264's projects are all the same but there could be a situation in which your project setup (unit/integration etc) are different?
