### ISSUE TITLE
ts-jest not being applied for config with projects

### ISSUE THREAD

**Issue by tonyhallett** [jest-community/vscode-jest#437]
### Environment

1. `node -v`: 10.15.3
1. `npm -v`: 6.9
1. `npm ls jest` 24.5

1. Operating system: Windows 10 Pro 1803

### Prerequisite
- are you able to run jest test from command line? Yes
- how do you run your tests from command line? (for example: `npm run test` or `node_modules/.bin/jest`) - in this particular project npm run test

### Steps to Reproduce

Open the [minimal reproducable](https://github.com/tonyhallett/vscodejestprojectsissue) in vscode.
Works ok until uncomment the test containing typescript in project2/__tests__/project2.test.ts and save.

### Expected Behavior

vscode works the same as running the npm script which works ( npm run test )

### Actual Behavior

parser errors - see output pane

**Comment by Illyism** [comment]
What are the errors for reference?
