### ISSUE TITLE
VSCode Intellisense is not suggesting available methods in JEST

### ISSUE THREAD

**Issue by kartheektrilochan** [jest-community/vscode-jest#440]
### Environment
1. `node -v`: v.9.2.0
1. `npm -v`: 5.5.1
1. `npm ls jest` or `npm ls react-scripts` (if you haven’t ejected):
npm ls jest 
+-- jest@24.5.0
`-- react-scripts@2.1.8
  `-- jest@23.6.0

1. your vscode-jest settings if customized:
    - jest.pathToJest? [fill]
    - jest.pathToConfig? [fill]
    - anything else that you think might be relevant? [fill]

1. Operating system: Windows_NT x64 10.0.17134

### Prerequisite
- are you able to run jest test from command line? yes
- how do you run your tests from command line? npm run test

Steps to Reproduce:

Create a new react app using 

1 .npx create-react-app my-app 
2. npm install --save-dev jest
3. Opened the project in VSCode.

 

### Expected Behavior
I expect VS Code intellisense would assist me with available methods from JEST.

### Actual Behavior

VS Code is not suggesting me any method suggestions for JEST test cases.

**Comment by dlee005c** [comment]
same for me as well.
node -v v9.6.1
npm -v 6.9.0
For what it's worth, i'm using nvm to manage node/npm

**Comment by cassiobock** [comment]
I'm having the same problem. I've tried installing [@types/jest](https://www.npmjs.com/package/@types/jest) with `npm i @types/jest` and the suggestions started to show again.

**Comment by filipeestacio** [comment]
I found that I need to restart vscode after installing @types/jest if vscode was open during installation. Can anyone confirm if that is expected?

**Comment by Waserman** [comment]
create `jsconfig.json`  in the root directory of your project.
the file should contain the following:
`
{
    "typeAcquisition": {
        "include": [
            "jest"
        ]
    }
}
`

after saving reload vscode.
Worked for me.

**Comment by diazgilberto** [comment]
> create `jsconfig.json` in the root directory of your project.
> the file should contain the following:
> `{ "typeAcquisition": { "include": [ "jest" ] } }`
> 
> after saving reload vscode.
> Worked for me.

For some reason this solution doesn't work for me. Interesting is that I found a post from Nicholas Zakas post with the solution you are proposing. I'm wondering if I need to tell vscode about `jsconfig.json` or doesn vscode just picked it up if its there.

**Comment by noxasch** [comment]
mine only works after i install `@type/jest`

node v10.15.0
npm v6.5.0

```
npm i -D @types/jest
```

**Comment by danielo515** [comment]
None of the provided solutions works for me. Guess what else can I try

**Comment by diazgilberto** [comment]
> None of the provided solutions works for me. Guess what else can I try

Try to create a new user in your computer with a fresh installation of vscode and do `npm i -D @types/jest` and see if that works. I'm just trying to isolate all other extensions that might be causing conflict.

**Comment by FernanddoSalas** [comment]
Install `@types/jest` as a dev dependencie works for me.
I've tried to install it globally but it seems not work.

**Comment by iotheo** [comment]
[eslint-plugin-jest](https://www.npmjs.com/package/eslint-plugin-jest) seems to be a prerequisite. After adding it to your dev dependencies, don't forget to add the jest to your eslint config file, as shown below.

```javascript
env: {
  // other envs
  jest: true
}

**Comment by jjayaraman** [comment]
Thanks, Guys, as mentioned above just the below in jsconfig.json works for me.
I though in javascript projects this is a better option, as javascript project like react does not need to install @types/xxxx. I guess @types are only for typescript projects? 

```
{
    "typeAcquisition": {
        "include": ["jest"]
    }
}
```

**Comment by or4** [comment]
install local and global types, works fine
npm i @types/jest
npm i -g @types/jest

**Comment by jcairo** [comment]
Including the test folder in tsconfig fixed it for me.

`"include": ["src", "test"]`

**Comment by andmill** [comment]
> 
> 
> Including the test folder in tsconfig fixed it for me.
> 
> `... "include": ["src", "test"]`

This worked for me too. I have the _orta.vscode-jest_ extension installed and am running a react 16 project with `npx create-react-app`.
No restart of VSCode required

**Comment by jcairo** [comment]
Only problem is that it then compiles the code test project folder. Still not a great solution...

**Comment by leaveswoods** [comment]
Installing @types/jest solved the problem while adding this to jsconfig.js could not help`
{
    "typeAcquisition": {
        "include": ["jest"]
    }
}`

**Comment by sumeetchawla** [comment]
> I found that I need to restart vscode after installing @types/jest if vscode was open during installation. Can anyone confirm if that is expected?

Yup, yesterday it wasn't working. I closed and went to sleep and it is working now. I did a lot of window reload yesterday but didn't work either.

**Comment by azad21012** [comment]
before  read this issue i thought  need an extension like jest -published by orta- . but after installing @types/jest and reload vs-code the methods suggested by vs-code :)

**Comment by onuriltan** [comment]
**P.S** Doing both steps worked for me, and the last one 🙂 
1. `npm i -D @types/jest`
2. Add `jsconfig.json` to root folder as
```
{
    "typeAcquisition": {
        "include": ["jest"]
    }
}
```
3. Reload Vscode

**Comment by jvmazagao** [comment]
> **P.S** Doing both steps worked for me, and the last one 🙂
> 
> 1. `npm i -D @types/jest`
> 2. Add `jsconfig.json` to root folder as
> 
> ```
> {
>     "typeAcquisition": {
>         "include": ["jest"]
>     }
> }
> ```
> 
> 1. Reload VSCode

In my vscode this solution works very well.

**Comment by GigaGeekKPI** [comment]
> Install `@types/jest` as a dev dependencie works for me.
> I've tried to install it globally but it seems not work.

Dude, thank you so much

**Comment by yevhen-logosha** [comment]
my case was an outdated version of `@types/jest`, upgrading it to match version of Jest did the trick

**Comment by dil-dbakker** [comment]
My case was opening VSCode at the root of our repo, rather than the src folder which contained our jest.config.js and tsconfig.json files. When I opened the src folder as a VSCode Project, everything worked as expected.

**Comment by aardvarkk** [comment]
@dil-dbakker Thank you! This was exactly my problem. I tried about a thousand complicated config options people were proposing but I was just one directory "too high" opening a parent directory in VSCode. Running `vscode .` inside the specific project I was working with fixed everything for me.

**Comment by alonsogchparra** [comment]
> create `jsconfig.json` in the root directory of your project.
> the file should contain the following:
> `{ "typeAcquisition": { "include": [ "jest" ] } }`
> 
> after saving reload vscode.
> Worked for me.

This suggestion worked for me very well. Thanks for the feedback

**Comment by connectdotz** [comment]
great thread to help people resolving similar issues. But since this issue is really not related to this extension, I will close it.

**Comment by wbolduc** [comment]
> great thread to help people resolving similar issues. But since this issue is really not related to this extension, I will close it.
Where would you recommend this information goes

I was experiencing this same sort of problem where intellisense would not show the available jest methods despite doing what almost every thread on the topic suggests

I was able to resolve it but I don't know why this works.

_remove_ `{ "typeAcquisition": { "include": [ "jest" ] } }`
make sure that in the jsconfig.json you are not specifying a compilerOption.target

My resulting config looks like this (minus work specific stuff)
`{
	//for some reason type acquisition and and target both break intellisense for jest
	"compilerOptions": {
		"allowSyntheticDefaultImports": false,
		"baseUrl": "./",
		"paths": {
			"Test/*": ["./__mocks__/*"]
		}
	},
	"include": ["./src/**/*"]
}
`

The packages I have installed relevant to testing
`
  "@testing-library/jest-dom": "^5.11.10",
  "@testing-library/react": "^11.2.6",
  "@testing-library/user-event": "^13.1.3",
  "@types/jest": "^26.0.22",
  "@types/react": "^17.0.3",
  "babel-jest": "^26.6.3",
  "babel-plugin-transform-class-properties": "^6.24.1",
  "eslint-plugin-jest": "^24.3.5",
  "jest": "^26.6.3",
  "jest-dom": "^4.0.0",
  "msw": "^0.28.1",
`

I don't totally know why this works but it's worth a shot if you were stuck like me

**Comment by gianluca-sabena** [comment]
Another workaround is to use explicit import: "However, if you prefer explicit imports, you can do import {describe, expect, test} from '@jest/globals'."as documented here https://jestjs.io/docs/api

PS: I was not able to solve the problem with other suggest methods.
