### ISSUE TITLE
Mono-repo causes tests to fail

### ISSUE THREAD

**Issue by sh7dm** [jest-community/vscode-jest#448]
### Environment

1. `node -v`: v11.14.0
1. `npm -v`: 6.8.0
1. `npm ls jest` or `npm ls react-scripts` (if you haven’t ejected): jest@24.7.1
1. your vscode-jest settings if customized:
    - jest.pathToJest? -
    - jest.pathToConfig? -
    - anything else that you think might be relevant? -

1. Operating system: Ubuntu 18.04

### Prerequisite
- are you able to run jest test from command line? +
- how do you run your tests from command line? (for example: `npm run test` or `node_modules/.bin/jest`) jest / yarn test

### Steps to Reproduce

1. Use mono-repo project containing test in one of packages
2. Try to use extension
Repo: look at vuetifyjs/vuetify

### Relevant Debug Info

[fill]

### Expected Behavior

Ability to run extension in specific folder, not root

### Actual Behavior
It runs in root

--- 

The fastest (and the most fun) way to resolve the issue is to submit a pull-request yourself. If you are interested, feel free to check out the [contribution guide](https://github.com/jest-community/vscode-jest/CONTRIBUTING.md), we look forward to seeing your PR...

**Comment by sh7dm** [comment]
P.S. it works right if I open package itself in editor, but it's uncomfortable.

**Comment by sh7dm** [comment]
I need an option to set root for Jest.

**Comment by connectdotz** [comment]
hey @sh7dm we just released a [3.0.0 pre-release](https://github.com/jest-community/vscode-jest/releases/tag/3.0.0) that supports vscode's multi-root workspaces, you can give it a try!

**Comment by sh7dm** [comment]
@connectdotz sorry, I use Jest at a serious project and we can't switch to pre probably

**Comment by sh7dm** [comment]
Will check that out

**Comment by sh7dm** [comment]
@connectdotz can I close this now? you fixed it already
