### ISSUE TITLE
showInputBox 

### ISSUE THREAD

**Issue by 8090boy** [jest-community/vscode-jest#451]
### vscode jest
 
window.showInputBox() is called in different business files. 
How do you simulate different return values?

**Comment by 8090boy** [comment]
A.js relies on vscode , how to simulate the different return values of vscode.window.showInputBox in a.spec.js.

**Comment by stephtr** [comment]
That's not related to this extension. But you can take a look at [Jest's mock feature](https://jestjs.io/docs/en/mock-functions) and [how we](https://github.com/jest-community/vscode-jest/blob/master/__mocks__/vscode.ts) [use it](https://github.com/jest-community/vscode-jest/blob/master/tests/extension.test.ts) in this project.
