### ISSUE TITLE
Question: Is it possible to always show the DEBUG button even if the test is passing?

### ISSUE THREAD

**Issue by SpearThruster** [jest-community/vscode-jest#453]

**Comment by eghernqvist** [comment]
I did this by adding
```json
  "jest.debugCodeLens.showWhenTestStateIn": [
    "skip",
    "pass",
    "fail",
    "unknown"
  ]
```
to my `.vscode/settings.json`. Clicked the cogwheel below and then Copy Setting as JSON in User Settings:
![image](https://user-images.githubusercontent.com/10044687/58336868-e1a3e000-7e44-11e9-9d41-1afd2aa5488f.png)

**Comment by stephtr** [comment]
That's exactly the way it is supposed to work.

**Comment by SpearThruster** [comment]
Thanks @eghernqvist !
