### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Suele** [jest-community/vscode-jest#456]
- Issue Type: `Performance`
- Extension Name: `vscode-jest`
- Extension Version: `2.9.2`
- OS Version: `Linux x64 4.15.0-47-generic`
- VSCode version: `1.33.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/home/preto/Orta.vscode-jest-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by Suele** [comment]
Problem is equal to an open

**Comment by Suele** [comment]
Problem is equal to an open

**Comment by Suele** [comment]
Problem is equal to an open

**Comment by Suele** [comment]
Problem is equal to an open

**Comment by jmarceli** [comment]
Looks like https://github.com/jest-community/vscode-jest/issues/455
