### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by Alexandty** [jest-community/vscode-jest#462]
- Issue Type: `Bug`
- Extension Name: `vscode-jest`
- Extension Version: `2.9.2`
- OS Version: `Windows_NT x64 10.0.17134`
- VSCode version: `1.34.0`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by stephtr** [comment]
The needed data was in your clipboard, not ours 😉
