### ISSUE TITLE
'Would you like to update your Snapshots?' will not be shown in case of parameterized tests (describe.each)describe.each

### ISSUE THREAD

**Issue by shruda** [jest-community/vscode-jest#474]
**Environment**

1.  `node -v`: v8.16.0
2. `npm -v`: v6.4.1
3.  `npm ls jest`: jest@24.8.0
4. your vscode-jest settings if customized:
- "jest.rootPath": "./toolkit",
- "jest.restartJestOnSnapshotUpdate": true,

** Expected Behaviour ** 
I use describe.each in my tests and I expect that the "Would you like to update your Snapshots?" dialog will be shown if the snapshot tests fail.

** Actual Behaviour ** 
The dialog will not be shown because it checks only for "snapshot failed" and "snapshot test failed"

Is the following check on purpose or can it be extended so that parameterized checks also work?

https://github.com/jest-community/vscode-jest/blob/745e6035c7138fe358a03d01be97a520869de1bf/src/JestExt.ts#L408

Jest Output in case of describe.each
``` 
    DummyTests > paramTest > Value "red"
    expect(received).toMatchSnapshot()

    New snapshot was not written. The update flag must be explicitly passed to write a new snapshot.

    This is likely because this test is run in a continuous integration (CI) environment in which snapshots are not written by default.

    Received value "green"
   ....

      at Object.toMatchSnapshot (node_modules/jest-chain/dist/chain.js:15:11)
      at Object.test (tests/effects/fillEffect.test.ts:44:66)

    › 3 snapshots failed.

    Snapshot Summary
     › 3 snapshots failed from 1 test suite. Inspect your code changes or press 'u' to update them.

    Test Suites: 1 failed, 1 total
    Tests:       3 failed, 3 total
    Snapshots:   3 failed, 3 total
    Time:        3.619s
    Ran all test suites related to changed files.
```

**Comment by connectdotz** [comment]
hmm... interesting, couple of things might be at play here:
1. jest output different phrase so failed the matching logic as you pointed out in `JextExt.ts`. (PR welcome!)
1. this extension matches test results by test's "name" (via static file analysis/parsing) as well as line numbers, if the test name uses template-literal, it is recommended to use the upcoming [3.0.0+](https://github.com/jest-community/vscode-jest/releases), which has better support for it.
1. not sure if this is related without seeing the actual test file: this extension currently does not support "describe" block result matching, only test/it blocks.

**Comment by shruda** [comment]
Hi @connectdotz ,
thanks for your replay & explanation.

I created a PR and fixed the regex to detect the pluralized message 'snapshots failed'. 
I didn't find the message 'snapshot test failed' in [facebook/jest](https://github.com/facebook/jest), therefore I added the plural check only to 'snapshot failed'.

**Comment by connectdotz** [comment]
thanks @shruda, can you create a sample repo with the describe.each() test so we can verify the issue and fix.

**Comment by shruda** [comment]
@connectdotz , I adopted the Jest 'Getting-Started' example and added it to my bugreports repo:
https://github.com/shruda/bugreports/tree/master/vscode-jest/474

**Comment by connectdotz** [comment]
thanks for the PR and sample repo, which also exposed a use case `vscode-jest` doesn't support today:

the combination of `describe.each()` and parameterized test names confuses the test result matching logic as it finds multiple partial matches thus not able to update test status accordingly... 

this is a (new?) use case that probably requires some thought... nevertheless, @shruda can you log a new issue for the record. thx.

**Comment by shruda** [comment]
Done: https://github.com/jest-community/vscode-jest/issues/478
