### ISSUE TITLE
`it`s in different `describe`s with the same names always shown as a pending

### ISSUE THREAD

**Issue by a-x-** [jest-community/vscode-jest#484]
### Environment

1. `node -v && npm -v`: v11.15.0, 6.9.0
1. `npm ls jest`: WAT? I have per project jest and globally installed jest (because vscode-jest cannot detect it in multiroot or monorepo projects even I provide absolute path, also jest cannot detect babel and babel.config.js so :(
    ```
    MyProj@0.0.0 $HOME/path/to/MyProj
    └── (empty)
    ```
1. your vscode-jest settings if customized:
    - jest.pathToJest?: **no**
    - jest.pathToConfig?: **no**

1. Operating system: macOS latest

### Prerequisite
- are you able to run jest test from command line?: **yep**
- how do you run your tests from command line?: **it's not relevant to the issue**

### Steps to Reproduce

```js
describe('a', () => {
  it('works', () => {}); // it#1
});
describe('b', () => {
  it('works', () => {}); // it#2
});
```

### Expected Behavior

include full test name with all the parent describes into your hash/detecting functions, please

### Actual Behavior

Both it#1 and it#2 has pending gutters::
![Screenshot 2019-07-12 at 16 39 47](https://user-images.githubusercontent.com/6201068/61132289-c019b900-a4c3-11e9-8909-7d71965a93bf.png)

When I rename one or both of them, issue solves

**Comment by wrslatz** [comment]
Seems related to https://github.com/jest-community/vscode-jest/issues/570

**Comment by connectdotz** [comment]
this should be fixed, feel free to give [v4-alpha](https://github.com/jest-community/vscode-jest/releases/tag/v4.0.0-alpha.0) a try.
