### ISSUE TITLE
Jest not working because of spaces in project path

### ISSUE THREAD

**Issue by pardhu225** [jest-community/vscode-jest#489]
### Environment

1. `node -v`: v8.15.1
2. `npm -v`: 5.6.0
3. `npm ls jest`:
```
C:\Users\Pardhu Chowdary
--` (empty)
```
4. your vscode-jest settings if customized:
 `"jest.pathToJest": "npm run test --"`

5. Operating system: Windows 10

### Prerequisite
- are you able to run jest test from command line?
No. When I run just `jest` it gives `bash: jest: command not found`. I am using git bash btw.
- how do you run your tests from command line? 
`npm run test`
Although I'm not able to run `jest` from command line, `npm run test` works fine (detects and runs all the tests)

### Steps to Reproduce

1. Installed Jest extension via marketplace.
2. Added `"jest.pathToJest": "npm run test --"` to settings.json.
3. Output in the output panel (ctrl+shift+u) when it runs:
>&gt; expense-manager@1.0.0 test e:\Dev\expense-manager
>&gt; jest --coverage --verbose "--testLocationInResults" "--json" "--useStderr" "--outputFile" "C:\Users\Pardhu" "Chowdary\AppData\Local\Temp\jest_runner_expense_manager.json" "--no-color"
>
>
>No tests found, exiting with code 1
>Run with `--passWithNoTests` to exit with code 0
>In E:\Dev\expense-manager
>  46 files checked.
>  testMatch:  - 0 matches
>  testPathIgnorePatterns: \\node_modules\\ - 46 matches
>  testRegex: (\\\_\_tests\_\_\\.*|(\.|\\)(test|spec))\.ts$ - 1 match
>Pattern: Chowdary\AppData\Local\Temp\jest_runner_expense_manager.json - 0 matches

I'm pretty sure this is caused due to the space in the path: 
`C:\Users\Pardhu Chowdary\AppData\Local\Temp\jest_runner_expense_manager.json`
Tried the fix as suggested in #342 
### Relevant Debug Info

Partial package.json:
```
  "main": "dist/src",
  "scripts": {
    "prebuild": "tslint -c tslint.json -p tsconfig.json --fix",
    "build": "tsc",
    "prestart": "npm run build",
    "start": "node .",
    "test": "jest --coverage --verbose",
    "dev": "tsc-watch --onSuccess \"node ./dist/index.js\""
  },
  "dependencies": {
    "body-parser": "^1.19.0",
    "colors": "^1.3.3",
    "cookie-parser": "^1.4.4",
    "express": "^4.17.1",
    "firebase-admin": "^8.3.0",
    "mongoose": "^5.6.0"
  },
  "devDependencies": {
    "@types/cookie-parser": "^1.4.1",
    "@types/express": "^4.17.0",
    "@types/jest": "^24.0.15",
    "@types/mongoose": "^5.5.11",
    "@types/node": "^12.6.8",
    "jest": "^24.8.0",
    "nyc": "^14.1.1",
    "ts-jest": "^24.0.2",
    "ts-node": "^8.3.0",
    "tslint": "^5.18.0",
    "typescript": "^3.5.3"
  },
  "jest": {
    "verbose": true,
    "transform": {
      "^.+\\.tsx?$": "ts-jest"
    },
    "testRegex": "(/__tests__/.*|(\\.|/)(test|spec))\\.ts$",
    "moduleFileExtensions": [
      "ts",
      "tsx",
      "js",
      "jsx",
      "json",
      "node"
    ]
  }
```

### Expected Behavior
Tests should appear in the sidebar

### Actual Behavior
Nothing appears. Status bar gets stuck with `Jest: -\|/ Starting watch mode`

--- 

The fastest (and the most fun) way to resolve the issue is to submit a pull-request yourself. If you are interested, feel free to check out the [contribution guide](https://github.com/jest-community/vscode-jest/CONTRIBUTING.md), we look forward to seeing your PR...

**Comment by Ahryman40k** [comment]
I think I've got the same problem, 
`Exception raised: Process failed: spawn /media/ahryman40k/636194ba-d3c5-4360-9eb9-4a9fbc8e276f/-- ENOENT`
My project path is:` /media/ahryman40k/636194ba-d3c5-4360-9eb9-4a9fbc8e276f/-- Sources --`

Launch `jest` or `npm run test` and using my local jest binary both work, but jest extension still fails.

jest.config.js
> module.exports = {
>     verbose: true,
>     transform: {
>       "^.+\\.tsx?$": "ts-jest"
>     },
>     testPathIgnorePatterns: ['/node_modules/', '/dist/'],
>     testRegex: '(/__tests__/.*|(\\.|/)(test|spec))\\.tsx?$',
>     collectCoverageFrom : ["**/*.{ts,tsx}", "!**/node_modules/**"]
>   }

vscode .launch
> {
>     "version": "0.2.0",
>     "configurations": [
>         {
>             "type": "node",
>             "name": "vscode-jest-tests",
>             "request": "launch",
>             "args": [
>                 "--runInBand"
>             ],
>             "cwd": "${workspaceFolder}",
>             "console": "integratedTerminal",
>             "internalConsoleOptions": "neverOpen",
>             "disableOptimisticBPs": true,
>             "program": "${workspaceFolder}/node_modules/jest/bin/jest"
>         }
>     ]
> }

**Comment by teleclimber** [comment]
I'm experiencing this as well. My project folder has spaces in it:

```
~/Documents/Projects/tests/19-09-03 vue mobx ts/
```

The error hints strongly that it is confused by spaces:
```
Exception raised: Process failed: spawn /Documents/Projects/tests/19-09-03 ENOENT
```

My tests work fine from the command line.

Mac OS 10.12.6, npm 6.2.0, jest 24.9.0

Thanks.
