### ISSUE TITLE
Red/green dots in left-side of editor don't work for colorblind people

### ISSUE THREAD

**Issue by bryanjclark** [jest-community/vscode-jest#500]
### Environment

1. `node -v`: v8.16.0
1. `npm -v`: 6.9.0
1. `npm ls jest` or `npm ls react-scripts` (if you haven’t ejected): 
@0.0.0 /Users/bryan/git/mobile/react-native
└── jest@23.5.0 

1. Operating system: macOS Mojave 10.14.6

### Prerequisite
- are you able to run jest test from command line? yes
- how do you run your tests from command line? (for example: `npm run test` or `node_modules/.bin/jest`) `yarn run test`

### Steps to Reproduce

1. Using VSCode Jest as a colorblind person, it's hard for me to distinguish between red and green circles in the left-hand rail of the editor window:

<img width="891" alt="Napkin 2 09-19-19, 1 44 17 PM" src="https://user-images.githubusercontent.com/868389/65279662-a5774800-dae3-11e9-8ee5-74a8ec2038ee.png">

### Expected Behavior

The design should work even without color, so people with visual impairments can use the tool. Perhaps a different symbol would work — like one of these? 

Ⓧ ✘✖︎✗☞☛◎✕

I know there _could_ be a preference for this, but it'd be much better to do this without a preference!

### Actual Behavior

Because the red and green dots look the same to me, they're not as useful.

**Comment by bryanjclark** [comment]
I'll work on a PR! 😄

**Comment by jmarceli** [comment]
I think that this issue may be closed as it is addressed by the merged PR.

**Comment by bryanjclark** [comment]
This is closed! Thanks very much!
