### ISSUE TITLE
Replace the spinner for `initial full test run`

### ISSUE THREAD

**Issue by rhalaly** [jest-community/vscode-jest#505]
### Expected Behavior

Status bar will be static, and not jumpy...

### Actual Behavior

The current slash spinner cause entire status bar to jump since the length of the spinner frames are different. This is very annoying...

--- 

I think I can send a PR that is using the [VS Code spinner](https://code.visualstudio.com/api/references/icons-in-labels#animation) `$(sync~spin)`

**Comment by connectdotz** [comment]
> I think I can send a PR that is using the VS Code spinner $(sync~spin)

👍
