### ISSUE TITLE
Does not load jest config from CRA

### ISSUE THREAD

**Issue by abumalick** [jest-community/vscode-jest#515]
### Environment

1. `node -v`: `v12.13.0`
1. `npm -v`: `6.12.0`
1. `npm ls jest` or `npm ls react-scripts` (if you haven’t ejected):
```
npm ls jest
└─┬ react-scripts@3.2.0
  └── jest@24.9.0 
npm ls react-scripts
└── react-scripts@3.2.0 
```
1. your vscode-jest settings if customized:
    - jest.pathToJest? [fill]
    - jest.pathToConfig? [fill]
    - anything else that you think might be relevant? [fill]

1. Operating system: macOS High Sierra 10.13.6

### Prerequisite
- are you able to run jest test from command line? yes
- how do you run your tests from command line? (for example: `npm run test` or `node_modules/.bin/jest`) npm run test

### Steps to Reproduce

https://github.com/abumalick/vscode-test-cra/commit/1a787e8cf3513fa4e0b6d891a405a5330af5baac

Try to run vscode on this repository, you will see that vscode-jest's test will fail. If you run `yarn test` it will pass.

If you uncomment https://github.com/abumalick/vscode-test-cra/blob/master/src/App.test.js#L4 the test passes.

This shows that vscode-jest is not loading jest config of create-react-app

### Relevant Debug Info

[fill]

### Expected Behavior

It should load the config from create react app

### Actual Behavior

It seems that it is not the same configuration

--- 

It seems that wallaby creates a jest configuration that will be generated from jest configuration of create-react-app ref: https://wallabyjs.com/docs/tutorial/react.html

Thank you for the extension

**Comment by palcisto** [comment]
Confirmed this is an issue.

In https://github.com/jest-community/vscode-jest/issues/347 I stated that the issue was still existing and I would create a new issue, however since @abumalick has already created this issue I've gone ahead and cloned down the sample repo he created and verified it following the steps he outlined.

Specifically in this order:
1. Clone repo
2. `yarn install`
3. `yarn test`
4. Went to VS Code and opened the command palette and ran the comma
`Jest: Start Runner` since vscode-jest did not start the runner on it's own.

For which I received the following result both with line 4 of `App.test.js` commented and un-commented out:
```
FAIL src/App.test.js

  ● Test suite failed to run

    Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/en/configuration.html

    Details:

    SyntaxError: /Users/patrick/Sites/sandbox/vscode-test-cra/src/App.test.js: Unexpected token (8:18)

       6 | it("renders without crashing", () => {
       7 |   const div = document.createElement("div");
    >  8 |   ReactDOM.render(<App />, div);
         |                   ^
       9 |   ReactDOM.unmountComponentAtNode(div);
      10 | });
      11 |

      at Parser.raise (node_modules/@babel/parser/lib/index.js:6400:17)
      at Parser.unexpected (node_modules/@babel/parser/lib/index.js:7728:16)
      at Parser.parseExprAtom (node_modules/@babel/parser/lib/index.js:8940:20)
      at Parser.parseExprSubscripts (node_modules/@babel/parser/lib/index.js:8507:23)
      at Parser.parseMaybeUnary (node_modules/@babel/parser/lib/index.js:8487:21)
      at Parser.parseExprOps (node_modules/@babel/parser/lib/index.js:8353:23)
      at Parser.parseMaybeConditional (node_modules/@babel/parser/lib/index.js:8326:23)
      at Parser.parseMaybeAssign (node_modules/@babel/parser/lib/index.js:8273:21)
      at Parser.parseExprListItem (node_modules/@babel/parser/lib/index.js:9590:18)
      at Parser.parseCallExpressionArguments (node_modules/@babel/parser/lib/index.js:8720:22)


Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        2.18s
Ran all test suites related to changed files.
```

**Comment by connectdotz** [comment]
hmmm... I cloned the demo repo but couldn't reproduce the error... jest has no problem reading the `setupTest.js` and all tests passed, comment or uncomment of https://github.com/abumalick/vscode-test-cra/blob/master/src/App.test.js#L4

@abumalick this plugin doesn't generate its own config, it tries to mimic the way you run jest (in this case, yarn/npm test for CRA). can you turn on the [debug mode](https://github.com/jest-community/vscode-jest#plugin-not-running-as-expect-try-self-diagnosis) and see the exact spawn command used? What is the error you saw? Is it the same as @palcisto ?

@palcisto your error didn't seem to be related to the `setupTest.js`, which tried to load the `MutationObserver`. Are you able to run `yarn test` on the command line? What is your system config,  os/node etc?

**Comment by abumalick** [comment]
okay I will try that, thank you for testing.

**Comment by abumalick** [comment]
@connectdotz  strange, it is passing now. I wonder what happened.
Maybe disabling and enabling the extension changed something.

@palcisto As @connectdotz said, your issue seems not related as the error is different. I would uninstall and reinstall the extension if I was you.

Thank you for your time @connectdotz @palcisto 

I will close the issue as it is now working for me.

**Comment by palcisto** [comment]
@connectdotz I am able to run `yarn test` on the command line. 
This is the 
VS Code 1.39.2
MacOS Catalina 10.15

Version: 1.39.2
Commit: 6ab598523be7a800d7f3eb4d92d7ab9a66069390
Date: 2019-10-15T15:33:00.827Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 19.0.0

**Comment by palcisto** [comment]
@connectdotz uninstalling and re-installing the extension did not work.

I wonder if it could have anything to do with my test script command?
```
"test": "REACT_APP_ENV=beta react-scripts test --env=jsdom",
```

**Comment by palcisto** [comment]
@connectdotz uninstalling and re-installing the vscode-jest extension did not resolve the issue.

**Comment by connectdotz** [comment]
> I wonder if it could have anything to do with my test script command?

@palcisto indeed, from the code [here](https://github.com/jest-community/vscode-jest/blob/7b5f243281aa7ef7cd627a5bd458d1e3b800089f/src/helpers.ts#L51) you can see it try to match against the default  CRA test scripts, i.e. `react-scripts test`. Your test script has a prefix `REACT_APP_ENV=beta` thus the plugin failed to recognize your project as a CRA project.

You should be able to fix this by setting `jest.pathToJest` to `yarn test`. see [here](https://github.com/jest-community/vscode-jest/issues/129#issuecomment-545646441) for more info.

**Comment by palcisto** [comment]
@connectdotz thanks that helped.
