### ISSUE TITLE
Process failed: spawn jest ENOENT

### ISSUE THREAD

**Issue by oliversturm** [jest-community/vscode-jest#516]
### Environment

1. `node -v`: v10.16.3
1. `npm -v`: 6.9.0
1. `npm ls jest` or `npm ls react-scripts` (if you haven’t ejected):

Running from root of monorepo:

```
➜ npm ls jest
jestpluginissue@1.0.0 /home/user/git/jestpluginissue
└── (empty)
```

Running from individual package folder (`packages/pack1`):

```
➜ npm ls jest           
pack1@1.0.0 /home/user/git/jestpluginissue/packages/pack1
└── jest@24.9.0 
```

1. your vscode-jest settings if customized:

Tried to set jest.debugMode to true, but this doesn't change anything.

1. Operating system: Linux

### Prerequisite
- are you able to run jest test from command line? Yes
- how do you run your tests from command line? (for example: `npm run test` or `node_modules/.bin/jest`) `npm run test` (inside a package folder)

### Steps to reproduce

* Clone https://github.com/oliversturm/jestpluginissue
* Run `npm install`
* Run `npm run lerna bootstrap`
* Go to the package folder and run tests:

```
cd packages/pack1
npm run test
```

* Run VS Code in the root  folder
* Try to activate the Jest Runner

### Relevant Debug Info

My setup is a monorepo with lerna. Jest is installed in individual projects inside `packages`. Pretty standard setup, I think. In each package.json, I have this:

```
  "scripts": {
    "test": "jest",
    "test-watch": "jest --watch"
  },
```

### Expected Behavior

Jest runner works in VS Code

### Actual Behavior

Output shows this:

```
Exception raised: Process failed: spawn jest ENOENT
Finished running all tests. Starting watch mode.

Exception raised: Process failed: spawn jest ENOENT

Exception raised: Process failed: spawn jest ENOENT

Exception raised: Process failed: spawn jest ENOENT

Exception raised: Process failed: spawn jest ENOENT

Exception raised: Process failed: spawn jest ENOENT
Starting Jest in Watch mode failed too many times and has been stopped.
 see troubleshooting: https://github.com/jest-community/vscode-jest/blob/master/README.md#troubleshooting
```

As I said above, I tried switching on `jest.debugMode`, but this doesn't make any difference to the output.

**Comment by oliversturm** [comment]
I made things work for me by using `--hoist` with the `lerna bootstrap` command. This probably makes sense for my setup anyway, so I don't mind. I'm leaving this issue open for the time being because my understanding from the docs was that multi-project workspaces should be supported out of the box and I didn't find this to be the case for my original setup.

**Comment by connectdotz** [comment]
> my understanding from the docs was that multi-project workspaces should be supported out of the box

Looks like we definitely need to update the doc soon. This plugin attempt to "guess" how developers run their tests, the main use cases it covered, out of the box, are:
1. run simple `jest` from the root project, where jest resides in node_modules or is installed globally
2. as a typical non-ejected react project, i.e. created by create-react-app.

while this covered many projects, it will most likely not able to cover the more sophisticated projects such as the monorepo projects, which can use settings like `jest.pathToJest` to customize jest location or adopt vscode's [multi-root-workspaces](https://code.visualstudio.com/docs/editor/multi-root-workspaces) that treats each child-package as a separate folder...

**Comment by connectdotz** [comment]
close as this is resolved by auto fallback to login shell
