### ISSUE TITLE
`branch.end.column` value is sometimes `null`

### ISSUE THREAD

**Issue by garyking** [jest-community/vscode-jest#524]
### Environment

1. `node -v`: v12.12.0
1. `npm -v`: 6.13.1
1. `npm ls jest` or `npm ls react-scripts` (if you haven’t ejected): 24.9.0
1. your vscode-jest settings if customized:
    - jest.pathToJest? `node_modules/jest/bin/jest.js --coverage --runInBand --watchAll`

1. Operating system: macOS 10.14.6

### Prerequisite
- are you able to run jest test from command line? Yes
- how do you run your tests from command line? (for example: `npm run test` or `node_modules/.bin/jest`) `yarn run test`

### Steps to Reproduce

Sample repo: https://github.com/garyking/vscode-jest-bug-sample-repo

All relevant info can be found in this PR: https://github.com/jest-community/vscode-jest/pull/519

**Comment by seanpoulter** [comment]
Did #519 resolve this issue @garyking?

**Comment by garyking** [comment]
@seanpoulter Yes #519 fixed the problem for me. But @connectdotz said they [wanted me](https://github.com/jest-community/vscode-jest/pull/519#issuecomment-556906103) to open an issue to track this, since this doesn't actually [fix the root issue](https://github.com/jest-community/vscode-jest/pull/519#issuecomment-555834028).

**Comment by seanpoulter** [comment]
Thank you for the clarification **and** bug fix! 👏  I had skimmed the conversation in #519 and missed that.
