### ISSUE TITLE
Output does not expand to the complete output in test Summary

### ISSUE THREAD

**Issue by distante** [jest-community/vscode-jest#525]
### Environment

1. `node -v`: v12.13.0
1. `npm -v`: 6.12.1
1. `npm ls jest` or `npm ls react-scripts` (if you haven’t ejected): 
1. Vscode 1.40.1
```
my-project@0.0.1 C:\_SSD_DEV\ionic\my_project
`-- jest@24.9.0 
```
1. your vscode-jest settings if customized:
    - jest.pathToJest? `npm run test --  --silent --coverage --watchAll`
    - jest.pathToConfig? `./jest.config.js`
    - anything else that you think might be relevant? 

jest.config.js
```
module.exports = {
  preset: 'jest-preset-angular',
  setupFilesAfterEnv: ['<rootDir>/src/setupJest.ts'],
  transformIgnorePatterns: ['<rootDir>/node_modules/(?!@ionic|@saninn|@ngrx)'],
  coverageReporters: process.env.CI ? ['text'] : ['lcov'],
  coveragePathIgnorePatterns: ['/node_modules/', 'package.json', '<rootDir>/src/test.ts', './manual-plugins/'],
  testPathIgnorePatterns: ['/node_modules/', './src/test.ts', './plugins/', '<rootDir>/coverage/', './manual-plugins/'],
  modulePathIgnorePatterns: ['<rootDir>/coverage/', '<rootDir>/plugins/'],
  collectCoverage: true,
  coverageDirectory: './coverage',
  collectCoverageFrom: ['.src/**/*.ts']
};
```

1. Operating system: Windows 10

### Prerequisite
- are you able to run jest test from command line? Yes
- how do you run your tests from command line?  `npm run test --  --silent --coverage --watchAll`

### Expected Behavior
Jest output text should be visible in the complete width of the output tab in VScode

### Actual Behavior
Output is truncated in several parts
![image](https://user-images.githubusercontent.com/5490201/69493736-a9905f00-0eb2-11ea-9912-299996b34778.png)

It happens just for the Summary part, the first output is correctly rendered.

![image](https://user-images.githubusercontent.com/5490201/69493855-50292f80-0eb4-11ea-9cd0-1779e53465d1.png)

**Comment by connectdotz** [comment]
can you create a sample repo to help us diagnose?

**Comment by grit96** [comment]
I also encounter this issue. It happens with any jest project.

**Comment by tskimmett** [comment]
Just wanted to say we've been encountering the same problem. Funnily enough it seems to only mangle the output for test failures (ironically the most important part).
![image](https://user-images.githubusercontent.com/4603206/89047276-33cf7380-d31c-11ea-90ce-0a843cd2a7ba.png)

**Comment by connectdotz** [comment]
this should be addressed by TestExplorer's output terminal
