### ISSUE TITLE
Jest fails to spawn when the project directory includes a space in one of the folders

### ISSUE THREAD

**Issue by MatthiasDurivet** [jest-community/vscode-jest#529]
### Environment

1. `node -v`: 10.16.3
1. `npm -v`: 6.11.3
1. `npm ls jest` or `npm ls react-scripts` (if you haven’t ejected): 
/home/matthias/Documents/coding Training/adventOfCode/intCodeComputer
└── jest@24.9.0

1. Operating system: ubuntu 18.04

### Prerequisite
- are you able to run jest test from command line? yesy
- how do you run your tests from command line?`npm run test`

### Steps to Reproduce

My directory had a space in one of the folder names: "coding Training"

### Expected Behavior

Show visual representation of the tests in VS-code side panel

### Actual Behavior

Error with cannot spawn jest in watch mode

### Solution

After removing the space the plugin worked fine
Handling the directory paths as strings may solve the problem eniterly

**Comment by MatthiasDurivet** [comment]
The workaround is easy but would be nice to fix this entirely.

**Comment by patveck** [comment]
My understanding is that this has already been fixed upstream in jest-community/jest-editor-support#21. vscode-jest upgraded jest-editor-support to the latest version about three weeks ago in its package.json, but apparently, this hasn't been published yet. I cloned this repo and installed vscode-jest from the clone and can confirm that it works.

**Comment by connectdotz** [comment]
[v3.1.0](https://github.com/jest-community/vscode-jest/releases/tag/v3.1.0) is out and should address this issue, feel free to give it a try...

**Comment by connectdotz** [comment]
this should be addressed in [v3.1.0](https://github.com/jest-community/vscode-jest/releases/tag/v3.1.0), feel free to reopen if not...
