### ISSUE TITLE
How to run test cases of only the file currently being edited. 

### ISSUE THREAD

**Issue by meharajM** [jest-community/vscode-jest#530]
### Environment

1. `node -v`: [fill]
1. `npm -v`: [fill]
1. `npm ls jest` or `npm ls react-scripts` (if you haven’t ejected): [fill]
1. your vscode-jest settings if customized:
    - jest.pathToJest? [fill]
    - jest.pathToConfig? [fill]
    - anything else that you think might be relevant? [fill]

1. Operating system: [fill]

### Prerequisite
- are you able to run jest test from command line? [fill]
- how do you run your tests from command line? (for example: `npm run test` or `node_modules/.bin/jest`) [fill]

### Steps to Reproduce

[fill]

### Relevant Debug Info

[fill]

### Expected Behavior

[fill]

### Actual Behavior

[fill]

--- 

The fastest (and the most fun) way to resolve the issue is to submit a pull-request yourself. If you are interested, feel free to check out the [contribution guide](https://github.com/jest-community/vscode-jest/CONTRIBUTING.md), we look forward to seeing your PR...

**Comment by connectdotz** [comment]
this extension runs your test in 2 phase:
1. upon starting, it will do a full jest run for all of your tests 
1. followed by starting jest in watch mode, which will only run tests that changed.

You can use `"jest.runAllTestsFirst": false`to skip the first full test run.

**Comment by raphaelbs** [comment]
@connectdotz I'm working in a huge project whereas running Jest in all files takes forever (and often freezes the PC).
Is possible to run only on the currently opened test file?

**Comment by connectdotz** [comment]
> Is possible to run only on the currently opened test file?

In theory, once you turned off the `jest.runAllTestsFirst`, jest should only run the tests that "changed". However, if you want to run the files opened, regardless if they are changed, which sounded like an 'on-demand" testing... such feature doesn't exist yet... although I can see it could be useful for some use case... PR is welcome.

**Comment by connectdotz** [comment]
This is possible now,  please feel free to give [v4.0.0-alpha.5](https://github.com/jest-community/vscode-jest/releases/tag/v4.0.0-alpha.5) a try and let us know if it works for you.

**Comment by raphaelbs** [comment]
@connectdotz How can I install this alpha version?

The last one that shows up for me is the `3.2.0`
![image](https://user-images.githubusercontent.com/11169832/113639204-0bd4a480-964f-11eb-8b5a-eaf6980de0c2.png)

**Comment by connectdotz** [comment]
@raphaelbs it's not officially released in the marketplace yet, but you can install it using the VSIX file, please see **"How to test"** section in [v4.0.0-alpha.5](https://github.com/jest-community/vscode-jest/releases/tag/v4.0.0-alpha.5) release note.

**Comment by dilraj-vidyard** [comment]
For those that didn't get it, try adding this to the `User/settings.json`


```js
    "jest.runMode": {
        "testFileOnly": true,
        "runAllTestsOnStartup": false,
        "type": "on-save"
    }
```
