### ISSUE TITLE
Jest Sample Test Fails in VSCode on new Nest.js Project

### ISSUE THREAD

**Issue by mindjuice** [jest-community/vscode-jest#534]
### Environment

1. `node -v`: v13.3.0
1. `npm -v`: 6.13.4
1. `npm ls jest` or `npm ls react-scripts` (if you haven’t ejected):
jestteest@0.0.1 /Users/me/dev/jesttest
└── jest@24.9.0

1. your vscode-jest settings if customized:
    - jest.pathToJest? Default
    - jest.pathToConfig? Default
    - anything else that you think might be relevant?

`jest` settings from my `package.json`:

  ```
"jest": {
    "moduleFileExtensions": [
      "js",
      "json",
      "ts"
    ],
    "rootDir": "src",
    "testRegex": ".spec.ts$",
    "transform": {
      "^.+\\.(t|j)s$": "ts-jest"
    },
    "coverageDirectory": "../coverage",
    "testEnvironment": "node"
  }
```

1. Operating system: Mac OS X version 10.13.6

### Prerequisite
- are you able to run jest test from command line? Yes, and the sample test passes
- how do you run your tests from command line? (for example: `npm run test` or `node_modules/.bin/jest`): `yarn run test` (the `package.json` script line is `"test": "jest",`)

### Steps to Reproduce

```
npm i -g @nestjs/cli
nest new mytest
```

### Expected Behavior
The sample unit test in `src/app.controller.spec.ts` should pass when run in vscode.

### Actual Behavior
The test fails with the following error:

```
FAIL src/app.controller.spec.ts

  ● Test suite failed to run

    Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/en/configuration.html

    Details:

    /Users/kencr2000/dev/euclid/jestteest/src/app.controller.spec.ts:8
        beforeEach(async () => {
                         ^
    SyntaxError: Unexpected token (

      at ScriptTransformer._transformAndBuildScript (../node_modules/@jest/transform/build/ScriptTransformer.js:537:17)
      at ScriptTransformer.transform (../node_modules/@jest/transform/build/ScriptTransformer.js:579:25)


Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        0.76s
Ran all test suites related to changed files.
```

**Comment by mindjuice** [comment]
I tried changing my `tsconfig.json` `target` setting from `es2017` to `es2015`, but that gave a similar error in the `nest` `node_modules` code.

**Comment by stephtr** [comment]
Hm, I just ran
```
npm i -g @nestjs/cli
nest new mytest
```
and the resulting project didn't have any issues on VS Code. Maybe someone using Linux could double check it?

**Comment by mindjuice** [comment]
Hmmm...ok.  I can try it tonight on both another Mac and in a Linux VM.

**Comment by mindjuice** [comment]
I tried it on my other Mac using the same node version and it worked.

I did some digging on my original system and found an ancient version of `node@0.8.4` that had been installed via `brew`.  This hadn't been interfering with anything else, but after removing it, the test passed on this system too.

Thanks for testing it out!  Much appreciated!
