### ISSUE TITLE
Goto test output option

### ISSUE THREAD

**Issue by zssng** [jest-community/vscode-jest#548]
### Environment

1. `node -v`: [v10.16.3]
1. `npm -v`: [6.9.0]
1. `npm ls jest` or `npm ls react-scripts` (if you haven’t ejected): [fill]
1. your vscode-jest settings if customized:
    - jest.pathToJest? [fill]
    - jest.pathToConfig? [fill]
    - anything else that you think might be relevant? [fill]

1. Operating system: [windows 10]

### Prerequisite
- are you able to run jest test from command line? [fill]
- how do you run your tests from command line? (for example: `npm run test` or `node_modules/.bin/jest`) [fill]

### Steps to Reproduce

[fill]

### Relevant Debug Info

[fill]

### Expected Behavior

provide content menu option to indirect to test output (console.log etc).We have to rerun failed test to see actual output at present,(may be wrong)

### Actual Behavior

[fill]

--- 

The fastest (and the most fun) way to resolve the issue is to submit a pull-request yourself. If you are interested, feel free to check out the [contribution guide](https://github.com/jest-community/vscode-jest/CONTRIBUTING.md), we look forward to seeing your PR...

**Comment by seanpoulter** [comment]
That's a great idea @zssng. Want to help add that feature? I'd suggest checking the VS Code API docs to see if it's possible to scroll to a certain point in the output.

**Comment by connectdotz** [comment]
this should be addressed by v5 output terminal.
