### ISSUE TITLE
additional command line parameters

### ISSUE THREAD

**Issue by xenoterracide** [jest-community/vscode-jest#556]
we have an issue in our codebase, which I'm pretty sure is caused by firebase, but a single test doesn't exit properly, then  have to kill it. adding `--forceExit` to the command line seems to fix this, but I see no way to add this in this plugin.

**Comment by connectdotz** [comment]
hmmm... you should be able to do this by customizing the `jest.pathToJest` in your `.vscode/settings.json` file. Basically you can instruct this extension to run whatever jest command you want with this setting, for example, to run you test script in package.json, which has the `--forceExit` flag, you can just set`"jest.pathToJest": yarn test`  or run jest directly: `"jest.pathToJest": xxx/node_modules/.bin/jest --forceExit`

**Comment by connectdotz** [comment]
close as staled issue
