### ISSUE TITLE
Option to run always with `--watchAll` instead of `--watch`

### ISSUE THREAD

**Issue by lordofthelake** [jest-community/vscode-jest#558]
### Environment

1. `node -v`: v12.13.1
1. `npm -v`: 6.13.6
1. Operating system: macOS Mojave

### Prerequisite
- are you able to run jest test from command line? Only using `--watchAll`
- how do you run your tests from command line? (for example: `npm run test` or `node_modules/.bin/jest`) `pnpx jest --watchAll`

### Steps to Reproduce

In a monorepo using git submodules and a multi-project setup (`jest.config.js` in the root using the `projects` option to run the test suites of all packages), running Jest in watch mode (`jest --watch`) always errors out with something along the lines of:

```
Determining test suites to run...

  ● Test suite failed to run

    fatal: ../packages/a-dependency-outside-the-submodule: '../packages/a-dependency-outside-the-submodule' is outside repository
```

This is a variant of [a known Jest issue](https://github.com/facebook/jest/issues/4419), and the usual workaround is to run Jest with `--watchAll` instead of `--watch`.

vscode-jest aways errors out, though, because it tries to use `--watch` and there is no way (that I could find) for force it to run Jest with `--watchAll`.

### Expected Behavior

I would like to have an option to run Jest with vscode-jest using `watchAll` instead of `watch`, or having the extension detect this kind of error and behave accordingly.

**Comment by connectdotz** [comment]
looks like there is code attempted to detect such situation [here](https://github.com/jest-community/vscode-jest/blob/25394c83e21c04f12f8cb4289db3178b1d3162a8/src/Jest/index.ts#L7), is that not working for your use case or maybe the regex is outdated or too rigid... want to give it a try to fix it?

**Comment by lordofthelake** [comment]
@connectdotz I took a super quick stab at it. I see the build failing, but from the log it seems like Danger is having some trouble posting its comment (and is lying about the email addresses not being verified) – any insight about that?
