### ISSUE TITLE
Set NODE_PATH before launching jest.js to debug

### ISSUE THREAD

**Issue by orokanasaru** [jest-community/vscode-jest#563]
When running normally, jest/jest.cmd set `NODE_PATH` before launching jest.js with node. 
vscode-jest launches jest.js directly without setting `NODE_PATH`, which can lead to dependencies not being resolved during test execution. 
This prevents the ability to debug tests.
Please set `NODE_PATH` before launching jest.js to debug.

### Environment

1. `node -v`: v10.15.0
1. `npm -v`: 6.4.1
1. `npm ls jest` or `npm ls react-scripts` (if you haven’t ejected): jest@25.1.0

1. Operating system: Windows

### Prerequisite
- are you able to run jest test from command line? yes
- how do you run your tests from command line? (for example: `npm run test` or `node_modules/.bin/jest`) `npm run test`

### Steps to Reproduce

Will create repo later if needed.

### Relevant Debug Info

N/A

### Expected Behavior

Tests run under the same environment during debug as they do under normal runs.

### Actual Behavior

`NODE_PATH` isn't set and jest may not be able to resolve dependencies when debugging.

--- 

The fastest (and the most fun) way to resolve the issue is to submit a pull-request yourself. If you are interested, feel free to check out the [contribution guide](https://github.com/jest-community/vscode-jest/CONTRIBUTING.md), we look forward to seeing your PR...

**Comment by connectdotz** [comment]
if you run test with `npm run test`, should set the `jest.pathToJest` to  the same...

**Comment by orokanasaru** [comment]
Unfortunately, that does not actually help in this situation.

From the readme:

> In contrast to previous versions of this plugin the debug settings are now independent from VS Code's `jest.pathToJest` and `jest.pathToConfig` setting. If you had to modify one of these, you pretty surely have to create a custom debug configuration and modify its path.

Setting the path in the debug configuration also does not work as this is a case of different behavior between `node_modules/.bin/jest.cmd` and `node_module/jest/bin/jest`.
VS Code will try to run the path with `node.exe` and node doesn't understand `cmd` files.

Investigating further, this is a `pnpm` specific issue. 
`pnpm` edits the files in `.bin` to add `NODE_PATH` to enable node to resolve all the symlinks it sets up.

To anyone hitting this in the future, the solution is to add a custom configuration in `launch.json` that sets `NODE_PATH` to whatever `pnpm` put in the `jest.cmd` file.

After the investigation, the issue appears to be rather external to this extension, so I'm closing it.
