### ISSUE TITLE
Spaces in project path not supported

### ISSUE THREAD

**Issue by stesee** [jest-community/vscode-jest#569]
### Environment

1. `node -v`: v12.16.1
1. `npm -v`: 6.13.4
1. `npm ls jest` or `npm ls react-scripts` (if you haven’t ejected): office-addin-taskpane-react@0.0.1 C:\dev\1\2\3\Bla blub
1. your vscode-jest settings if customized:
    - jest.pathToJest? no
    - jest.pathToConfig? no
    - anything else that you think might be relevant? [fill]

1. Operating system: Windows 10

### Prerequisite
- are you able to run jest test from command line? yes
- how do you run your tests from command line? (for example: `npm run test` or `node_modules/.bin/jest`) both work

### Steps to Reproduce

Just rename any exisiting project directory and put a space anywehere -> broken

Workarround - add to settings.json
```Json
"jest.pathToJest": "npm run test --"
```

### Expected Behavior

vscode-jest should support projects with spaces in their path without workarround.

### Actual Behavior

vscode-jest writes multiple times
```
'"jest.cmd"' is not recognized as an internal or external command,
operable program or batch file.
```
before "Starting Jest in Watch mode failed too many times and has been stopped."

--- 

The fastest (and the most fun) way to resolve the issue is to submit a pull-request yourself. If you are interested, feel free to check out the [contribution guide](https://github.com/jest-community/vscode-jest/CONTRIBUTING.md), we look forward to seeing your PR...

**Comment by connectdotz** [comment]
can you turn on the debug mode and paste the spawned command here?

**Comment by stesee** [comment]
hm... behaviour is no longer reproducible -> Closed

node -v: v12.16.1

npm -v: 6.13.4

Used this steps:
1. Installed https://marketplace.visualstudio.com/items?itemName=Orta.vscode-jest
2. Created "c:\temp\Something WithSpace"
3. https://jestjs.io/docs/en/getting-started
4. Worked 🤷‍♂️
