### ISSUE TITLE
Processes keep spawning/Stop runner not stopping all processes

### ISSUE THREAD

**Issue by DavidLyhedDanielsson** [jest-community/vscode-jest#578]
### Environment

1. `node -v`: 12.14.1
2. `npm -v`: 6.14.2
3. `npm ls jest`:
```
test@1.0.0 /home/david/testdir
└── jest@25.5.0
```
4. vscode-jest settings unchanged
5. Operating system: Ubuntu 18.04.4

### Prerequisite
- are you able to run jest test from command line? Yes
- how do you run your tests from command line? npm run test/npm test. package.json script: `"test": "jest --colors --coverage",`

### Steps to Reproduce

1. Create a new, empty, directory
2. Add the following package.json and install:
```
{
  "name": "test",
  "version": "1.0.0",
  "scripts": {
    "test": "jest --colors --coverage"
  },
  "dependencies": {
    "@types/jest": "^25.2.1",
    "jest": "^25.5.0"
  }
}
```
3. Add `__tests__` directory with following file named test.js:
```
describe('test', () => {
  it('should pass', () => {
    expect(1).toEqual(1);
  });
});
```
4. Jest runner starts automatically now, or when I reload the window
5. Run `ps aux | grep jest` which yields:
```
david     4059  0.0  0.0   4624   812 ?        S    12:25   0:00 /bin/sh -c "/home/david/testdir/node_modules/.bin/jest" --testLocationInResults --json --useStderr --outputFile /tmp/jest_runner_testdir.json --watch --no-coverage --no-color --reporters default --reporters "/home/david/.vscode/extensions/orta.vscode-jest-3.1.1/out/reporter.js"
david     4060  180  0.7 936620 127364 ?       Rl   12:25   0:01 node /home/david/testdir/node_modules/.bin/jest --testLocationInResults --json --useStderr --outputFile /tmp/jest_runner_testdir.json --watch --no-coverage --no-color --reporters default --reporters /home/david/.vscode/extensions/orta.vscode-jest-3.1.1/out/reporter.js
david     4118  0.0  0.0  23072  1104 pts/5    S+   12:25   0:00 grep --color=auto --exclude-dir=.bzr --exclude-dir=CVS --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn jest
```
6. Run `Jest: Stop Runner` command
7. Run `ps aux | grep jest` which yields:
```
david     4060  3.2  0.7 933288 120520 ?       Sl   12:25   0:04 node /home/david/testdir/node_modules/.bin/jest --testLocationInResults --json --useStderr --outputFile /tmp/jest_runner_testdir.json --watch --no-coverage --no-color --reporters default --reporters /home/david/.vscode/extensions/orta.vscode-jest-3.1.1/out/reporter.js
david     7034  0.0  0.0  23072  1052 pts/5    S+   12:27   0:00 grep --color=auto --exclude-dir=.bzr --exclude-dir=CVS --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn jest
```
8. Run `Jest: Start Runner` command OR reload window OR seemingly write tests for a while, i.e. create/delete/modify file
9. Run `ps aux | grep jest` which yields:
```
david     4060  2.5  0.7 933288 120520 ?       Sl   12:25   0:04 node /home/david/testdir/node_modules/.bin/jest --testLocationInResults --json --useStderr --outputFile /tmp/jest_runner_testdir.json --watch --no-coverage --no-color --reporters default --reporters /home/david/.vscode/extensions/orta.vscode-jest-3.1.1/out/reporter.js
david     7874  0.0  0.0   4624   856 ?        S    12:28   0:00 /bin/sh -c "/home/david/testdir/node_modules/.bin/jest" --testLocationInResults --json --useStderr --outputFile /tmp/jest_runner_testdir.json --watch --no-coverage --no-color --reporters default --reporters "/home/david/.vscode/extensions/orta.vscode-jest-3.1.1/out/reporter.js"
david     7875  185  0.8 953944 135188 ?       Rl   12:28   0:01 node /home/david/testdir/node_modules/.bin/jest --testLocationInResults --json --useStderr --outputFile /tmp/jest_runner_testdir.json --watch --no-coverage --no-color --reporters default --reporters /home/david/.vscode/extensions/orta.vscode-jest-3.1.1/out/reporter.js
david     7925  0.0  0.0  23072  1088 pts/5    S+   12:28   0:00 grep --color=auto --exclude-dir=.bzr --exclude-dir=CVS --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn jest
```
### Relevant Debug Info

Loading vscode with debug enabled outputs:
```
[Extension Host] spawning process with command="/home/david/testdir/node_modules/.bin/jest" --testLocationInResults --json --useStderr --outputFile /tmp/jest_runner_testdir.json --no-coverage --no-color --reporters default --reporters "/home/david/.vscode/extensions/orta.vscode-jest-3.1.1/out/reporter.js"
[Extension Host] spawning process with command="/home/david/testdir/node_modules/.bin/jest" --testLocationInResults --json --useStderr --outputFile /tmp/jest_runner_testdir.json --watch --no-coverage --no-color --reporters default --reporters "/home/david/.vscode/extensions/orta.vscode-jest-3.1.1/out/reporter.js"
```
### Expected Behavior

I expect:
1. Running `Stop Runner` command should stop running jest tests
1. A single process to be spawned, unless it is intended behaviour to spawn multiple ones
1. Performance not to degrade over time

### Actual Behavior

1. Even after running `Stop Runner` command, saving the file will make jest run the tests again. Probabaly because of the next actual behaviour
1. As you can from the steps above, even after stopping the jest runner, `ps aux` shows me there are still processes up listening for changes
1. After a while of writing tests/code, a bunch of processes have spawned, all of which will run my tests when the file is saved. This makes my computer slow, and makes the fan go to 100% for a few seconds

I can stop the runner, manually kill processes, and then starts the runner back up and everything is fine and works as it should

**Comment by connectdotz** [comment]
hi @DavidLyhedDanielsson this is probably related to #550, we have a release candidate that should fix this issue. Can you can let us know if it works for you (see more in [comment](https://github.com/jest-community/vscode-jest/issues/550#issuecomment-620280415)) ?

**Comment by DavidLyhedDanielsson** [comment]
Wow, that looks exactly right. I looked through all the open issues and did some searching, but I guess I didn't search hard enough... I will try it first thing in the morning! Really happy to hear it might have been fixed

**Comment by DavidLyhedDanielsson** [comment]
Quick testing and it seems like it works with 3.2.0 :tada: I'll keep testing it and if I find issues I guess I'll make another issue
