### ISSUE TITLE
GutterFormatter images are not in build

### ISSUE THREAD

**Issue by markcarroll** [jest-community/vscode-jest#585]
### Environment

1. `node -v`: v12.16.1
1. `npm -v`: 6.14.5
1. `npm ls jest` or `npm ls react-scripts` (if you haven’t ejected): jest@26.0.1
1. your vscode-jest settings if customized:
    - jest.pathToJest? default
    - jest.pathToConfig? default
    - anything else that you think might be relevant? see below

1. Operating system: macOS 10.15.4

### Prerequisite
- are you able to run jest test from command line? yes
- how do you run your tests from command line? (for example: `npm run test` or `node_modules/.bin/jest`) jest (with npx fallback)

### Steps to Reproduce

Turn on GutterFormatter in vscode settings

### Relevant Debug Info

VSCode fails to load the SVG images used in the gutter formatter. It is trying to load them from:

> Request URL: file:///Users/mark/.vscode/extensions/orta.vscode-jest-3.2.0/src/Coverage/Formatters/GutterFormatter/partially-covered-gutter-icon.svg

That folder is not present in extension folder. 

### Expected Behavior

Gutter images load. 

### Actual Behavior

Error as listed above. 

--- 

The fastest (and the most fun) way to resolve the issue is to submit a pull-request yourself. If you are interested, feel free to check out the [contribution guide](https://github.com/jest-community/vscode-jest/CONTRIBUTING.md), we look forward to seeing your PR...

**Comment by Tymek** [comment]
I'll take a shot at it. My first guess is that `raw-loader` or something like that can help. We'll see
