### ISSUE TITLE
[Feature Request] add test list (with status) in a left bar icon

### ISSUE THREAD

**Issue by distante** [jest-community/vscode-jest#595]
In this bar an icon could be added:
![image](https://user-images.githubusercontent.com/5490201/84186955-a09f5d80-aa91-11ea-85dd-7ab0c2d12dcf.png)

It can open a panel with the list of the current tests and their status (passing, failing) similar at what
webstorm generates:
![image](https://user-images.githubusercontent.com/5490201/84187030-bc0a6880-aa91-11ea-9927-1df0220213ac.png)

where when someone double clicks on a test name, the cursor goes to that test (not just for failing tests).

**Comment by distante** [comment]
I found this, maybe it could be used: https://github.com/dfcowell/vscode-jest-test-adapter

**Comment by Agalin** [comment]
Integration with Test Explorer seems to be the way to go. Python extension (maintained by Microsoft itself) seems to use it internally (i.e. provides same functionality and UI as Test Explorer but without installing it - and without colliding with it if installed) so it can be considered soemwhat of a standard in VSCode..

**Comment by Tymek** [comment]
@distante no code there. just template with right name. You can find real deal here: 
- https://marketplace.visualstudio.com/items?itemName=kavod-io.vscode-jest-test-adapter
- https://github.com/kavod-io/vscode-jest-test-adapter

it works and seem to have some active development

**Comment by distante** [comment]
> @distante no code there. just template with right name. You can find real deal here: 
> - https://marketplace.visualstudio.com/items?itemName=kavod-io.vscode-jest-test-adapter
> - https://github.com/kavod-io/vscode-jest-test-adapter
> 
> it works and seem to have some active development
> 
> ![Screenshot from 2020-07-02 11-19-10](https://user-images.githubusercontent.com/2625371/86340928-e5b04d00-bc55-11ea-9f1a-590a5d152c55.png)
> 

OH, sorry, I just saw it in a blog post about another thing and I saved the link so I could share it here.

**Comment by j-m** [comment]
Duplicates #402

**Comment by connectdotz** [comment]
closed as vscode has provided a native TestExplorer
