### ISSUE TITLE
[Feature Request?] Publish to the Open-VSX registry

### ISSUE THREAD

**Issue by KartikSoneji** [jest-community/vscode-jest#602]
Can this extension be published to the Open VSX registry as well?

Open VSX registry: https://open-vsx.org/
How to Publish an Extension: https://github.com/eclipse/openvsx/wiki/Publishing-Extensions

**Comment by jankeromnes** [comment]
Great idea! Friendly ping @orta 😇 🙏

**Comment by orta** [comment]
Ah yeah, sorry - I'm not actively maintaining this (other folks are) but if it needs me saying this is a good idea, then this is a good idea 👍🏻

**Comment by jankeromnes** [comment]
Awesome, thanks @orta! (Note: I asked you because you've also published [svelte.svelte-vscode](https://open-vsx.org/extension/svelte/svelte-vscode) and [svelte.svelte-vscode-nightly](https://open-vsx.org/extension/svelte/svelte-vscode-nightly) to OpenVSX -- many thanks for that! 💯)

@connectdotz or @stephtr would you be interested in publishing `vscode-jest` to OpenVSX? This would allow users from VSCodium, Gitpod, Theia, etc. to also use it. (Let me know if I can help!)

**Comment by connectdotz** [comment]
sorry slow to respond, yes we should publish there, I will try to do it this weekend

**Comment by connectdotz** [comment]
@orta this package is published under publisher = "Orta", which will also be the namespace in open-vsx. For security reason, we should claim the ownership of the namespace. But I wasn't sure if you have any other repo under "Orta"...

We should probably rename the publisher to `jest-community` at some point, what do you think? However, doing so in vscode is sort of tricky, especially given our install base. I see a few approaches and would like you to weight in:

1. hold off open-vsx publication until we rename the publisher in vscode
2. if you don't have any other packages under Orta namespace, we can claim and publish as "Orta" in open-vsx for now and change it to the new namespace later.
3. you can claim "Orta" namespace, grant us permission, either you or us can then publish under Orta. We can change to new namespace later.

**Comment by orta** [comment]
I have a bunch of extensions, so I can't really rename my vscode org.

I can claim the open namespace and put a token in the secret vault for this repo, then a deploy can automatically happen from here via a GH action?

**Comment by connectdotz** [comment]
> I can claim the open namespace and put a token in the secret vault for this repo, then a deploy can automatically happen from here via a GH action?

It makes sense for you to claim the namespace. 

However, we have not been using GH action in this repo yet, not that we can not set it up, just that it is not the current procedure... (Personally I prefer manual publication so we can better control the timing and quality)

If you add us as Contributors in open-vsx namespace (see [here](https://github.com/eclipse/openvsx/wiki/Namespace-Access#how-to-manage-namespace-members)) then we can publish to it with our own token, I think it is more secure and accountable for each release publisher to use their own token anyway. Does that make sense?

**Comment by orta** [comment]
Perfect 👍🏻

**Comment by orta** [comment]
Alright, that's everything I think

**Comment by connectdotz** [comment]
Thanks, @orta. 

ok, both 3.2.0 and 4.0.0-alpha.1 are published: https://open-vsx.org/extension/Orta/vscode-jest

@jankeromnes please let me know if there is any issue with it.

**Comment by jankeromnes** [comment]
That's awesome, many thanks @connectdotz and @orta! 💯 🙏

The uploaded extensions look good to me. 👍 (However, given that `4.0.0-alpha.1` is now the latest available version on OpenVSX, please note that this will be the default version that all users get when installing this extension in VSCodium, Gitpod, Theia, etc.)

**Comment by connectdotz** [comment]
hmm... is there a way to publish pre-release?

**Comment by jankeromnes** [comment]
> hmm... is there a way to publish pre-release?

@connectdotz In theory, I think you can mark an extension as `preview` in its `package.json`, and then all marketplaces (e.g. OpenVSX) and tools (e.g. VSCodium) should always propose the latest non-preview version by default.

But I know that some extension authors prefer to publish with separate IDs and logos in order to avoid any potential confusion, like for example [svelte.svelte-vscode](https://open-vsx.org/extension/svelte/svelte-vscode) vs [svelte.svelte-vscode-nightly](https://open-vsx.org/extension/svelte/svelte-vscode-nightly).

**Comment by borisyordanov** [comment]
@connectdotz The open-vsx version of the extension is quite old now. Can we get an update? Is there any way we can make it automatic?

**Comment by connectdotz** [comment]
indeed... will look into it soon

**Comment by connectdotz** [comment]
ok, [4.2.1](https://github.com/jest-community/vscode-jest/releases/tag/v4.2.1) has been published. I will make sure the subsequent releases to be published to both registries...

**Comment by connectdotz** [comment]
@jankeromnes does open-vsx support the new [pre-release](https://code.visualstudio.com/updates/v1_63#_pre-release-extensions) feature in vscode? If I publish a vsix file builded with `--pre-release` flag, will VSCodium treat it like vscode, i.e. not to automatically upgrade unless the user explicitly ask for it?

**Comment by jankeromnes** [comment]
@connectdotz That's an excellent question!

I don't think this is currently supported by OpenVSX, so I filed a feature request: https://github.com/eclipse/openvsx/issues/386

Please feel free to subscribe to that issue for updates, fixes, or potential workarounds.

**Comment by 6uliver** [comment]
> ok, [4.2.1](https://github.com/jest-community/vscode-jest/releases/tag/v4.2.1) has been published. I will make sure the subsequent releases to be published to both registries...

Can you publish the latest version? 4.2.1 was the last release published to OpenVSX.

**Comment by connectdotz** [comment]
@6uliver Sorry that I forgot to sync the OpenVSX. The latest 5.2.2 is published now.

**Comment by 6uliver** [comment]
> @6uliver Sorry that I forgot to sync the OpenVSX. The latest 5.2.2 is published now. Let me know if you didn't see it.

Great, thank you very much!
