### ISSUE TITLE
Tests with double quotes in the name are skipped

### ISSUE THREAD

**Issue by gasparsigma** [jest-community/vscode-jest#608]
### Environment

1. `node -v`: 10.22.0
1. `npm -v`: 6.14.6
1. `npm ls jest` or `npm ls react-scripts` (if you haven’t ejected): jest@26.1.0
1. your vscode-jest settings if customized: Default config from vscode to jest-tests
```
{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "type": "node",
      "name": "vscode-jest-tests",
      "request": "launch",
      "args": [
        "--runInBand"
      ],
      "cwd": "${workspaceFolder}",
      "console": "integratedTerminal",
      "internalConsoleOptions": "neverOpen",
      "disableOptimisticBPs": true,
      "program": "${workspaceFolder}/node_modules/jest/bin/jest"
    }
  ]
}
```

5. Operating system: Windows 10

### Prerequisite
- are you able to run jest test from command line? Yes
- how do you run your tests from command line? (for example: `npm run test` or `node_modules/.bin/jest`) `npx jest`

### Steps to Reproduce

1. Run:
```sh
npm init
npm i jest
code .
```
2. Go to 'Run' tab in vscode (Ctrl+Shift+D in Windows)
3. Click 'create a launch.json file'
4. Select 'Debug Jest tests using vscode-jest'
5. Create file 'something.js'
```js
function something() {
  return true;
}

module.exports = something;

```
6. Create file 'something.test.js'
```js
const something = require("./something.js");

describe("something", () => {
  it('something with "quotes" in name', () => {
    expect(something()).toBe(true);
  });
});
```
7. Click 'Debug' on top of the test

### Relevant Debug Info

Output to terminal:
```sh
 ${env:CI}='vscode-jest-tests'; ${env:NODE_OPTIONS}='--require C:\Users\XXX~1\AppData\Local\Temp\vscode-js-debug-bootloader.js '; ${env:VSCODE_INSPECTOR_OPTIONS}='{"inspectorIpc":"\\\\.\\pipe\\node-cdp.1716-1.sock","deferredMode":false,"waitForDebugger":"","execPath":"C:\\Program Files\\nodejs\\node.exe","onlyEntrypoint":false,"fileCallback":"C:\\Users\\XXX~1\\AppData\\Local\\Temp\\node-debug-callback-18c05939ed997a21"}'; & 'C:\Program Files\nodejs\node.exe' '.\node_modules\jest\bin\jest' '--runInBand' 'something.test.js' '--testNamePattern' 'something with "quotes" in name'
Debugger listening on ws://127.0.0.1:58715/a8a555a3-137d-47e0-99dd-6f79ff243849
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
Test Suites: 1 skipped, 0 of 1 total
Tests:       1 skipped, 1 total     
Snapshots:   0 total
Time:        2.453 s
Ran all test suites matching /something.test.js/i with tests matching "something with quotes in name".
```

### Expected Behavior

Test will run and attach to debugger

### Actual Behavior

Test is skipped

**Comment by connectdotz** [comment]
hmmm... I have no problem running this on Mac... vscode debugger has escaped the double-quote automatically without the plugin doing anything special... if this only happens on windows (can somebody verify?) then probably should let vscode know because this behavior should be consistent across platforms...

**Comment by simjesinstech** [comment]
Having a similar issue on windows, when debugging a single test using the debug CodeLense - create react app project - default `launch.json` template
This is skipped: 
>\`should do something if ${someVariable}\`

This is not skipped: 
>\`should do something if X\`

**Comment by connectdotz** [comment]
hmmm... this is an interesting problem, but it has nothing to do with the double-quote. The problem is the parser is not able to parse the expression in template-literal... I think we might be able to address this with v4, can you open a separate issue to track this?

**Comment by stephtr** [comment]
Is this issue still a thing? I can't reproduce it on my Windows 10 machine.
I also can't see how #607 would fix the issue since in cmd quotes are escaped as `""` instead of `\"`.

**Comment by svekl** [comment]
I think it's a bit broader issue than just double quotes. For me it also ignores describe blocks without quotes and with template literals

Examples:
```typescript
  describe(rtkAction, () => {
  describe(`${rtkAction}`, () => {
```

What works well is:
```typescript
  describe('rtkAction', () => {
```

Faced it because using Redux toolkit and actions generated by it are casting to string well so this notation helps me to find all action references including jest describes and tests, so in case of renaming - name gets updated even in test name.

**Comment by connectdotz** [comment]
@svekl I think you found a bug, although it is not the same as the original issue, which should probably not an issue after v4 anymore...

**Comment by deeptha-utt** [comment]
I have test description something like this and it skips when I try to run the test case individually but runs when I run the test suite (describe)
it("should display values with 'Show' button when values are hidden", ...)

However, if I remove the single quote within the string it works fine.
What works:
it("should display values with Show button when values are hidden", ...)
