### ISSUE TITLE
Weird line highlights

### ISSUE THREAD

**Issue by arvigeus** [jest-community/vscode-jest#610]
A screenshot shows it all: https://imgur.com/ha5n4BX

It looks so out of place and misleading (an error? diff?)

Default theme, default settings

Link to the file from the project (if needed): https://github.com/katawaredev/config/blob/master/packages/jest-preset-permissive/expo.js

**Comment by arvigeus** [comment]
It seems the line disappeared with disabling _Enable Code Coverage On Load_.

I guess that styling need some reworking

**Comment by connectdotz** [comment]
hmmm... the `jest.showCoverageOnLoad` should default to false, do you have a sample repo we can take a look? 

> I guess that styling need some reworking

suggestion?

**Comment by arvigeus** [comment]
Was this recently updated? Now when I reset it it's not showing anything. I will close it for now.

> suggestion?

Red squares like [Wallaby.js](https://wallabyjs.com/)
