### ISSUE TITLE
Decorators are not shown for test.each

### ISSUE THREAD

**Issue by alexalexiuc** [jest-community/vscode-jest#612]
### Environment

`node -v`: 10.20.1
`npm -v`: 6.14.4
`extension version`: 3.2.0

Operating system: Windows 10

### Steps to Reproduce

When I am writing a test using `test.each`, no matter if test pass or fail, decorators are not shown for that test

### Expected Behavior

Decorators to be shown for `test.each`

### Actual Behavior

See `test.each`

![image](https://user-images.githubusercontent.com/27913426/89451863-83230300-d765-11ea-816d-cc2714facffd.png)

**Comment by connectdotz** [comment]
this is a known issue but should be addressed by [v4.0](https://github.com/jest-community/vscode-jest/releases/tag/v4.0.0-alpha.0), feel free to give it a try...

**Comment by ximex** [comment]
`test.each()` already works in v4 alpha. but `test.concurrent.each` isn't working.

**Comment by ankitprahladsoni** [comment]
What about `it.each()` with string template? I don't see decorators for that even on v4alpha2

**Comment by connectdotz** [comment]
@ankitprahladsoni you are right, there are a few gaps in the parameterized test support. Feel free to take a look at #649, which should close these gaps...

**Comment by connectdotz** [comment]
[v4.0.0-alpha.3](https://github.com/jest-community/vscode-jest/releases/tag/v4.0.0-alpha.3) is released today. The main change is to support the parameterized tests. Feel free to give this release a try and open new issues if needed...
