### ISSUE TITLE
Green check not appearing when more tests in different describe has the same title in the same file 

### ISSUE THREAD

**Issue by bisialessandro** [jest-community/vscode-jest#620]
### Environment

1. `node -v`: v10.20.1
1. `npm -v`: 6.14.4
1. `npm ls jest` or `npm ls react-scripts` (if you haven’t ejected): jest@26.1.0
1. your vscode-jest settings if customized:
    - jest.pathToJest? no
    - jest.pathToConfig? no
    - anything else that you think might be relevant? no

1. Operating system: macOS Catalina 10.15.5 

### Prerequisite
- are you able to run jest test from command line? yes
- how do you run your tests from command line? (for example: `npm run test` or `node_modules/.bin/jest`) yarn jest

### Steps to Reproduce
https://github.com/bisialessandro/vscode-jest-issue

### Expected Behavior

We should see green arrow on the side of the successful test that are in the same file with the same title but in different describe.

### Actual Behavior

The command yarn jest is successfully execute but the inside of the file it seems that the test with the same title are not going to be considered. 

--- 

The fastest (and the most fun) way to resolve the issue is to submit a pull-request yourself. If you are interested, feel free to check out the [contribution guide](https://github.com/jest-community/vscode-jest/CONTRIBUTING.md), we look forward to seeing your PR...

**Comment by adamldoyle** [comment]
Another seemingly related issue is that when you click "Debug" above one of the duplicated test titles, it runs all tests in that file with the duplicated title and outputs a message such as "Ran all test suites matching /testFile.test.js/i with tests matching 'duplicated test title'."
