### ISSUE TITLE
Could not resolve a module for a custom reporter

### ISSUE THREAD

**Issue by admir86** [jest-community/vscode-jest#621]
### Environment

1. `node -v`: v12.16.2
1. `npm -v`: 6.9.0
1. `npm ls jest` or `npm ls react-scripts` (if you haven’t ejected): jest@26.2.2 
1. your vscode-jest settings if customized:
    - jest.pathToJest? yes, `"npm run tst --"`
    - jest.pathToConfig? yes, `./jest.config.js`
    - anything else that you think might be relevant? the npm tst script? `node ./node_modules/@nrwl/cli/bin/nx test jst-app --runInBand=true --codeCoverage=false`

1. Operating system: Windows 10

### Prerequisite
- are you able to run jest test from command line? yes
- how do you run your tests from command line? (for example: `npm run test` or `node_modules/.bin/jest`) `npm run tst`

### Steps to Reproduce

`git clone https://github.com/admir86/vscode-jest`
`npm ci`
open the jest output to see the logs

### Expected Behavior

Watcher should run and show test result.

### Actual Behavior

Watcher is crashing: 
![image](https://user-images.githubusercontent.com/36576424/92022861-37f81200-ed5c-11ea-9f97-3c115ec93a58.png)

with error:
```
An unhandled exception occurred: Could not resolve a module for a custom reporter.
  Module name: default,c:\Users\admir\.vscode\extensions\orta.vscode-jest-3.2.0\out\reporter.js
```

--- 

The fastest (and the most fun) way to resolve the issue is to submit a pull-request yourself. If you are interested, feel free to check out the [contribution guide](https://github.com/jest-community/vscode-jest/CONTRIBUTING.md), we look forward to seeing your PR...

**Comment by connectdotz** [comment]
hmmm... could this be related to the [nx](https://github.com/nrwl/nx/issues/3450) issue?

**Comment by admir86** [comment]
possible, a few weeks ago I made updates of my npm dependencies, since then it works
