### ISSUE TITLE
Stuck at "Starting watch mode"

### ISSUE THREAD

**Issue by dominik-fielmann** [jest-community/vscode-jest#628]
I have been stuck with this problem since I switched to a new laptop with Ubuntu 20.04. 

The issue is the exact same one as mentioned [here](https://github.com/jest-community/vscode-jest/issues/316). vscode-jest is stuck in the "starting watch mode" phase and never displays the results of the tests.

A colleague who has a similar setup as me has the exact same problem. VSCode is installed via snap, in case that's relevant.

### Environment

1. `node -v`: v14.13.1
1. `npm -v`: 6.14.8
1. `npm ls jest` or `npm ls react-scripts` (if you haven’t ejected): jest@26.5.2
1. your vscode-jest settings if customized:
    - jest.pathToJest? not changed, but I tried as well with "npm run test --"
    - jest.pathToConfig? not changed
    - anything else that you think might be relevant? I disabled all other extensions.

1. Operating system: Ubuntu 20.04

### Prerequisite
- are you able to run jest test from command line? yes
- how do you run your tests from command line? `npm run test`

### Steps to Reproduce

Happens with any jest repository unfortunately.

### Relevant Debug Info

Complete output from the extension ouput window:

> Finished running all tests. Starting watch mode.

<details><summary>Output from Developer Tools console</summary>

<pre>
TMScopeRegistry.ts:45 Overwriting grammar scope name to file mapping for scope source.yaml.
Old grammar file: file:///snap/code/46/usr/share/code/resources/app/extensions/yaml/syntaxes/yaml.tmLanguage.json.
New grammar file: file:///home/dominik/.vscode/extensions/redhat.vscode-yaml-0.11.1/syntaxes/yaml.tmLanguage.json
register @ TMScopeRegistry.ts:43
console.ts:137 [Extension Host] (node:3871) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
t.log @ console.ts:70
console.ts:137 [Extension Host] spawning process with command=npm run test -- --testLocationInResults --json --useStderr --outputFile /tmp/jest_runner_server.json --no-coverage --no-color --reporters default --reporters "/home/dominik/.vscode/extensions/orta.vscode-jest-3.2.0/out/reporter.js"
console.ts:137 [Extension Host] spawning process with command=npm run test -- --testLocationInResults --json --useStderr --outputFile /tmp/jest_runner_server.json --watch --no-coverage --no-color --reporters default --reporters "/home/dominik/.vscode/extensions/orta.vscode-jest-3.2.0/out/reporter.js"
console.ts:137 [Extension Host] No editors associated with document: /home/dominik/code/mfm/orders-module-backend/server/tsconfig.json
t.log @ console.ts:70
console.ts:137 [Extension Host] spawning process with command="/home/dominik/code/mfm/orders-module-backend/server/node_modules/.bin/jest" --testLocationInResults --json --useStderr --outputFile /tmp/jest_runner_server.json --no-coverage --no-color --reporters default --reporters "/home/dominik/.vscode/extensions/orta.vscode-jest-3.2.0/out/reporter.js"
console.ts:137 [Extension Host] spawning process with command="/home/dominik/code/mfm/orders-module-backend/server/node_modules/.bin/jest" --testLocationInResults --json --useStderr --outputFile /tmp/jest_runner_server.json --watch --no-coverage --no-color --reporters default --reporters "/home/dominik/.vscode/extensions/orta.vscode-jest-3.2.0/out/reporter.js"
DevTools failed to load SourceMap: Could not load content for file:///snap/code/46/usr/share/code/resources/app/node_modules.asar/semver-umd/lib/semver-umd.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///snap/code/46/usr/share/code/resources/app/node_modules.asar/xterm/lib/xterm.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///snap/code/46/usr/share/code/resources/app/node_modules.asar/xterm-addon-unicode11/lib/xterm-addon-unicode11.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///snap/code/46/usr/share/code/resources/app/node_modules.asar/xterm-addon-search/lib/xterm-addon-search.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///snap/code/46/usr/share/code/resources/app/node_modules.asar/node-pty/lib/index.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///snap/code/46/usr/share/code/resources/app/node_modules.asar/node-pty/lib/unixTerminal.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///snap/code/46/usr/share/code/resources/app/node_modules.asar/node-pty/lib/terminal.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///snap/code/46/usr/share/code/resources/app/node_modules.asar/node-pty/lib/eventEmitter2.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///snap/code/46/usr/share/code/resources/app/node_modules.asar/node-pty/lib/utils.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///snap/code/46/usr/share/code/resources/app/node_modules.asar/tas-client/tas-client/ExperimentationService.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///snap/code/46/usr/share/code/resources/app/node_modules.asar/tas-client/tas-client/FeatureProvider/TasApiFeatureProvider.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///snap/code/46/usr/share/code/resources/app/node_modules.asar/tas-client/tas-client/FeatureProvider/FilteredFeatureProvider.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///snap/code/46/usr/share/code/resources/app/node_modules.asar/tas-client/tas-client/FeatureProvider/BaseFeatureProvider.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///snap/code/46/usr/share/code/resources/app/node_modules.asar/tas-client/tas-client/Util/AxiosHttpClient.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///snap/code/46/usr/share/code/resources/app/node_modules.asar/tas-client/tas-client/ExperimentationServiceAutoPolling.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///snap/code/46/usr/share/code/resources/app/node_modules.asar/tas-client/tas-client/ExperimentationServiceBase.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///snap/code/46/usr/share/code/resources/app/node_modules.asar/tas-client/tas-client/Util/MemoryKeyValueStorage.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///snap/code/46/usr/share/code/resources/app/node_modules.asar/tas-client/tas-client/Util/PollingService.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///snap/code/46/usr/share/code/resources/app/node_modules.asar/vscode-textmate/release/main.js.map: 
</pre>
</details>

### Expected Behavior

The tests are run and the UI shows the result next to the test.

### Actual Behavior

`Jest: Starting watch mode` keeps showing indefinitely. The test indicator status remains an empty circle.

**Comment by dominik-fielmann** [comment]
Because of a suspicion, I removed the `code` snap package and reinstalled it via `apt`. Suddenly it works. So this bug seems to happen with the snap version of VS Code only.

**Comment by connectdotz** [comment]
close as it didn't seem to be related to this extension.
