### ISSUE TITLE
Run | Debug disappears when optional chaining operator is encountered (parsing fails)

### ISSUE THREAD

**Issue by JonathanWilbur** [jest-community/vscode-jest#630]
I am almost certain this is a bug with the [Jest Editor Support](https://github.com/jest-community/jest-editor-support) library, but I am just letting you know, because it critically affects this extension.

See [this issue](https://github.com/jest-community/jest-editor-support/issues/51) for more information.

**Comment by connectdotz** [comment]
please give [v4 alpha](https://github.com/jest-community/vscode-jest/releases) a try and let us know if you still see this issue...

**Comment by connectdotz** [comment]
feel free to reopen it if it didn't resolve your issue
