### ISSUE TITLE
Debug button disappears

### ISSUE THREAD

**Issue by andersekdahl** [jest-community/vscode-jest#631]
When I start VSCode I can see a Debug button on top of my tests, but then it disappears. Closing the folder in VSCode and opening it again shows the Debug button again.

### Environment

1. `node -v`: v12.19.0
1. `yarn -v`: 1.22.10
1. `npm ls jest` or `npm ls react-scripts` (if you haven’t ejected): jest@26.4.2
1. your vscode-jest settings if customized:
    - jest.pathToJest? no
    - jest.pathToConfig? no
    - anything else that you think might be relevant? no

1. Operating system: Windows

### Prerequisite
- are you able to run jest test from command line? yes
- how do you run your tests from command line? (for example: `npm run test` or `node_modules/.bin/jest`) ``.\node_modules\.bin\jest`

### Steps to Reproduce

I'm not quite sure if this is what's causing it, but it seems that if I run jest through the CLI, then open VSCode and navigate to a file with tests in them, the Debug button has now disappeared.

### Relevant Debug Info

Not sure I have any relevant debug info.

### Expected Behavior

Debug button shouldn't disappear.

### Actual Behavior

Debug button disappeared.

**Comment by connectdotz** [comment]
by default the debug button shows up only for "failed" or "unknown" tests. You can change this behavior by setting `jest.debugCodeLens.showWhenTestStateIn` to include one or more states: 
```
[ "fail","pass", "skip", "unknown"]          
```

**Comment by andersekdahl** [comment]
Ah, didn't know that, thanks!

**Comment by thorseye** [comment]
> by default the debug button shows up only for "failed" or "unknown" tests. You can change this behavior by setting `jest.debugCodeLens.showWhenTestStateIn` to include one or more states:
> 
> ```
> [ "fail","pass", "skip", "unknown"]          
> ```

This is a quite hidden feature - maybe it could be added to the docs, and the settings could display the available options to set?
