### ISSUE TITLE
Open VSX Listing: Signing the Publisher Agreement

### ISSUE THREAD

**Issue by spoenemann** [jest-community/vscode-jest#645]
Thank you for being part of the Open VSX community by adding your extensions to the Open VSX Registry. Please note that the service was recently transferred to the Eclipse Foundation and urgent action on your part is needed so we can continue to list your extensions. To ensure uninterrupted service, please sign the [Eclipse Publisher Agreement](https://www.eclipse.org/legal/documents/eclipse-openvsx-publisher-agreement.pdf) **on or before January 8, 2021**. If not signed by that date, your extensions will be delisted and will no longer appear on the site nor be available via the API. If you sign at a later date, your extensions will then be re-activated. The signing process is [explained in the Wiki](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions) (steps 1 and 2).

Please also note that all extensions MUST have a license in order to be listed.

More details are in these recent blog posts:
https://blogs.eclipse.org/post/brian-king/open-vsx-registry-under-new-management
https://blogs.eclipse.org/post/brian-king/new-era-open-vsx-registry

Today, there’s growing momentum around open source tools and technologies that support Visual Studio (VS) Code extensions. Leading global organizations are adopting these tools and technologies. This momentum has spurred demand for a marketplace without restrictions and limitations. Thanks for joining us on this journey as we continue to build the Open VSX community. We look forward to continued innovation from you in 2021!

**Comment by connectdotz** [comment]
sorry looks like I am late. @orta did you happen to sign it yet? Do you have any objections?

**Comment by orta** [comment]
Odd, I should have already signed it for Svelte

**Comment by orta** [comment]
Confirmed, maybe @spoenemann  might mean you
![Screen Shot 2021-01-19 at 5 59 19 PM](https://user-images.githubusercontent.com/49038/105074284-0fa94f80-5a80-11eb-8964-df0507f86488.png)

**Comment by spoenemann** [comment]
Yes this issue is about the [Jest extension](https://open-vsx.org/extension/Orta/vscode-jest) which was published by @connectdotz. The Publisher Agreement needs to be signed by the publishing user.

**Comment by connectdotz** [comment]
ok, I am on it now but having some problem creating an eclipse account... working with the webmaster@eclipse.org, hopefully, we will figure it out soon

**Comment by connectdotz** [comment]
the account issue is resolved and I sign the publisher agreement. Not sure if the extension release is restored... I plan to push the next release soon.

**Comment by spoenemann** [comment]
Great! That's all, you can continue publishing as usual now.

**Comment by connectdotz** [comment]
ok, cool.
