### ISSUE TITLE
Plugin runs on files it shouldn't

### ISSUE THREAD

**Issue by simonknittel** [jest-community/vscode-jest#646]
### Environment

1. `node -v`: v14.15.1
1. `npm -v`: 6.14.8
1. `npm ls jest` or `npm ls react-scripts` (if you haven’t ejected): jest@26.6.3
1. your vscode-jest settings if customized:
    - jest.pathToJest? no
    - jest.pathToConfig? no
    - anything else that you think might be relevant? no

1. Operating system: macOS

### Prerequisite
- are you able to run jest test from command line? yes
- how do you run your tests from command line? (for example: `npm run test` or `node_modules/.bin/jest`) npm run test

### Steps to Reproduce

I've got following file tree:
- root
  - cypress
    - integration
      - my-cypress-test.spec.js
  - source
    - spec
      - my-jest-test.test.js
  - jest.config.js
  - package.json
  - node_modules
  - ...

My jest.config.js contains:
```
module.exports = {
  roots: ['source/']
};
```

### Expected Behavior

The extension only runs on files located in source/

### Actual Behavior

I've got - imho fairly simple - setup in which I've got a directory for Cypress test files and a directory for Jest test files. I've created a jest.config.js file and use their `roots` property to point Jest to the correct directory. This works when I run Jest manually and also when the extension executes the tests.

However, for some reason it also detects the files located in the `cypress` directory as Jest test files and complains about "cy is not defined" and also shows these small green ticks or red crosses in front of each `it()` call. It doesn't run these tests, but when I open the file, the extension thinks that this is a Jest test file and apparently runs their own linting against it.

I've tried many different combinations of jest.rootPath, jest.disabledWorkspaceFolders etc. but without any success. It always keeps thinking these Cypress test files are Jest files even though it does not try to run these tests.

<img width="855" alt="Screenshot 2021-01-06 at 08 57 26" src="https://user-images.githubusercontent.com/8451099/103743974-42256800-4ffd-11eb-9f28-0d6540caa149.png">

--- 

The fastest (and the most fun) way to resolve the issue is to submit a pull-request yourself. If you are interested, feel free to check out the [contribution guide](https://github.com/jest-community/vscode-jest/CONTRIBUTING.md), we look forward to seeing your PR...

**Comment by connectdotz** [comment]
this is weird... if it shows status marks that means it found some test results from jest run. can you turn on debug mode and show us the command line started jest process from your developer console or output channel? Or if you have a sample repo that will be very helpful too

**Comment by simonknittel** [comment]
Hi @connectdotz, 
I've created https://github.com/simonknittel/vscode-jest-sample as a sample repo since I'm not exactly sure what to look out for with the debug mode enabled.
The repo is very basic but is enough to repoduce the bug.

**Comment by connectdotz** [comment]
@simonknittel I tried your repo with the latest alpha ([v4.0.0-alpha.3](https://github.com/jest-community/vscode-jest/releases/tag/v4.0.0-alpha.3)) and I could not reproduce the issue... 

<img width="560" alt="Screen Shot 2021-01-28 at 6 31 08 PM" src="https://user-images.githubusercontent.com/891093/106211602-0bbfb080-6197-11eb-8f70-b7070ec8424e.png">
<img width="560" alt="Screen Shot 2021-01-28 at 6 30 37 PM" src="https://user-images.githubusercontent.com/891093/106211604-0c584700-6197-11eb-9c81-f62b9b689198.png">


Do you mind trying alpha.3 to see if that resolves your issue?

**Comment by simonknittel** [comment]
Hi @connectdotz, yes that seems to resolve that issue. With that version installed I can not repoduce the issue anymore. It behaves like in your screenshots.

**Comment by connectdotz** [comment]
great!

**Comment by Yash-Singh1** [comment]
I am still seeing this issue on `vscode-jest` v4.4.0.

**Comment by connectdotz** [comment]
@Yash-Singh1 @muuvmuuv please feel free to open a new issue with a sample repo
