### ISSUE TITLE
No checkmark when test with same name exists in other describe block scope

### ISSUE THREAD

**Issue by ties-s** [jest-community/vscode-jest#648]
### Environment

1. `node -v`: v12.16.3
1. `npm -v`: 6.14.4
1. `npm ls jest` or `npm ls react-scripts` (if you haven’t ejected): jest@26.6.3 

1. Operating system: macOS 11.1

### Prerequisite
- are you able to run jest test from command line? yes
- how do you run your tests from command line? (for example: `npm run test` or `node_modules/.bin/jest`) npm t

### Steps to Reproduce

```js
describe('Block A', () => {

	test('Test 1', () => {
		// expect ...
	}) 

	test('Test 2 in A', () => {
		// expect ...
	}) 

})

describe('Block B', () => {

	test('Test 1', () => {
		// expect ...
	}) 

	test('Test 2 in B', () => {
		// expect ...
	}) 

})
```

### Expected Behavior

show checkmark next to all tests

### Actual Behavior

no checkmark, but a circle, next to tests that have that also exists in another `describe` block

**Comment by connectdotz** [comment]
please give [v4-alpha](https://github.com/jest-community/vscode-jest/releases/tag/v4.0.0-alpha.2) a try

**Comment by ties-s** [comment]
I switched to another plugin for now.

**Comment by connectdotz** [comment]
no problem, this should already be fixed in v4. feel free to reopen if otherwise...
