### ISSUE TITLE
Alpha 3: Debug lens disappears when jest.autoEnable is set to false

### ISSUE THREAD

**Issue by sebas2day** [jest-community/vscode-jest#658]
### Environment

1. `node -v`: v14.15.1
1. `npm -v`: NA
1. `npm ls jest` or `npm ls react-scripts` (if you haven’t ejected): [fill]
1. your vscode-jest settings if customized: NA
    - jest.pathToJest? [fill]
    - jest.pathToConfig? [fill]
    - anything else that you think might be relevant? [fill]

1. Operating system: Macos 11.1

### Prerequisite
- are you able to run jest test from command line? Yes
- how do you run your tests from command line? (for example: `npm run test` or `node_modules/.bin/jest`) `yarn test`

### Steps to Reproduce

Set `jest.autoEnable` to false. Restart vscode window. Debug does not show up ( see screenshot ).

<img width="500" alt="image" src="https://user-images.githubusercontent.com/5485197/106768236-03a2bd80-663c-11eb-8eff-8bcbf3909d5d.png">

### Relevant Debug Info

NA

### Expected Behavior

Expected to see the debug button. In the non-alpha release (3.2.0) this was still working.

<img width="515" alt="image" src="https://user-images.githubusercontent.com/5485197/106769065-de627f00-663c-11eb-8146-f5f58dcb41e9.png">

### Actual Behavior

No debug button

--- 

The fastest (and the most fun) way to resolve the issue is to submit a pull-request yourself. If you are interested, feel free to check out the [contribution guide](https://github.com/jest-community/vscode-jest/CONTRIBUTING.md), we look forward to seeing your PR...

**Comment by connectdotz** [comment]
Hmmm... indeed, good catch. We missed this use case. The workaround is easy, just triggers the test to run by touch and save the file, but yes we should address this issue.

**Comment by connectdotz** [comment]
however, keep in mind that even though we can add the debug codeLens back, its functionality is greatly reduced. For example, you won't be able to debug parameterized tests individually, any test name with dynamic value, such as template-literal, test parameters, will not be debuggable as jest will not find those tests by the uninterpreted names...

Anyway, I will restore the previous behavior, at least you can debug some of the tests if not all...

**Comment by sebas2day** [comment]
Ok. Does that account for `jest.each` as well or only dynamic test names? I really liked how `jest.each` is debuggable now with this alpha release but I actually don't want jest to keep running in the background as its really eating my CPU %.

**Comment by connectdotz** [comment]
> Does that account for jest.each as well or only dynamic test names?

if your parameterized test name contains variables, such as "%s", "$parameter", it is dynamic and thus probably won't be able to debug... 

> I actually don't want jest to keep running in the background as its really eating my CPU %.

yeah, we are aware of this issue... If I got some cycle, would like to tackle this in v4, I think it is another common complaint that worthy to address...

**Comment by sebas2day** [comment]
Thanks for fixing this. I installed the new alpha and it works, including `test.each`, real nice.

> yeah, we are aware of this issue... If I got some cycle, would like to tackle this in v4, I think it is another common complaint that worthy to address...

Maybe an idea to auto watch only the test files that have been opened by the user?
