### ISSUE TITLE
Starting VSCode gives "registerer.enabled" is not a function

### ISSUE THREAD

**Issue by protechdm** [jest-community/vscode-jest#672]
Error: Jest: Failed to parse the TypeScript config file F:\example22\jest.config.ts
  TypeError: registerer.enabled is not a function
    at readConfigFileAndSetRootDir (f:\example22\node_modules\jest-config\build\readConfigFileAndSetRootDir.js:150:13)

Error: Jest: Failed to parse the TypeScript config file F:\example22\jest.config.ts
  TypeError: registerer.enabled is not a function
    at readConfigFileAndSetRootDir (f:\example22\node_modules\jest-config\build\readConfigFileAndSetRootDir.js:150:13)

Error: Jest: Failed to parse the TypeScript config file F:\example22\jest.config.ts
  TypeError: registerer.enabled is not a function
    at readConfigFileAndSetRootDir (f:\example22\node_modules\jest-config\build\readConfigFileAndSetRootDir.js:150:13)

Error: Jest: Failed to parse the TypeScript config file F:\example22\jest.config.ts
  TypeError: registerer.enabled is not a function
    at readConfigFileAndSetRootDir (f:\example22\node_modules\jest-config\build\readConfigFileAndSetRootDir.js:150:13)

Error: Jest: Failed to parse the TypeScript config file F:\example22\jest.config.ts
  TypeError: registerer.enabled is not a function
    at readConfigFileAndSetRootDir (f:\example22\node_modules\jest-config\build\readConfigFileAndSetRootDir.js:150:13)

Starting Jest in Watch mode failed too many times and has been stopped.
 see troubleshooting: https://github.com/jest-community/vscode-jest/blob/master/README.md#troubleshooting

**jest.config.ts:-**

import type {Config} from "@jest/types";

const config: Config.InitialOptions = {
  verbose: true,
  transform : {
    "^.+\\.[t|j]sx?$": "ts-jest",
    "^.+\\.[t|j]sx$": "babel-jest"
  },
  moduleNameMapper: {
    "^src\/testing$": "<rootDir>/src/testing/async-observable-helpers.ts"
  },
  modulePathIgnorePatterns: [
    "node_modules"
  ]
};
export default config;

**Comment by connectdotz** [comment]
This looks like a jest issue, are you able to start jest in terminal?

**Comment by expelledboy** [comment]
If you look through the code its trying to call an api to`ts-node`

```js
let registerer; // Load the TypeScript configuration

const loadTSConfigFile = async configPath => {
  // Register TypeScript compiler instance
  await registerTsNode();
  registerer.enabled(true);
  let configObject = (0, _jestUtil().interopRequireDefault)(
    require(configPath)
  ).default; // In case the config is a function which imports more Typescript code

  if (typeof configObject === 'function') {
    configObject = await configObject();
  }

  registerer.enabled(false);
  return configObject;
};

async function registerTsNode() {
  if (registerer) {
    return registerer;
  }

  try {
    const tsNode = await import('ts-node');
    registerer = tsNode.register({
      compilerOptions: {
        module: 'CommonJS'
      },
      moduleTypes: {
        '**': 'cjs'
      }
    });
    return registerer;
  } catch (e) {
    if (e.code === 'ERR_MODULE_NOT_FOUND') {
      throw new Error(
        `Jest: 'ts-node' is required for the TypeScript configuration files. Make sure it is installed\nError: ${e.message}`
      );
    }

    throw e;
  }
}
```

This can only mean that the api of your ts-node is not compatible ie it has to be a dep issue between jest and ts-node. Hope this helps anyone out there.

**Comment by connectdotz** [comment]
thanks @expelledboy! This issue has been inactive for a year and is not related to this extension. I will close it now.
