### ISSUE TITLE
setSystemTime is not available

### ISSUE THREAD

**Issue by moeyashi** [jest-community/vscode-jest#677]
### Environment

1. `node -v`: v12.20.2
1. `npm -v`: 6.14.11
1. `npm ls jest` or `npm ls react-scripts` (if you haven’t ejected): `-- jest@26.6.3
1. your vscode-jest settings if customized:
    - jest.pathToJest? not customize
    - jest.pathToConfig? not customize
    - anything else that you think might be relevant? not customize

1. Operating system: Windows10

### Prerequisite
- are you able to run jest test from command line? yes
- how do you run your tests from command line? (for example: `npm run test` or `node_modules/.bin/jest`) yarn test

### Steps to Reproduce

https://github.com/moeyashi/issue-vscode-jest-set-system-time

```
git clone https://github.com/moeyashi/issue-vscode-jest-set-system-time
yarn
# Change setSystemTime.spec.js for start vscode-jest
```

### Relevant Debug Info

In `yarn test` the test succeeds

```
yarn run v1.22.10
$ jest
 PASS  ./setSystemTime.spec.js
  setSystemTime
    √ can set new Date (6 ms)

Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        13.226 s
Ran all test suites.
Done in 17.96s.
```

### Expected Behavior

test suite pass

### Actual Behavior

test suite failed

```

  ● setSystemTime › can set new Date

    TypeError: setSystemTime is not available when not using modern timers

      2 |     test('can set new Date', () => {
      3 |         jest.useFakeTimers('modern')
    > 4 |         jest.setSystemTime(new Date('2020-02-03')) //TypeError: setSystemTime is not available when not using modern timers
        |              ^
      5 |         const actual = new Date()
      6 |         expect(actual.getFullYear()).toBe(2020)
      7 |         expect(actual.getMonth()).toBe(1)

      at Object.setSystemTime (node_modules/jest-runtime/build/index.js:1856:17)
      at Object.<anonymous> (setSystemTime.spec.js:4:14)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        0.34 s, estimated 1 s
Ran all test suites related to changed files.
```

--- 

The fastest (and the most fun) way to resolve the issue is to submit a pull-request yourself. If you are interested, feel free to check out the [contribution guide](https://github.com/jest-community/vscode-jest/CONTRIBUTING.md), we look forward to seeing your PR...

**Comment by connectdotz** [comment]
hi, I tried your repo (on mac) but can not reproduce the issue (with [v4.0.0-alpha.5](https://github.com/jest-community/vscode-jest/releases/tag/v4.0.0-alpha.5))... the extension is actually using the jest under node_modules, maybe you have a different version of jest there (comparing to `yarn test`)? you can try setting `jest.pathToJest` to `yarn test`, or try to figure out the actual root cause that I think probably not related to this extension...

**Comment by moeyashi** [comment]
@connectdotz Thank you for your reply.
I close this issue. I commented for someone who faced the same error.

Today, I tried these.

- I tried on Ubuntu on WSL and can pass test.
- I tried setting `jest.pathToJest` to `yarn test` on windows, but I can not pass test.
- I tried use `v4.0.0-alpha.5`, but I can not pass that.

In any case, I can pass test on terminal with `yarn test`.
