### ISSUE TITLE
Unrecognized option "testLocationInResults".

### ISSUE THREAD

**Issue by levin-ilya** [jest-community/vscode-jest#681]
### Environment

1. `node -v`: v14.9.0
1. `npm -v`: 6.14.7
1. `npm ls jest` or `npm ls react-scripts` (if you haven’t ejected): jest@21.2.1
1. Operating system: MacOS X

**Comment by connectdotz** [comment]
hi, yes this extension does have dependency on`testLocationInResults` flag, which was introduced in jest 22.0 3 years ago. Looks like you were still using pretty old 21.2.1, might want to consider upgrading it?

**Comment by levin-ilya** [comment]
I see, unfortunately I can not, it's a large project with a ton of test failures if we upgrade, but thanks for the info!
