### ISSUE TITLE
Jest process "watch-tests" failed unexpectedly

### ISSUE THREAD

**Issue by Derican** [jest-community/vscode-jest#702]
### Environment

1. `vscode-jest version`: [4.0.1]
2. `node -v`: [14.16.0]
3. `npm -v` or `yarn --version`: [6.14.11]
4. `npm ls jest` or `npm ls react-scripts` (if you haven’t ejected): [
octs_frontend@0.1.0 C:\Users\Grady\Desktop\octs-frontend
+-- @vue/cli-plugin-unit-jest@4.5.11
| \`-- jest@24.9.0  deduped
\`-- jest@24.9.0
]
5. your vscode-jest settings if customized:
    - jest.jestCommandLine? ["jest.jestCommandLine": "npm run test --"]
    - jest.autoRun? [{
		"watch": true
	}]
    - anything else that you think might be relevant? []
6. Operating system: [Win10 x64 20H2 19042.985]

### Prerequisite
- are you able to run jest test from the command line? [yes]
- how do you run your tests from the command line? (for example: `npm run test` or `node_modules/.bin/jest`) [`npm run test`]

### Steps to Reproduce

create a vue-cli project and open the folder with VS Code

### Relevant Debug Info

Jest process "watch-tests" failed unexpectedly
 see troubleshooting: https://github.com/jest-community/vscode-jest/blob/master/README.md#troubleshooting

### Expected Behavior

When editing tests, jest runs those saved tests and shows the results.

### Actual Behavior

jest doesn't run any tests and Jest (Workspace) reports:
octs-frontend:		warning | success 24, fail 0, unknown 1; mode: coverage, auto-run-watch; state: idle

--- 

The fastest (and the most fun) way to resolve the issue is to submit a pull-request yourself. If you are interested, feel free to check out the [contribution guide](https://github.com/jest-community/vscode-jest/CONTRIBUTING.md), we look forward to seeing your PR...

**Comment by connectdotz** [comment]
it would be helpful if you can paste the error message from the OUTPUT channel or the developer console

**Comment by Derican** [comment]
# OUTPUT
Test Suites: 30 passed, 30 total
Tests:       103 passed, 103 total
Snapshots:   0 total
Time:        31.042s
Jest process "watch-tests" failed unexpectedly
 see troubleshooting: https://github.com/jest-community/vscode-jest/blob/master/README.md#troubleshooting

# developer console
[Extension Host] [octs-frontend/JestProcessManager] 
process ended: ObjectextContext: autoRun: {
config: "[Circular]", 
isOff: false, 
isWatch: true, 
mode: "auto-run-watch"}
loggingFactory: {}
output: {name: "Jest (octs-frontend)", 
_channel: {…}}
runnerWorkspace: {rootPath: "c:\Users\Grady\Desktop\octs-frontend", jestCommandLine: "npm run test --", pathToConfig: "", localJestMajorVersion: 20, outputFileSuffix: "octs_frontend", …}
collectCoverage: truedebug: truejestCommandLine: "npm run test --"
localJestMajorVersion: 20
outputFileSuffix: "octs_frontend"
pathToConfig: ""
rootPath: "c:\Users\Grady\Desktop\octs-frontend"
__proto__: Object
settings: {autoEnable: true, enableInlineErrorMessages: false, enableSnapshotUpdateMessages: true, pathToConfig: "", jestCommandLine: "npm run test --", …}
workspace: {uri: {…}, 
name: "octs-frontend", index: 0}__proto__: Objectrequest: {type: "watch-tests", listener: {…}, schedule: {…}}_id: "id: 0, 
request: {"type":"watch-tests","listener":"object","schedule":{"queue":"blocking","dedup":{"filterByStatus":["pending"]}}}"_stopReason: "process-end"__proto__: Object
workbench.desktop.main.js:62 [Extension Host] [octs-frontend/RunTestListener] Jest process "watch-tests" failed unexpectedly
S @ workbench.desktop.main.js:62
workbench.desktop.main.js:735 Jest process "watch-tests" failed unexpectedly

**Comment by connectdotz** [comment]
hmm... what does the npm test script do? Does it have '--watchAll=false' by any chance?

**Comment by Derican** [comment]
Yes I found it in my script. Does removing it give any help?
```
"test": "jest --coverage --testResultsProcessor=jest-sonar-reporter --silent --watchAll=false",
```
when I remove it, all tests are recognized as 'unknown'. By the way, the script worked with old version like 3.2.0

**Comment by connectdotz** [comment]
> Yes I found it in my script. Does removing it give any help?

Yes, that explains why the `watch-tests` ended since there is the `--watchAll=false` in the commandLine that prevented the watch to continue. 

> when I remove it, all tests are recognized as 'unknown'.

I assume you mean when you remove the `--watchAll=false` flag. In that case I am guessing because your `jest.autoRun` config did not have the `"onStartup": ["all-tests"]`, the extension will not run any test at startup (so they will all be question marks), and will only run tests when they changed (through jest watcher). 

> By the way, the script worked with old version like 3.2.0

Hm... do you have `jest.pathToJest` set for `yarn test`? If not then it explains why the 3.2.0 works because it is not using your test script. To simulate the same behavior as the old version, you can remove both `jest.jestCommandLine` and `jest.autoRun`, or set `jest.autoRun` to 
```
"jest.autoRun": {
   "watch": true, 
   "onStartup": ["all-tests"]
}
```

**Comment by Derican** [comment]
Thanks for help, I find the following setting matching my needs:
```
"jest.autoRun": {
		"watch": false,
		"onStartup": [
			"all-tests"
		],
		"onSave": "test-file",
	},
```
By the way, I want to set "onSave" both "test-file" and "test-src-file", how to write the json?

**Comment by connectdotz** [comment]
If you want to trigger test run upon either test and source file changes just use “test-src-files”

**Comment by Derican** [comment]
thx, that solved my problem.
