### ISSUE TITLE
ON Debugging the test case using Code Lense (no match found)

### ISSUE THREAD

**Issue by sachin-agarwal-by** [jest-community/vscode-jest#703]
### Environment

1. `vscode-jest version`: [v4.0.1]
2. `node -v`: [v12.18.4]
3. `npm -v` or `yarn --version`: [6.14.6]
4. `npm ls jest` or `npm ls react-scripts` (if you haven’t ejected): [react-scripts@3.4.4]
5. your vscode-jest settings if customized:
    - jest.jestCommandLine? [fill]
    - jest.autoRun? [{
    "watch": true,
    "onStartup": ["all-tests"]
  }]
    - anything else that you think might be relevant? [fill]
6. Operating system: [fill]

### Prerequisite
- are you able to run jest test from the command line? [yes]
- how do you run your tests from the command line? (for example: `npm run test` or `node_modules/.bin/jest`) [npm run test]

### Steps to Reproduce

I am just trying to click on Debug Code lense it saying no match Found. but in auto run mode all test cases are running but I cant debug it .

No tests found, exiting with code 1
Run with `--passWithNoTests` to exit with code 0
In C:\Users\aa\Documents\src
  741 files checked.
  testMatch: C:/Users/aa/Documents/src/**/__tests__/**/*.{js,jsx,ts,tsx}, C:/Users/aa/Documents/src/**/*.{spec,test}.{js,jsx,ts,tsx} - 138 matches
  testPathIgnorePatterns: \\node_modules\\ - 741 matches
  testRegex:  - 0 matches
Pattern: c:\Users\aa\Documents\src\views\index.test.js - 0 matches
Waiting for the debugger to disconnect...
Waiting for the debugger to disconnect...

Below is my vscode configuration:- 
[{
      "name": "vscode-jest-tests",
      "type": "node",
      "request": "launch",
      "env": { "CI": "true" },
      "runtimeExecutable": "${workspaceRoot}/node_modules/.bin/react-scripts",
      "args": ["test", "--runInBand", "--no-cache", "--watchAll=false"],
      "cwd": "${workspaceRoot}",
      "protocol": "inspector",
      "console": "integratedTerminal",
      "internalConsoleOptions": "neverOpen"
    }]

**Comment by connectdotz** [comment]
probably the same problem as #694

**Comment by sachin-agarwal-by** [comment]
@connectdotz  did we released the fix or do we have any workaround please?
