### ISSUE TITLE
Code lens debug stoped working in 4.0

### ISSUE THREAD

**Issue by Burnaster** [jest-community/vscode-jest#712]
### Environment

1. `vscode-jest version`: v4.0.1
2. `node -v`: v14.15.4
3. `npm -v` : 7.11.2
4. `npm ls jest` : jest@26.6.3
5. your vscode-jest settings if customized:
    - jest.jestCommandLine? none
    - jest.autoRun? none
6. Operating system: Windows 10

### Prerequisite
- are you able to run jest test from the command line? yes
- how do you run your tests from the command line? "angular cli" 

### Steps to Reproduce

`Jest: Run all tests`: works as expected.
VS Code debug with the `default Jest configuration`: works as expected
Code lens `Debug`: does not work

Since the extension upgrade to 4.x the code lens `Debug` stopped working for me.
### Relevant Debug Info

Console
```
cmd /C "set "CI=vscode-jest-tests" && set "NODE_OPTIONS=--require d:/development/tools/vscode_1_56_0/resources/app/extensions/ms-vscode.js-debug/src/bootloader.bundle.js --inspect-publish-uid=http" && set "VSCODE_INSPECTOR_OPTIONS={"inspectorIpc":"\\\\.\\pipe\\node-cdp.10764-1.sock","deferredMode":false,"waitForDebugger":"","execPath":"C:\\Program Files\\nodejs\\node.exe","onlyEntrypoint":false,"autoAttachMode":"always","fileCallback":"C:\\Users\\myuser\\AppData\\Local\\Temp\\node-debug-callback-8f4fe4101c69c4e3"}" && "C:\Program Files\nodejs\node.exe" .\node_modules\jest\bin\jest --runInBand d:\omitted\src\app\order\order\order.component.spec.ts --testNamePattern "should create" "
```

Output
```
Debugger attached.
No tests found, exiting with code 1
Run with `--passWithNoTests` to exit with code 0
In D:\omitted
  2701 files checked.
  testMatch: **/*(*.)@(spec|test).[tj]s?(x) - 198 matches
  testPathIgnorePatterns: \\node_modules\\ - 2701 matches
  testRegex:  - 0 matches
Pattern: d:\omitted\src\app\order\order\order.component.spec.ts - 0 matches
Waiting for the debugger to disconnect...
```

I suspect the problem lies with the provided parameter `d:\omitted\src\app\order\order\order.component.spec.ts` that does not match any of the test files. If i use the same console command as above but replace `d:\omitted\src\app\order\order\order.component.spec.ts` with `order.component.spec.ts` the test is found.
### Expected Behavior

The code lens feature should find the test that was clicked.

### Actual Behavior
no test found

**Comment by connectdotz** [comment]
Sorry about this, this is most likely related to #694. We just released 4.0.2 that should address this issue, please let us know if it didn't.
