### ISSUE TITLE
Unable to debug tests using the configuration generated by the wizard

### ISSUE THREAD

**Issue by pbalenzuela** [jest-community/vscode-jest#713]
### Environment

1. `vscode-jest version`: 4.0.2
2. `node -v`: v14.15.4
3. `yarn --version`: 1.22.5
4. `npm ls jest`: jest@26.6.0
5. your vscode-jest settings if customized:
    - jest.jestCommandLine? yarn test
6. Operating system: windows 10

### Prerequisite
- are you able to run jest test from the command line? yes
- how do you run your tests from the command line?  yarn test

### Steps to Reproduce

Click on debug to start debugging a given test

## This is working
No `vscode-jest-tests` configuration in `launch.json`

`package.json` relevant content:

```
{
  "scripts": {
    "test": "react-scripts test"
  }
}
```
works without any problems

## This is not working
`launch.json`
```
{
  "configurations": [
    {
      "type": "node",
      "name": "vscode-jest-tests",
      "request": "launch",
      "console": "integratedTerminal",
      "internalConsoleOptions": "neverOpen",
      "disableOptimisticBPs": true,
      "runtimeExecutable": "yarn",
      "protocol": "inspector",
      "cwd": "${workspaceFolder}",
      "args": ["test", "test", "--runInBand", "--watchAll=false"]
    }
  ]
}

```
results
```
$  cd E:\\Repository\\Tatango\\backend\\projects\\frontend ; /usr/bin/env CI=vscode-jest-tests 'NODE_OPTIONS=--require "c:/Users/Pato/AppData/Local/Programs/Microsoft VS Code/resources/app/extensions/ms-vscode.js-debug/src/bootloader.bundle.js" 
--inspect-publish-uid=http' 'VSCODE_INSPECTOR_OPTIONS={"inspectorIpc":"\\\\.\\pipe\\node-cdp.5800-14.sock","deferredMode":false,"waitForDebugger":"",
"execPath":"C:\\Program Files\\nodejs\\node.exe","onlyEntrypoint":false,"autoAttachMode":"always","fileCallback":"
C:\\Users\\Pato\\AppData\\Local\\Temp\\node-debug-callback-08d1e4d8362f4414"}' "C:\\Program Files (x86)\\Yarn\\bin\\yarn.cmd" test test --runInBand --watchAll=false --testNamePattern "index running with mocked api should render a table with Name, Current Usage and Actions columns fetching data properly" --runTestsByPath E:\\Repository\\Tatango\\backend\\projects\\frontend\\src\\domain\\MyAccount\\CouponCodeGroups\\List\\index.integration.test.js
'C:\Program' is not recognized as an internal or external command,
operable program or batch file.
```

## This is not working either
`launch.json`
```
{
  "configurations": [
    {
      "type": "node",
      "name": "vscode-jest-tests",
      "request": "launch",
      "console": "integratedTerminal",
      "internalConsoleOptions": "neverOpen",
      "disableOptimisticBPs": true,
      // "runtimeExecutable": "yarn",
      "protocol": "inspector",
      "cwd": "${workspaceFolder}",
      "args": ["test", "test", "--runInBand", "--watchAll=false"],
      "windows": { "program": "yarn" }
    }
  ]
}
```

results

```
  /usr/bin/env CI=vscode-jest-tests 'NODE_OPTIONS=--require "c:/Users/Pato/AppData/Local/Programs/Microsoft VS Code/resources/app/extensions/ms-vscode.js-debug/src/bootloader.bundle.js" --inspect-publish-uid=http' 'VSCODE_INSPECTOR_OPTIONS={"inspectorIpc":"\\\\.\\pipe\\node-cdp.5800-15.sock","deferredMode":false,"waitForDebugger":"","execPath":"C:\\Program Files\\nodejs\\node.exe","onlyEntrypoint":false,"autoAttachMode":"always","fileCallback":"C:\\Users\\Pato\\AppData\\Local\\Temp\\node-debug-callback-c786b8c6740bfc39"}' "C:\\Program Files\\nodejs\\node.exe" yarn test test --runInBand --watchAll=false --testNamePattern "index running with mocked api should render a table with Name, 
Current Usage and Actions columns fetching data properly" --runTestsByPath E:\\Repository\\Tatango\\backend\\projects\\frontend\\src\\domain\\MyAccount\\CouponCodeGroups\\List\\index.integration.test.js 
Debugger attached.
Waiting for the debugger to disconnect...
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'E:\Repository\Tatango\backend\projects\frontend\yarn'
←[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:725:27)←[39m
←[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)←[39m
←[90m    at internal/main/run_main_module.js:17:47←[39m {
  code: ←[32m'MODULE_NOT_FOUND'←[39m,
  requireStack: []
}

```

**Comment by connectdotz** [comment]
is "C:\\Program Files (x86)\\Yarn\\bin\\yarn.cmd" the correct path for yarn? try to replace it with the correct absolute path, maybe vscode debugger somehow not able to resolve the yarn path correctly in your environment...? 

BTW, looks like there are 2 "test" in the "args", if the wizard does that then it is a bug, you only need one, feel free to edit it.

**Comment by pbalenzuela** [comment]
The path is correct. I even tried to have a copy in the root directory. I tried "c:\Yarn\yarn.cmd" without any luck
In regards to the double "test" in the args, yes, that has been introduced by the wizard

**Comment by connectdotz** [comment]
> I tried "c:\Yarn\yarn.cmd" without any luck

How about uppercae C: "C:\Yarn\yarn.cmd"? 

This one is weird, as "yarn" worked fine in windows as far as we know. There might be something unique about your system setup (did you change the vscode shell setting by any chance?)... The config is executed/translated by vscode debugging system, we have little control over it, so I am as puzzled as you are at why vscode debugger could not execute yarn...

> In regards to the double "test" in the args, yes, that has been introduced by the wizard

Yes, this one we can definitely improve upon. 😄 Thanks for rasing this to our attention.

**Comment by pbalenzuela** [comment]
A few things to consider:

This problem is new to `4.x.x`
This used to work with `3.2.0`

I couldn't define a valid configuration at `launch.json` but it works without one

**Comment by pbalenzuela** [comment]
I made it work after all. These are the 2 alternatives that worked:

1. Copied the contents of the yarn (not just `yarn/bin` to the root folder) and updated the `path` env variable (be sure to have just one configured considering both `system` and `user` variables) to use this location instead.

Notice that this problem has been introduced after using `.msi` installer

2. Completely removed the `.msi` installation and installed it with the recommended way
`npm install --global yarn`

https://classic.yarnpkg.com/en/docs/install/#windows-stable
