### ISSUE TITLE
Unable to add breakpoint in VSCode using mouse after setting coverage as "GutterFormat"

### ISSUE THREAD

**Issue by sachin-agarwal-by** [jest-community/vscode-jest#716]
I am not able to add breakpoint in VS Code once I upgraded VScode-Jest to 4.0.2 and using the "jest.coverageFormatter": "GutterFormatter".

Please help.

**Comment by connectdotz** [comment]
this is expected, please see [Customization > Details > GutterFormatter ](https://github.com/jest-community/vscode-jest#coverageFormatter).

**Comment by sachin-agarwal-by** [comment]
@connectdotz  I cant see any where in above link https://github.com/jest-community/vscode-jest#coverageFormatter where it mention its expected that we cant keep breakpoint if we set "jest.coverageFormatter": "GutterFormatter" property ..

Please correct me if  am wrong.

**Comment by connectdotz** [comment]
please click on the arrow in front of the "coverageFormatter" to expand the details...

**Comment by sachin-agarwal-by** [comment]
great thaks.
