### ISSUE TITLE
Feature - Run jest with specified node version from .nvmrc file

### ISSUE THREAD

**Issue by Vadorequest** [jest-community/vscode-jest#72]
Since the plugins starts without allowing the user to specify what version of node should be used, and use the default selected version in its own process, it is not yet possible to select what version of node should be used.

In my case, my default nvm node version is 4.x. But my project has a .nvmrc with `6.9.1` in it. But Jest uses the default one. _(which makes the whole extension unusable since it crashed instantly)_

Would it be possible to either specify what path of node we want Jest to use, or, more simply, run a `nvm use` before the plugin starts if there is a `.nvmrc` file in the root folder?

**Comment by orta** [comment]
This seems reasonable to me, it'll have to go in jest-editor-support ( which has just had some changes related to this https://github.com/facebook/jest/pull/2817 )

**Comment by liqwid** [comment]
Definitely needed, current node version management is hard.

Also please update README that to change node version for tests one has to do
`nvm alias default $REQUIRED_NODE_VERSION`

**Comment by orta** [comment]
PRs welcome 👍

**Comment by roni-frantchi** [comment]
I know this issue is pretty old, is there a proposed solution or suggested workaround on how to get the watch test use the right node version using nvm?

For what it's worth, when using the `debug` launch lens, it uses the node version specified in in `launch.json`, so that works. But the watched test seems to not be using launch..?

**Comment by Jamelle-Boose** [comment]
> For what it's worth, when using the `debug` launch lens, it uses the node version specified in in `launch.json`, so that works. But the watched test seems to not be using launch..?

Same. @orta how do I get jest in watch mode to use the node version specified in `launch.json`?

**Comment by PixelDuck** [comment]
I am also looking for a solution to use this plugin with nvm...

**Comment by TENsaga** [comment]
same here, watch not working

**Comment by connectdotz** [comment]
During debugging, this extension uses vscode's debug infrastructure that used launch.json; during the regular test run/watch it spawns a node process instead. It would default to the node version from your default shell... I use nvm and it works fine. Do you guys actually want to use a different node version than your default nvm?

**Comment by mjpieters** [comment]
Yes, I'd want to use the version specified in the `.nvmrc` file, not the shell default.

**Comment by sampalmer** [comment]
I got it working using [a startup script](https://github.com/microsoft/vscode/issues/1895#issuecomment-248661179):

1. Create a `node.sh` wrapper script to set up the Node version from `.nvmrc`:
  ```shell
  #!/bin/zsh
  source ~/.zshrc
  nvm run $*
  ```

**Comment by mjpieters** [comment]
>     1. Create a `node.sh` wrapper script to set up the Node version from `.nvmrc`. (Update shebang and `source` line to match your shell.)
>        ```shell
>        #!/bin/zsh
>        source ~/.zshrc
>        nvm exec $*
>        ```

Instead of creating your own script, you can use `~/.nvm/nvm-exec` for this:

```json
{
    "jest.jestCommandLine": "~/.nvm/nvm-exec npx test"
}
```

**Comment by giovannipds** [comment]
If you use `zsh` plus `nvm` auto version switch, you can simply:

```json
"jest.jestCommandLine": "source ~/.zshrc && nvm exec $* && yarn test"
```
Of course switching to `npm run test`, `npx test`, as you wish.

Also not sure if this is needed but it's possible:
```json
"jest.shell": "/bin/zsh",
```

**Comment by connectdotz** [comment]
I'm closing the issue as the community has suggested many ways to embed the nvm selection in the `jest.jestCommandLine`.
