### ISSUE TITLE
Exception raised: Process failed: spawn /bin/sh ENOENT

### ISSUE THREAD

**Issue by Ranguna** [jest-community/vscode-jest#729]
### Environment

1. `vscode-jest version`: 4.0.2
2. `node -v`: v12.19.0
3. `npm -v`: 6.14.8
4. `npm ls jest`:
```
subfolder@1.0.0 /home/luis/my/folder/jest-enoent/subfolder
└── jest@27.0.4
```
5. your vscode-jest settings if customized:
```
{
  "jest.rootPath": "${workspaceFolder}/subfolder",
  "jest.jestCommandLine": "npm t --"
}
```
6. Operating system: Arch Linux running on Linux 5.12.9-arch1-1

### Prerequisite
- are you able to run jest test from the command line? yes
- how do you run your tests from the command line? (for example: `npm run test` or `node_modules/.bin/jest`) npm t

### Steps to Reproduce

1. Create a typescript project in a subfolder of your workspace.
2. Change the jest extension root path to point into the subfolder.
3. Run tests with the extension.

Repo: https://github.com/Ranguna/jest-enoent

### Relevant Debug Info

[Extension Host] [jest-enoent/ListTestFileListener] not-test onTerminalError: Process failed: spawn /bin/sh ENOENT

### Expected Behavior

The tests to run on the extension.

### Actual Behavior

Got this in the output tab:
Exception raised: Process failed: spawn /bin/sh ENOENT

**Comment by connectdotz** [comment]
I think this might be a setting issue, `jest.rootPath` doesn't interpret vscode variable such as `${workspaceFolder}`, however you can just use a relative path instead: `"jest.rootPath": "subfolder"`.

**Comment by Ranguna** [comment]
You are an angel @connectdotz !
That worked, thank you very much !
