### ISSUE TITLE
No code completion/hints (aka "intellisense")

### ISSUE THREAD

**Issue by EdSF** [jest-community/vscode-jest#731]
### Environment

1. `vscode-jest version`: 4.0.3
2. `node -v`: v12.19.0
3. `npm -v` or `yarn --version`: npm 6.14.8
4. `npm ls jest` or `npm ls react-scripts` (if you haven’t ejected):  `jesttest@1.0.0 D:\Files\Projects\JestTest  --jest@27.0.4`
5. your vscode-jest settings if customized:
    - jest.jestCommandLine? "npx jest"
    - jest.autoRun? default (true)
    - anything else that you think might be relevant? Jest is only a dev dependency (not global)
6. Operating system: Windows 10

### Prerequisite
- are you able to run jest test from the command line? Yes - `npx jest` (jest is **not** global)
- how do you run your tests from the command line? (for example: `npm run test` or `node_modules/.bin/jest`) `npm test ( `"test": "jest"` or just `npx jest`

### Steps to Reproduce

- Just follow the ["getting started" guide with the `sum.js` and `sum.test.js`](https://jestjs.io/docs/getting-started), nothing more
- note the --save-dev (jest is not installed globally)
- run tests either via: 
   - `npm test` (scripts -> `test: "jest"`),  or 
   - `npx jest`

As you write `sum.test.js` - there is no "code completion" (aka "intellisense") _relevant to Jest_  - suggestions are **not** related to jest. The only time you'll get something related to jest is if you've used the command (history). I'm a n00b and end up having to go to Jest documentation - specifically `expect`

Everything else "works"

- indicators of passing tests (check mark)  
![image](https://user-images.githubusercontent.com/636166/122440995-f551a000-cf51-11eb-9c78-6cc5272b8703.png)
- VS Code task bar:  
![image](https://user-images.githubusercontent.com/636166/122441122-1914e600-cf52-11eb-9400-f22058bcf6f2.png)
- coverage, etc. are all good....

### Expected Behavior
Unsure what the actual behavior is since I've never gotten code completion/suggestion to work. I'm only 'expecting' this because of the animation displayed in the extension (showing code completion/suggestion working smoothly)

### Actual Behavior

As above, "everything" else seems to be fine except for this reported issue

--- 

The fastest (and the most fun) way to resolve the issue is to submit a pull-request yourself. If you are interested, feel free to check out the [contribution guide](https://github.com/jest-community/vscode-jest/CONTRIBUTING.md), we look forward to seeing your PR...

**Comment by connectdotz** [comment]
there is an existing thread you might find helpful: #686

**Comment by EdSF** [comment]
> there is an existing thread you might find helpful: #686

Resolved: `npm i -D @types/jest`

Thank you!
