### ISSUE TITLE
Test: Run All Tests returns workspace error on new VS Code version

### ISSUE THREAD

**Issue by angelod1as** [jest-community/vscode-jest#735]
### Environment

1. `vscode-jest version`: v4.0.3
2. `node -v`: 14.15.3
3. `npm -v` or `yarn --version`: 1.22.10
4. `npm ls jest` or `npm ls react-scripts` (if you haven’t ejected): 
```
Project
└─┬ react-scripts@3.4.4
  └── jest@24.9.0 
```

5. your vscode-jest settings if customized:
  ```
"jest.showCoverageOnLoad": true,
```

6. Operating system: Pop!_OS 20.04 LTS x86_64

7. VS Code Version: 1.57.1

### Prerequisite
- are you able to run jest test from the command line? Yes.
- how do you run your tests from the command line? (for example: `npm run test` or `node_modules/.bin/jest`) `yarn test --watchAll`, which runs `react-app-rewired test --env=jsdom --no-cache --watchAll`

### Steps to Reproduce

Unfortunately I can't disclose the repository.

- Update VSCode to latest version (1.57.1)
- Install vscode-jest
- Open a test file, write a test, save it.
- See the test run and end in success or fail
- Run "Test: Run all tests"
- See error message: `No tests found in this workspace. You may need to install a test provider extension`

### Relevant Debug Info

The tests run as they should when a file is saved. This error only throws when I run `Test: Run all tests`. When I run `Stop All Runners` then `Start All Runners`, all the tests run. I updated VS Code this morning, yesterday everything was running all right. No other update was made other than VS Code

### Expected Behavior

Tests should run when `Test: Run all tests` is called.

### Actual Behavior

Error `No tests found in this workspace. You may need to install a test provider extension` is shown

**Comment by connectdotz** [comment]
`"Test: Run all tests"` is not a vscode-jest command, perhaps you were thinking about `"Jest: Run all tests"`?

**Comment by connectdotz** [comment]
feel free to reopen the issue if you still have problems.
