### ISSUE TITLE
Use new Testing API

### ISSUE THREAD

**Issue by agos** [jest-community/vscode-jest#744]
As of 1.59, Visual Studio has finalized a set of APIs dedicated to Testing Extensions. It'd be cool if vscode-jest [adopted them](https://code.visualstudio.com/api/extension-guides/testing), to gain the benefit of the native UI

**Comment by connectdotz** [comment]
yup, that was the plan, see #742, feel free to try the rc and let us know how it works for you...

**Comment by agos** [comment]
thanks for pointing that out! I'm going to take it for a spin, sorry for opening an unnecessary issue!
