### ISSUE TITLE
Stop message from appearing every time I open a workspace

### ISSUE THREAD

**Issue by garyking** [jest-community/vscode-jest#755]
How can I stop the `vscode-jest now supports the official vscode test explorer!!` message from appearing, every time I open a workspace? Shouldn't it only appear once, then never again?

**Comment by connectdotz** [comment]
good point

**Comment by Js-Brecht** [comment]
Not to mention that when you hit the `X`, it opens the browser window anyway???  Seems like every time I open VSCode, I now have to kill new browser windows

**Comment by Salzian** [comment]
Seems like theres missing

1. Some sort of memorisation logic to remember that the user saw this message already.
2. Another else branch for when the user clicks the `X`. Right now else catches both the `See details` button and the `X`. See: https://github.com/jest-community/vscode-jest/blob/12dca209c0315a87cb0ec95f543fd3b124ac2c7a/src/extensionManager.ts#L286-L297

Also the double `!!` in the message is just the cherry on top to successfully annoy me 😂

**Comment by connectdotz** [comment]
all good comments, sorry for this issue, PR (#756) updated, 4.1.1 will be released soon. thanks.
