### ISSUE TITLE
Typo in `README.md`

### ISSUE THREAD

**Issue by roottool** [jest-community/vscode-jest#766]
## Overview

Some sentences have typo in `README.md`.
And as same, the other sentences have trailing whitespaces in `README.md` which can be trimmed.

### Environment

1. `vscode-jest version`: 4.1.2
2. `node -v`: 14.16.1
3. `yarn --version`: 1.22.10
4. `npm ls jest`: 26.6.3
5. your vscode-jest settings if customized:
    - Not customaized
6. Operating system: Windows 11 + WS2 Debian 10.10

### Prerequisite
- are you able to run jest test from the command line? Yes
- how do you run your tests from the command line? (for example: `npm run test` or `node_modules/.bin/jest`) `npm run test`

### Steps to Reproduce

1. Open `README.md`

### Relevant Debug Info

- Typo
1. https://github.com/jest-community/vscode-jest/blob/a7573b089a206d42102e2cb39c1e70c3c83b87b1/README.md#L8
2. https://github.com/jest-community/vscode-jest/blob/a7573b089a206d42102e2cb39c1e70c3c83b87b1/README.md#L11
3. https://github.com/jest-community/vscode-jest/blob/a7573b089a206d42102e2cb39c1e70c3c83b87b1/README.md#L13
4. https://github.com/jest-community/vscode-jest/blob/a7573b089a206d42102e2cb39c1e70c3c83b87b1/README.md#L222
- Trailing whitespaces which can be trimmed
1. https://github.com/jest-community/vscode-jest/blob/a7573b089a206d42102e2cb39c1e70c3c83b87b1/README.md#L1
2. https://github.com/jest-community/vscode-jest/blob/a7573b089a206d42102e2cb39c1e70c3c83b87b1/README.md#L82

### Expected Behavior

- `explorer`
- Trailing whitespaces which can be trimmed is going to trim.

### Actual Behavior

- `explore`
- Trailing whitespaces which can be trimmed exist. For example, `# vscode-jest  `

--- 

The fastest (and the most fun) way to resolve the issue is to submit a pull-request yourself. If you are interested, feel free to check out the [contribution guide](https://github.com/jest-community/vscode-jest/CONTRIBUTING.md), we look forward to seeing your PR...

**Comment by connectdotz** [comment]
thanks
