### ISSUE TITLE
Test Explorer shows tests as running which aren't

### ISSUE THREAD

**Issue by andrewplummer** [jest-community/vscode-jest#767]
### Environment

1. `vscode-jest version`: 1.60.0
2. `node -v`: v14.15.1
3. `npm -v` or `yarn --version`: 1.22.5
4. `npm ls jest` or `npm ls react-scripts` (if you haven’t ejected): jest@26.6.3
5. your vscode-jest settings if customized:
```
  "jest.enableCodeLens": false,
  "jest.jestCommandLine": "yarn test",
```

6. Operating system: OSX 11.5.2

### Issue

When viewing the test explorer while in watch mode all the tests, files, parent folders, and the root itself appear to be running even though they aren't (only specific tests are being re-run). You could make a case for the parent folders to appear as running (I personally would not like to see that, instead the initial "enqueued" status makes more sense), however it appears that even child tests are running which are not. In the video, only 7 tests have run but it appears that much more are, so none of the other leaf nodes should appear as running. The UI also jumps around quite a bit between running/finished states making it rather distracting, although I realize there may not be a lot you can do about that.

https://user-images.githubusercontent.com/74646/132733578-8695af96-7280-4d68-a35d-69675ac9e260.mov

**Comment by connectdotz** [comment]
Yeah, it is a known limit. In watch mode, the external process (jest watchman) determines what tests should be run, thus this extension does not know until the test run is completed and that is when it can start to update the status of the tests... 

We could delay the "busy" marking until we know which tests are actually running, but then if that took a long time, users might be facing no indication of anything is happening, which has been an issue before... Thus it was decided to mark the workspace "busy" at the start of the process (as currently there is no separate 'process busy' vs "test-item busy" mechanism)  followed by updating the details after the run is completed. 

It's true that the jumping around in the TestExplorer can be annoying, we are working with vscode team to see if they can improve that, maybe allow it to be "locked" at the current position for example...

**Comment by andrewplummer** [comment]
Yeah I was kind of assuming as much. It looks like Jest is working on a [programmatic interface](https://github.com/facebook/jest/tree/main/packages/jest-core) that might help here but it seems to be not ready yet. As for the jumping around I also was assuming that's vscode related... good to know it's been noticed 👍  ... I'll close this one for now then.

**Comment by andrewplummer** [comment]
Oh awesome that totally helps! 👍
