### ISSUE TITLE
Attach debugger.

### ISSUE THREAD

**Issue by alloy** [jest-community/vscode-jest#77]
Would it be possible to attach a debugger to the tests being run? I like to set breakpoints in tests while doing TDD.

**Comment by orta** [comment]
2 things:

In our repos I've been [adding](https://github.com/danger/danger-js/blob/master/.vscode/launch.json#L49-L64): 

```
    }, {
        "name": "Run Tests With Debugger (slower, use npm run watch for normal work)",
        "type": "node",
        "request": "launch",
        "port": 5858,
        "address": "localhost",
        "stopOnEntry": false,
        "runtimeExecutable": null,
        "runtimeArgs": [
            "--debug-brk",
            "./node_modules/.bin/jest",
            "-i"
        ],
        "cwd": "${workspaceRoot}",
        "sourceMaps": true
    }]

```

which means normal runs are faster. Then you do  debug to get it in launch mode running those tests. 


---

When I last did serious work on this, you could only do 1 debugger at a time. So debugging tests meant killing your current session.

 VS code 1.9 added multiple debugging env support, so now we could have a permanently connected debugger to the tests. Perhaps this is worth trying out.

**Comment by offero** [comment]
The vscode go extension adds a link above the test. It would be awesome for this plugin to do something similar where you can click on the link to run the test in debug mode.

**Comment by stephtr** [comment]
I'm closing it since debugging of tests has been meanwhile made available, [as documented](https://github.com/jest-community/vscode-jest#how-do-i-debug-tests).
