### ISSUE TITLE
Performance repro with test.each(table)

### ISSUE THREAD

**Issue by lrowe** [jest-community/vscode-jest#770]
### Environment

1. `vscode-jest version`: v4.1.2
2. `node -v`: v16.7.0 (homebrew Arm)
3. `npm -v` or `yarn --version`: nom 7.20.3
4. `npm ls jest` or `npm ls react-scripts` (if you haven’t ejected): jest@27.1.1
5. your vscode-jest settings if customized:
    - jest.jestCommandLine? [fill]
    - jest.autoRun? [fill]
    - anything else that you think might be relevant? [fill]
6. Operating system: Arm Mac

### Prerequisite
- are you able to run jest test from the command line? Yes
- how do you run your tests from the command line? (for example: `npm run test` or `node_modules/.bin/jest`) npm test

### Steps to Reproduce

Gist with all files: https://gist.github.com/lrowe/a3afd929268a396a0c83d17e2bed8102

Created with:
```
npm init
npm install --save-dev jest
# Edit package.json so that scripts.test = "jest"
```
repro.test.js
```js
const table = Array.from({ length: 200 }, (_, i) => i);
test.each(table)("%s", (n) => {
  expect(n).toEqual(n);
});
```

To reproduce increment the table length by one in repro.test.js.

### Expected Behavior

Tests should run almost instantly as they do when I run `npm test` on the command line (`time npm test` shows 0.603 total.)

### Actual Behavior

VSCode spends 10-20 seconds with the UI barely responsive and the Code Helper (Renderer) pinned at 100% cpu.

**Comment by connectdotz** [comment]
indeed... this seems to be related to vscode TestExplorer rendering. The performance is normal if I turned off testExplorer : `"jest.testExplorer": {"enabled": false}`

**Comment by connectdotz** [comment]
looks like this is fixed in the vscode insider version, we should close this once vscode 1.62 is released.
