### ISSUE TITLE
Extension breaks when using CRACO

### ISSUE THREAD

**Issue by JeffEmery** [jest-community/vscode-jest#793]
### Environment

1. `vscode-jest version`: v4.2.1
2. `node -v`: v14.15.1
3. `npm -v` or `yarn --version`: npm 6.14.8
4. `npm ls jest` or `npm ls react-scripts` (if you haven’t ejected): `-- react-scripts@4.0.3
5. your vscode-jest settings if customized:
    - jest.jestCommandLine? default
    - jest.autoRun? default
    - anything else that you think might be relevant? 
6. Operating system: Microsoft Windows [Version 10.0.19041.1288]

### Prerequisite
- are you able to run jest test from the command line? yes with both "craco test" and "react-scripts test"
- how do you run your tests from the command line? (for example: `npm run test` or `node_modules/.bin/jest`) npm run test

### Steps to Reproduce

This is a very simple repo that was created with [Create React App](https://github.com/facebook/create-react-app) and then adding [CRACO](https://github.com/gsoft-inc/craco).

[Repository with reproduced results](https://github.com/JeffEmery/reactjest)

### Relevant Debug Info

  ● Test suite failed to run

    SyntaxError: C:\code\junk\reactjest\src\App.test.js: Support for the experimental syntax 'jsx' isn't currently enabled (5:10):

      3 |
      4 | test('renders learn react link', () => {
    > 5 |   render(<App />);
        |          ^
      6 |   const linkElement = screen.getByText(/learn react/i);
      7 |   expect(linkElement).toBeInTheDocument();
      8 | });

    Add @babel/preset-react (https://git.io/JfeDR) to the 'presets' section of your Babel config to enable transformation.
    If you want to leave it as-is, add @babel/plugin-syntax-jsx (https://git.io/vb4yA) to the 'plugins' section to enable parsing.

      at Parser._raise (node_modules/@babel/parser/src/parser/error.js:147:45)

### Expected Behavior

Should compile and run tests properly with the following
***breaks***

```json
  "scripts": {
    "start": "craco start",
    "build": "craco build",
    "test": "craco test",
    "eject": "react-scripts eject"
  },
```

The original react-scripts does work
***works***

```json
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
```

### Actual Behavior

Tests fail to run in the Test Explorer

--- 

The fastest (and the most fun) way to resolve the issue is to submit a pull-request yourself. If you are interested, feel free to check out the [contribution guide](https://github.com/jest-community/vscode-jest/CONTRIBUTING.md), we look forward to seeing your PR...

**Comment by connectdotz** [comment]
@JeffEmery I tried your repo, 2 things:
1. the repo didn't have a craco config file so I was not even able to run tests in terminal, figure you probably forgot to check-in the config... I created a dummy one to make sure jest worked from command line in the terminal.
2. the extension can auto-config react apps but not CRACO. All you have to do is to customize the [jest.jestCommandLine](https://github.com/jest-community/vscode-jest#jestcommandline) setting, you can do that via the [setup wizard](https://github.com/jest-community/vscode-jest/blob/master/setup-wizard.md) or manually edit your vscode settings. I set `jest.jestCommandLine` to `yarn test` and all seems to work just fine

**Comment by JeffEmery** [comment]
Thank you. I assumed it was something that simple, I was overlooking. I added a tip to a PR in the README Troubleshooting section in case you want to add it.
