### ISSUE TITLE
Extension not working? Help!

### ISSUE THREAD

**Issue by JordanLongstaff** [jest-community/vscode-jest#801]
### Environment

1. `vscode-jest version`: 4.2.1
2. `node -v`: 14.17.5
3. `npm -v` or `yarn --version`: 6.14.14 and 1.22.17, respectively
4. `npm ls jest` or `npm ls react-scripts` (if you haven’t ejected): `jest@26.6.3`
5. your vscode-jest settings if customized:
    - jest.jestCommandLine: `node_modules/.bin/jest`
    - jest.rootPath: `client`
6. Operating system: macOS Monterey 12.0.1

### Prerequisite
- are you able to run jest test from the command line? yes
- how do you run your tests from the command line? (for example: `npm run test` or `node_modules/.bin/jest`) `jest path/to/test/file.test.ts` (`node_modules/.bin` is added to PATH)

### Steps to Reproduce

My VS Code repository has two different code projects, a server written in Python and contained in the `server` directory, and a client written in Coffeescript and Typescript and contained in the `client` directory. The `client` directory also contains `node_modules`, `package.json` and `yarn.lock`, hence my customized settings.

There might be something that I don't get about how to set it up properly, but I cannot get the extension to work in any capacity. I do not see Jest in the status bar, nor do I see any Jest tests in the Test Explorer, nor do I even see Jest appear as a tab in the `Output` window. It's as if the extension isn't even installed, even though it clearly is. I've also tried adding `client/` in front of the aforementioned `jest.jestCommandLine` setting and that didn't work.

### Relevant Debug Info

N/A

### Expected Behavior

All of the proclaimed indicators of the working, active existence and functionality of the extension in my VS Code environment should be visible and usable.

### Actual Behavior

None of them actually are.

--- 

The fastest (and the most fun) way to resolve the issue is to submit a pull-request yourself. If you are interested, feel free to check out the [contribution guide](https://github.com/jest-community/vscode-jest/CONTRIBUTING.md), we look forward to seeing your PR...

**Comment by connectdotz** [comment]
sounded like the extension is not automatically activated, which is triggered by these [activation events](https://github.com/jest-community/vscode-jest/blob/19e9269c7c2e8f81f2a51cc691184565c3ded375/package.json#L33):
```json
"activationEvents": [
    "workspaceContains:jest.config.js",
    "workspaceContains:jest.json",
    "workspaceContains:node_modules/.bin/jest",
    "workspaceContains:node_modules/react-scripts/node_modules/.bin/jest",
    "workspaceContains:node_modules/react-native-scripts",
    "onCommand:io.orta.jest.start"
  ],
```

If your project is a multi-root workspace, i.e. the "client" is a workspace folder (the recommended approach), then it would probably work just fine; otherwise, you would need to trigger the extension activation via the command: "Jest: Start All Runners" from the command palette. 

Let me know if that did not resolve your issue.

**Comment by JordanLongstaff** [comment]
It appears to be resolved! Thanks!
