### ISSUE TITLE
Jest tests being run on file save despite watch mode being disabled

### ISSUE THREAD

**Issue by JordanLongstaff** [jest-community/vscode-jest#802]
### Environment

1. `vscode-jest version`: 4.2.1
2. `node -v`: 14.17.5
3. `npm -v` or `yarn --version`: 6.14.14 and 1.22.17, respectively
4. `npm ls jest` or `npm ls react-scripts` (if you haven’t ejected): `jest@26.6.3`
5. your vscode-jest settings if customized:
    - jest.autoRun: `{ "watch": "false", "onStartup": ["all-tests"] }`
6. Operating system: macOS Monterey 12.0.1

### Prerequisite
- are you able to run jest test from the command line? yes
- how do you run your tests from the command line? (for example: `npm run test` or `node_modules/.bin/jest`) `jest path/to/test/file.test.ts` (`node_modules/.bin` is added to PATH)

### Steps to Reproduce

All I do is save a file, and then Jest suddenly runs all of the available tests (and does so multiple times, which really bogs down VS Code). This is in spite of the fact that I have explicitly disabled watch mode entirely, as indicated by the above setting.

### Expected Behavior

The tests should not be running in response to a code file being saved.

### Actual Behavior

They are.

--- 

The fastest (and the most fun) way to resolve the issue is to submit a pull-request yourself. If you are interested, feel free to check out the [contribution guide](https://github.com/jest-community/vscode-jest/CONTRIBUTING.md), we look forward to seeing your PR...

**Comment by JordanLongstaff** [comment]
`"jest.autoRun": "off"` works fine, but it's the previous setting that doesn't, which is disappointing because it means that I can't make Jest tests run when VS Code starts. Both autorun modes are referred to as `auto-run-off`, and yet one of them is misleading because it is inaccurate.

**Comment by connectdotz** [comment]
Try false without quotes

**Comment by JordanLongstaff** [comment]
Jeez, I feel so dumb. Thanks!
