### ISSUE TITLE
disabledWorkspaceFolders does not prevent jest sessions from being started

### ISSUE THREAD

**Issue by borisyordanov** [jest-community/vscode-jest#805]
### Environment

1. `vscode-jest version`: 4.2.1
2. `node -v`: 14.18.2
3. `npm -v` or `yarn --version`: npm 7.24.2
4. `npm ls jest` or `npm ls react-scripts` (if you haven’t ejected): jest@26.6.3
5. your vscode-jest settings if customized:
  ![Code_TnuCNKJJtU](https://user-images.githubusercontent.com/12392666/145127782-5ed67ee6-2c1e-4504-95c5-ec4463c20b35.png)
6. Operating system: Linux & Windows

### Prerequisite
- are you able to run jest test from the command line? yes
- how do you run your tests from the command line? npm run test

### Steps to Reproduce

1. Add any folder to disabledWorkspaceFolders
2. Check that a Jest(folderName) tab is available in the output pane in VSCode
3. The output might contain errors due to improper setup

### Expected Behavior

- if I workspace folder is listed under disabledWorkspaceFolders `vscode-jest` completely ignores it

### Actual Behavior

-  `vscode-jest` tries to run tests in all workspaces folders even the disabled ones. The ignored folders are only removed from the test explorer.

--- 

The fastest (and the most fun) way to resolve the issue is to submit a pull-request yourself. If you are interested, feel free to check out the [contribution guide](https://github.com/jest-community/vscode-jest/CONTRIBUTING.md), we look forward to seeing your PR...

**Comment by borisyordanov** [comment]
I can create a reproducible demo later this week if it'd be helpful.

**Comment by connectdotz** [comment]
hi @borisyordanov the image is very helpful. Looks like your setting has an extra space at the end `"jest.disabledWorkspaceFolders ":`, try without and it should work...

**Comment by borisyordanov** [comment]
@connectdotz you're absolutely right. I was wondering why VSCode had underlined that setting, but I couldn't figure out why. No idea how I missed that!

Also, thank you for this extension. It's immensely useful. I'm working on some blog posts on DX where I'll be focusing on `vscode-jest`. Once I'm more acquainted with it i hope I'll be able to contribute!
