### ISSUE TITLE
Keybindings for running test at current caret and re-run last test

### ISSUE THREAD

**Issue by lmeysel** [jest-community/vscode-jest#807]
### Environment

1. `vscode-jest version`: 4.2.1

It would be nice to have keybindings allowing me run/debug the test at the caretcursor position and re-run/debug the last test.

**Comment by connectdotz** [comment]
@lmeysel 

This should already be available via TestExplorer command:

<img width="968" alt="Screen Shot 2022-01-04 at 10 21 38 PM" src="https://user-images.githubusercontent.com/891093/148155749-892f59ef-8d8f-4280-a266-1bd2dab90ef0.png">

Thanks for mentioning this, we added more info at the end of the [commands](https://github.com/jest-community/vscode-jest#commands) section. Please let me know if that solved your issue.

**Comment by lmeysel** [comment]
Thanks, yes this solves my issue. I was not looking for testing* commands but rather jest*, thus i did not find the keybindings 🤦
