### ISSUE TITLE
Auto run single test

### ISSUE THREAD

**Issue by lmeysel** [jest-community/vscode-jest#808]
### Environment

1. `vscode-jest version`: 4.2.1

Autorun feature allows me to autorun the whole test-suite or the test of the recently changed file. It would be nice to autorun just a specific test :)

**Comment by connectdotz** [comment]
@lmeysel 

With [4.3.1](https://github.com/jest-community/vscode-jest#pre-release-v431-) you should be able to run any single test via the TestExplorer menu regardless of autoRun mode. Feel free to give it a try and let me know if it does what you expected.

**Comment by lmeysel** [comment]
No, what I was asking for is to auto-run just a single test/test-group. But this was before I understood there are keybindings for (re)-running the last test. So, at least to me, this is obsolete.

**Comment by connectdotz** [comment]
great
