### ISSUE TITLE
Bug: Jest plugin fails test which local passes. `mockUsers.toString().replaceAll is not a function`

### ISSUE THREAD

**Issue by GeorgeWL** [jest-community/vscode-jest#830]
### Environment

1. `vscode-jest version`: 4.2.1
2. `node -v`: 14.16.1 (though using NVM, when switch to 17.4.0 still see the same error)
3. `npm -v` or `yarn --version`: yarn 1.22.5
4. `npm ls jest` or `npm ls react-scripts` (if you haven’t ejected): jest@26.6.0
5. your vscode-jest settings if customized:
   N/A
6. Operating system: Windows 10 Pro

### Prerequisite
- are you able to run jest test from the command line? Yes
- how do you run your tests from the command line? (for example: `npm run test` or `node_modules/.bin/jest`) `yarn run test` (which runs the following command `node --harmony node_modules/jest/bin/jest.js`

### Steps to Reproduce

Create a test using string.replaceAll() in the test data
Jest plugin says test fails, running Jest in cli does not

[fill]

### Relevant Debug Info

[fill]

### Expected Behavior

[fill]

### Actual Behavior

[fill]

--- 

The fastest (and the most fun) way to resolve the issue is to submit a pull-request yourself. If you are interested, feel free to check out the [contribution guide](https://github.com/jest-community/vscode-jest/CONTRIBUTING.md), we look forward to seeing your PR...

**Comment by connectdotz** [comment]
Looks like you are using the command that is not yet available in the "default" node in your env. I guess that is why you use the `--harmony` flag in the test script. You can try to set your `jest.jestCommandLine` to "yarn test" so it would pick up the same command...
