### ISSUE TITLE
UI: Missing button to run tests (without debug)

### ISSUE THREAD

**Issue by Becold** [jest-community/vscode-jest#831]
### Environment

1. `vscode-jest version`: v4.2.1
2. `node -v`: v16.13.0
3. `npm -v` or `yarn --version`: npm: 8.1.3 / yarn: 1.22.17
4. `npm ls jest`:
```
myproject@0.0.1 C:\Lab\Work\myproject
├── jest@26.6.3
└─┬ ts-jest@26.5.6
  └── jest@26.6.3 deduped
```
5. your vscode-jest settings if customized:
- jest.config.js
```
module.exports = async () => {
  return {
    preset: 'ts-jest',
    collectCoverage: true,
    coverageDirectory: 'coverage',
    coverageThreshold: {
      global: {
        branches: 90,
        functions: 90,
        lines: 90,
        statements: 90
      },
    },
    coverageReporters: [
      'text',
      'lcov',
      'cobertura'
    ],
    reporters: [
      'default',
      ['jest-junit', {
        outputName: 'coverage/junit.xml',
      }],
    ],
    rootDir: './',
    moduleFileExtensions: ['js', 'ts'],
    testMatch: ['**/*.spec.ts'],
    notify: false,
    notifyMode: 'always',
    testPathIgnorePatterns: ['/node_modules', '/dist/', '/coverage'],
    verbose: true,
  };
};
```
6. Operating system: Windows 10 Enterprise N version 21H1 (OS Build 19043.1466)

### Prerequisite
- are you able to run jest test from the command line? yes
- how do you run your tests from the command line? (for example: `npm run test` or `node_modules/.bin/jest`):
`npm test`
with scripts in package.json
```
"scripts": {
  "pretest": "rimraf coverage",
  "test": "jest"
},
```

### Expected Behavior

A button and/or a context menu item to run tests
![image](https://user-images.githubusercontent.com/12863317/150177397-f98ee41a-143d-4b18-9d20-834483b594ce.png)

### Actual Behavior

No button and no context menu item
![image](https://user-images.githubusercontent.com/12863317/150177474-2d9cf76d-c87f-4607-8be3-3733342a1830.png)
![image](https://user-images.githubusercontent.com/12863317/150178365-7857b6bc-ae84-4459-bcef-c3ccdb41b435.png)

**Comment by connectdotz** [comment]
hi @Becold if your workspace folder is in "watch" mode and you are using v4.2.x then it is expected behavior. However, you can switch to the pre-release [4.3.1](https://github.com/jest-community/vscode-jest#pre-release-v431-) that enabled the run button/menu for even the "watch" mode.

**Comment by Becold** [comment]
Hi @connectdotz ,
Indeed, switching vscode-jest extension version to the pre-release version seems to display the run button/menu.
Thank you
