### ISSUE TITLE
Using coverageProvider: "v8" in jest.config.js breaks line-by-line coverage

### ISSUE THREAD

**Issue by mcpower** [jest-community/vscode-jest#842]
### Environment

1. `vscode-jest version`: v4.2.1
2. `node -v`: v16.14.0
3. `npm -v`: 8.3.1
4. `npm ls jest`:
```
vscode-jest-coverage@ /home/mcpower/git/vscode-jest-coverage
└── jest@27.5.1
```
5. No customised vs-code-jest settings
6. Operating system: Ubuntu 20.04 LTS via WSL

### Prerequisite
- are you able to run jest test from the command line? Yes
- how do you run your tests from the command line? `npx jest`

### Steps to Reproduce

Put `coverageProvider: "v8"` in your jest.config.js instead of `coverageProvider: "babel"`.

### Relevant Debug Info

N/A

### Expected Behavior

Line coverage shows the lines which are not covered by tests OR a notification/prompt appears saying to change `coverageProvider` to `"babel"`.

### Actual Behavior

Line coverage shows all green, while the stats at the top of the file show otherwise. No notification/prompt appears, causing user confusion.

(If this can't be fixed, a notification explaining why coverage isn't working would be the next best thing.)

**Comment by connectdotz** [comment]
Yes, v8 is not supported yet (it is still considered experimental in jest), but I agree we should look into it if it is going to be part of jest.

**Comment by connectdotz** [comment]
@EmilyRosina, @mcpower, we have incorporated v8 support in [v5 pre-release](https://github.com/jest-community/vscode-jest/blob/master/release-notes/release-note-v5.md), do you mind giving it a try and letting us know how it works for you? Thanks.
