### ISSUE TITLE
monorepo / npm workspaces / typescript tests not running & failing

### ISSUE THREAD

**Issue by dreamorosi** [jest-community/vscode-jest#843]
### Environment

1. `vscode-jest version`: v4.2.1
2. `node -v`: v14.x / v16.x
3. `npm -v` or `yarn --version`: npm 8.x
4. `npm ls jest` or `npm ls react-scripts` (if you haven’t ejected): 
```sh
aws-lambda-powertools-typescript@0.0.1 /Users/aamorosi/Codes/aws-lambda-powertools-typescript
├── jest@27.5.1
└─┬ ts-jest@27.1.3
  └── jest@27.5.1 deduped 
```
5. your vscode-jest settings if customized:
    - jest.jestCommandLine? N/A
    - jest.autoRun? `default`
    - anything else that you think might be relevant? Monorepo that uses npm workspaces and written in TypeScript
6. Operating system: MacOS

### Prerequisite
- are you able to run jest test from the command line? Yes, both on command line & CI/CD environment
- how do you run your tests from the command line? (for example: `npm run test` or `node_modules/.bin/jest`) `npm t` or `npm run lerna-test`

### Steps to Reproduce

This is the repo: https://github.com/awslabs/aws-lambda-powertools-typescript 

As mentioned, it requires `npm 8.x` 

### Relevant Debug Info

Open below to see output logs:
<details>
> aws-lambda-powertools-typescript@0.0.1 test
> npm run lerna-test "--testLocationInResults" "--json" "--useStderr" "--outputFile" "/var/folders/s7/xzcjrts93cn5_mq16vkcqt794zqxk7/T/jest_runner_aws_lambda_powertools_typescript.json" "--watch" "--no-coverage" "--reporters" "default" "--reporters" "/Users/aamorosi/.vscode/extensions/orta.vscode-jest-4.2.1/out/reporter.js" "--colors"

> aws-lambda-powertools-typescript@0.0.1 lerna-test
> lerna exec -- npm run test "/var/folders/s7/xzcjrts93cn5_mq16vkcqt794zqxk7/T/jest_runner_aws_lambda_powertools_typescript.json" "default" "/Users/aamorosi/.vscode/extensions/orta.vscode-jest-4.2.1/out/reporter.js"

lerna notice cli v4.0.0
lerna info Executing command in 5 packages: "npm run test /var/folders/s7/xzcjrts93cn5_mq16vkcqt794zqxk7/T/jest_runner_aws_lambda_powertools_typescript.json default /Users/aamorosi/.vscode/extensions/orta.vscode-jest-4.2.1/out/reporter.js"

> @aws-lambda-powertools/commons@0.6.0 test
> npm run test:unit "/var/folders/s7/xzcjrts93cn5_mq16vkcqt794zqxk7/T/jest_runner_aws_lambda_powertools_typescript.json" "default" "/Users/aamorosi/.vscode/extensions/orta.vscode-jest-4.2.1/out/reporter.js"

> cdk-app@0.6.0 test
> npm run test:unit "/var/folders/s7/xzcjrts93cn5_mq16vkcqt794zqxk7/T/jest_runner_aws_lambda_powertools_typescript.json" "default" "/Users/aamorosi/.vscode/extensions/orta.vscode-jest-4.2.1/out/reporter.js"

> cdk-app@0.6.0 test:unit
> npm run build && jest "/var/folders/s7/xzcjrts93cn5_mq16vkcqt794zqxk7/T/jest_runner_aws_lambda_powertools_typescript.json" "default" "/Users/aamorosi/.vscode/extensions/orta.vscode-jest-4.2.1/out/reporter.js"

> @aws-lambda-powertools/commons@0.6.0 test:unit
> jest --group=unit --detectOpenHandles --coverage --verbose "/var/folders/s7/xzcjrts93cn5_mq16vkcqt794zqxk7/T/jest_runner_aws_lambda_powertools_typescript.json" "default" "/Users/aamorosi/.vscode/extensions/orta.vscode-jest-4.2.1/out/reporter.js"

> cdk-app@0.6.0 build
> tsc --skipLibCheck

No tests found, exiting with code 1
Run with `--passWithNoTests` to exit with code 0
In /Users/aamorosi/Codes/aws-lambda-powertools-typescript/packages/commons
  10 files checked.
  roots: /Users/aamorosi/Codes/aws-lambda-powertools-typescript/packages/commons/src, /Users/aamorosi/Codes/aws-lambda-powertools-typescript/packages/commons/tests - 10 matches
  testMatch: **/?(*.)+(spec|test).ts - 2 matches
  testPathIgnorePatterns: /node_modules/ - 10 matches
  testRegex:  - 0 matches
Pattern: /var/folders/s7/xzcjrts93cn5_mq16vkcqt794zqxk7/T/jest_runner_aws_lambda_powertools_typescript.json|default|/Users/aamorosi/.vscode/extensions/orta.vscode-jest-4.2.1/out/reporter.js - 0 matches
npm ERR! Lifecycle script `test:unit` failed with error: 
npm ERR! Error: command failed 
npm ERR!   in workspace: @aws-lambda-powertools/commons@0.6.0 
npm ERR!   at location: /Users/aamorosi/Codes/aws-lambda-powertools-typescript/packages/commons 
npm ERR! Lifecycle script `test` failed with error: 
npm ERR! Error: command failed 
npm ERR!   in workspace: @aws-lambda-powertools/commons@0.6.0 
npm ERR!   at location: /Users/aamorosi/Codes/aws-lambda-powertools-typescript/packages/commons 
lerna ERR! npm run test /var/folders/s7/xzcjrts93cn5_mq16vkcqt794zqxk7/T/jest_runner_aws_lambda_powertools_typescript.json default /Users/aamorosi/.vscode/extensions/orta.vscode-jest-4.2.1/out/reporter.js exited 1 in '@aws-lambda-powertools/commons'
lerna ERR! npm run test /var/folders/s7/xzcjrts93cn5_mq16vkcqt794zqxk7/T/jest_runner_aws_lambda_powertools_typescript.json default /Users/aamorosi/.vscode/extensions/orta.vscode-jest-4.2.1/out/reporter.js exited 1 in '@aws-lambda-powertools/commons'
lerna WARN complete Waiting for 1 child process to exit. CTRL-C to exit immediately.
</details>

### Expected Behavior

Test run & have same results as when run in the command line.

### Actual Behavior

Most of the tests fail / don't run with the extension

--- 

The fastest (and the most fun) way to resolve the issue is to submit a pull-request yourself. If you are interested, feel free to check out the [contribution guide](https://github.com/jest-community/vscode-jest/CONTRIBUTING.md), we look forward to seeing your PR...

**Comment by connectdotz** [comment]
Hi, sorry for the delayed response. I looked at your repo, and it seems lerna is stripping off all `--options` flags we passed to jest. From your output:

```
lerna info Executing command in 5 packages: "npm run test /var/folders/s7/xzcjrts93cn5_mq16vkcqt794zqxk7/T/jest_runner_aws_lambda_powertools_typescript.json default /Users/aamorosi/.vscode/extensions/orta.vscode-jest-4.2.1/out/reporter.js"
```

while the original arguments passed to the run script is

```
aws-lambda-powertools-typescript@0.0.1 test > npm run lerna-test "--testLocationInResults" "--json" "--useStderr" "--outputFile" "/var/folders/s7/xzcjrts93cn5_mq16vkcqt794zqxk7/T/jest_runner_aws_lambda_powertools_typescript.json" "--watch" "--no-coverage" "--reporters" "default" "--reporters" "/Users/aamorosi/.vscode/extensions/orta.vscode-jest-4.2.1/out/reporter.js" "--colors"
```
I am not familiar with lerna, so not sure how to fix that. However, you could try the vscode [multiroom workspace](https://code.visualstudio.com/docs/editor/multi-root-workspaces), which is how we officially support the multiroom projects like yours. I tried it by adding your `commons` as a workspace folder and setting the `"jest.jestCommandLine": "npm run test:unit --"` in its settings.json, all tests there worked as expected.

Please let me know if that works for you or if you have any other questions.

**Comment by dreamorosi** [comment]
Hi @connectdotz, thank you for looking into it, appreciate you taking the time.

We ended up using another VSCode plugin at the end, but we are in the process of moving away from lerna (which has been declared as unmaintained) so we might reconsider this in the future.
