### ISSUE TITLE
Unable to see/update Coverage with auto-run off

### ISSUE THREAD

**Issue by 11joselu** [jest-community/vscode-jest#855]
### Environment

1. `vscode-jest version`: v4.4.0
2. `node -v`: v16.1.0
3. `npm -v` or `yarn --version`: 7.11.2
4. `npm ls jest` or `npm ls react-scripts` (if you haven’t ejected): jest@27.5.1
5. your vscode-jest settings if customized:
  ```json
  "jest.coverageFormatter": "GutterFormatter",
  "jest.autoRun": "off",
  "jest.coverageColors": { "uncovered": "rgba(255,99,71, 0.2)", "partially-covered": "rgba(255,215,0, 0.2)"}
  ```
6. Operating system: Linux mint 20.2

### Prerequisite
- are you able to run jest test from the command line? Yes
- how do you run your tests from the command line? (for example: `npm run test` or `node_modules/.bin/jest`) npm run test || CTRL + SHIFT + T (shortcut defined for vscode Jest: Run All tests

### Steps to Reproduce

You can reproduce using this repo: https://github.com/CodiumTeam/legacy-training-js/tree/master/tennis-refactoring-kata

### Expected Behavior

After runing all tests and clicking in 'Toggle coverage" we should be able to see the coverage report as a Gutter. 

### Actual Behavior

Disabling autoRun, if you run all test then "Toggle coverage" the reports do not appears.  You need to  click in the coverage icon (bottom line) and then focus in code. After that, the coverage appears. Even if you remove some tests cases, run all tests + toggle coverage, did not refresh the report

Example

_Sometimes I use shortcut to toggle coverage (window + space)_
![vs-code-coverage](https://user-images.githubusercontent.com/8685132/165259608-664e6fb8-3c91-458d-aa6e-e86cf5e6caee.gif)

--- 

The fastest (and the most fun) way to resolve the issue is to submit a pull-request yourself. If you are interested, feel free to check out the [contribution guide](https://github.com/jest-community/vscode-jest/CONTRIBUTING.md), we look forward to seeing your PR...

**Comment by 11joselu** [comment]
Question:

In the readme, this image 

![Jest coverage report](https://raw.githubusercontent.com/jest-community/vscode-jest/master/images/status-bar-watch-coverage.png) 

Means you must set autoWatch to true?. If so, maybe we can change readme to add as a required step.

**Comment by connectdotz** [comment]
> After runing all tests and clicking in 'Toggle coverage" we should be able to see the coverage report as a Gutter.

Not quite. To see the coverage report, you need to tell jest to generate the coverage info, therefore the right sequence will be 

1. toggle coverage on
2. run tests 

I tried your repo and it seems to work as expected.

**Comment by 11joselu** [comment]
Yes, I do and it seems to work too. I will close it. Thanks for your time :)
