### ISSUE TITLE
Error notification when no tests / jest are in the workspace folder

### ISSUE THREAD

**Issue by domino2** [jest-community/vscode-jest#856]
### Environment

1. `vscode-jest version`: [4.4.0]
2. `node -v`: [16.14.2]
3. `npm -v`: [8.5.0]
4. `npm ls jest`: [empty]
5. your vscode-jest settings if customized:
    - jest.jestCommandLine? [empty]
    - jest.autoRun? [empty]
6. Operating system: [macOS Monterey 12.3.1]

### Steps to Reproduce

Add additional node/npm folders into the workspace and you'll see the "not-test onProcessExit: process exit with code=127" notification error.

### Relevant Debug Info

Additional folders are not meant to be tested, but they have package.json and node_modules as usual apps.
Jest is not installed for these and global installation is not available also.

### Expected Behavior

I would to expect to be able to hide the workspace folder from the processing of this plugin.

### Actual Behavior

VS Code notifying me randomly about this issue and the error message keeping to pop up.

**Comment by connectdotz** [comment]
Yes, this is sort of a known issue, the algorithm could have been smarter. For now, you can use the setting `disabledWorkspaceFolders` to manually exclude the folder. See more details in [Customization](https://github.com/jest-community/vscode-jest#customization) section.
