### ISSUE TITLE
Can I avoid that the TestExplorer is opened upon launch?

### ISSUE THREAD

**Issue by janaagaard75** [jest-community/vscode-jest#861]
Version 4.4.0 introduced this feature: "Enhanced test output discovery by automatically opening TestExplorer terminal upon launch."

Is it possible to turn this off? I prefer the minimalistic approach where the test result is only displayed in VSCode's bottom status bar. I have searched in the documentation about this, but haven't been able to find anything.

**Comment by fleonard** [comment]
I'm in the same boat. pretty annoying that a new terminal is always opened. Would be good to have the ability to manually turn it off

**Comment by connectdotz** [comment]
This has been addressed, please try [pre-release 4.5.0](https://github.com/jest-community/vscode-jest#pre-release-v450-).

duplicate of #854
