### ISSUE TITLE
Code Coverage report doesn't auto update after running watch tests

### ISSUE THREAD

**Issue by Tasty213** [jest-community/vscode-jest#864]
### Environment

1. `vscode-jest version`: v4.4.0
2. `node -v`: v16.15.0
3. `npm -v`: 8.5.5
4. `npm ls jest`: jest@28.1.0
5. your vscode-jest settings if customized:
```
		"jest.rootPath": "",
		"jest.showCoverageOnLoad": true,
		"jest.autoRun": {
			"watch": true,
			"onStartup": [
				"all-tests"
			]
		},
		"jest.coverageFormatter": "GutterFormatter"
```
6. Operating system: Windows 11 Version 10.0.22000 Build 22000
7. Jest config from Package.json
```
"jest": {
        "testEnvironment": "jsdom",
        "collectCoverage": true,
        "collectCoverageFrom": [
            "./src/**"
        ],
        "coverageReporters": [
            "text",
            "html",
            "lcov"
        ],
        "modulePathIgnorePatterns": [
            "setup.js"
        ]
    }
```

### Prerequisite
- are you able to run jest test from the command line? Yes, doing so runs the tests and produces a coverage report in HTML, text and lcov. The Html one is updated with the correct coverage but the gutter bars remain unchanged.
- how do you run your tests from the command line? npm run test

### Steps to Reproduce

I've made another repo with a minimal config but that doesn't seem to have the same issue https://github.com/Tasty213/vscode-jest-code-coverage-gutter-bars-bug,  the current repo I'm experiencing difficulty with is https://github.com/Tasty213/gryphon-games it is larger which makes me think it may be size/performance issue.

To reproduce on the larger repo:
1. Clone the repo and open in vscode
2. use command pallete to toggle on coverage report
3. Run all the tests
4. open the coverage report HTML generated in `./coverage`
5. open `./src/coursle/board.js` and see that lines 163-173 are green
6. edit line 68 to skip the describe block
7. rerun the tests (this should happen automatically)
8. Refresh the coverage HTML report and note that it now shows missing163-173
9. See board.js has not updated it's gutter bars to reflect this
10. toggling coverage off and on again via the command palette fixes this 

### Relevant Debug Info
Went through the self debug bit but i couldn't find anything of use. When toggling between coverage on and off it just logged it running the command with and without the coverage option.

### Expected Behavior
Files gutter bars indicating code coverage should automatically update when new test data is available

### Actual Behavior
They only update once you toggle the coverage on or off.

**Comment by connectdotz** [comment]
hi @Tasty213 I tried your [gryphon-games](https://github.com/Tasty213/gryphon-games) repo today and I could not reproduce it on either Windows 10 or macOS. Are you still having the problems? anything interesting from developer console or terminal?

**Comment by ffMathy** [comment]
I am getting this too on MacOS M1 in a dev-container (Linux).
