### ISSUE TITLE
not-test onProcessExit: process exit with code=127

### ISSUE THREAD

**Issue by 201flaviosilva** [jest-community/vscode-jest#865]
### Environment

1. `vscode-jest version`: [v4.4.0](https://github.com/jest-community/vscode-jest/releases/tag/v4.4.0)
2. `node -v`: v17.1.0
3. `npm -v`: 8.1.4
4. `npm ls jest`: jest@28.1.0
5. your vscode-jest settings if customized: https://github.com/201flaviosilva/HillClimbing.js/blob/main/jest.config.js
6. Operating system: Mac OS Monterey 12.3.1 (21E258)

### Prerequisite
- are you able to run jest test from the command line? Yes
- how do you run your tests from the command line? `npm run test` or `npm run start:test`

### Steps to Reproduce

This is my working repository: https://github.com/201flaviosilva/HillClimbing.js

### Relevant Debug Info
```sh
not-test onProcessExit: process exit with code=127, signal=undefined
 see troubleshooting: https://github.com/jest-community/vscode-jest/blob/master/README.md#troubleshooting
env: node: No such file or directory
Jest process "watch-tests" ended unexpectedly
 see troubleshooting: https://github.com/jest-community/vscode-jest/blob/master/README.md#troubleshooting
```

### Expected Behavior

To run the test with any problem

### Actual Behavior

Not run the tests and print this error:

<img width="1428" alt="Jest Bug" src="https://user-images.githubusercontent.com/55815265/168910463-7bf3a198-ca36-483f-a64a-ec48f8c9bba2.png">

**Comment by 201flaviosilva** [comment]
Got a new error:
<img width="1434" alt="Jest Bug 2" src="https://user-images.githubusercontent.com/55815265/168926767-ee85f98d-4ade-452a-8507-213724fc3143.png">

If this helps any way :)

**Comment by connectdotz** [comment]
```
env: node: No such file or directory
```
this is an indication that the shell env is not properly initialized. Try to start vscode from a terminal (instead of UI). 

more detailed info [here](https://github.com/jest-community/vscode-jest/issues/741#issuecomment-921222851)

**Comment by 201flaviosilva** [comment]
Opening the VS Code this way has improved, but I don't think it's an intuitive way

**Comment by connectdotz** [comment]
indeed,  I am hoping to come up with a better fix soon. I will let you know when it is available. 

The link provided above (https://github.com/jest-community/vscode-jest/issues/741#issuecomment-921222851) suggested a few workarounds, you can choose the one least sucked for now :grimacing:

**Comment by 201flaviosilva** [comment]
Yap, I  think I will wait until it’s solved :)
