### ISSUE TITLE
Jest process "watch-tests" ended unexpectedly: npm not found

### ISSUE THREAD

**Issue by Morriz** [jest-community/vscode-jest#867]
### Environment

1. `vscode-jest version`: `v4.4.0`
2. `node -v`: `v16.14.2`
3. `npm -v` or `yarn --version`: `8.5.0`
4. `npm ls jest` or `npm ls react-scripts` (if you haven’t ejected): `react-scripts@5.0.1`
5. your vscode-jest settings if customized:
    - jest.jestCommandLine? [fill]
    - jest.autoRun? [fill]
    - anything else that you think might be relevant? [fill]
6. Operating system: OSX 12.3.1

### Prerequisite
- are you able to run jest test from the command line? yes
- how do you run your tests from the command line? `npm test` which runs `react-scripts test`

### Steps to Reproduce

Open a react-scripts project that has the extension installed. Only upon startup is an error shown, and the waiting script re-runs successfully after touching any file. Race condition?

Also, setting a custom command is giving the same errors.

The jest config:
```js
module.exports = {
  preset: 'ts-jest',
  testEnvironment: 'node',
  modulePathIgnorePatterns: ['.history'],
  transform: {
    '^.+\\.test.(ts|tsx)?$': 'ts-jest',
  },
  moduleFileExtensions: ['ts', 'tsx', 'js', 'jsx', 'json', 'node'],
}
```

### Relevant Debug Info

Without configuring anything (out of the box) I see this error:
```
not-test onProcessExit: process exit with code=127, signal=undefined
 see troubleshooting: https://github.com/jest-community/vscode-jest/blob/master/README.md#troubleshooting
/bin/sh: npm: command not found
Jest process "watch-tests" ended unexpectedly
 see troubleshooting: https://github.com/jest-community/vscode-jest/blob/master/README.md#troubleshooting
```

### Expected Behavior

No error messages

### Actual Behavior

Error messages

--- 

The fastest (and the most fun) way to resolve the issue is to submit a pull-request yourself. If you are interested, feel free to check out the [contribution guide](https://github.com/jest-community/vscode-jest/CONTRIBUTING.md), we look forward to seeing your PR...

**Comment by Morriz** [comment]
I tried uninstalling, cleaning prefs, reinstalling, but no dice.

**Comment by Morriz** [comment]
We use the same config in another repo where these errors don't appear. I am trying to find out what is diff

**Comment by connectdotz** [comment]
```
/bin/sh: npm: command not found
```
this usually indicates a shell env issue. Try to start vscode from a terminal (instead of UI). 

more detailed info [here](https://github.com/jest-community/vscode-jest/issues/741#issuecomment-921222851)

**Comment by Morriz** [comment]
I always start it from shell, and all my windows work fine. If the app can't find npm in PATH then I presume PATH must be different suddenly. Hmmm

**Comment by connectdotz** [comment]
you can verify the path via the developer console:

See additional logging from the developer console (via Help > Toggle Developer Tools menu), look for the spawn log, expand the "options" object, then "env", the "PATH" (inherited from vscode process) should be there:

![ezgif com-gif-maker](https://user-images.githubusercontent.com/891093/169888937-c7f69526-0f33-48b3-80ed-8d62419d0659.gif)

**Comment by Morriz** [comment]
ok, got vscode updates and the issue is gone...may have been some local state that got corrupt. Tnx for your time

**Comment by asrulkadir** [comment]
> ```
> /bin/sh: npm: command not found
> ```
> 
> this usually indicates a shell env issue. Try to start vscode from a terminal (instead of UI).
> 
> more detailed info [here](https://github.com/jest-community/vscode-jest/issues/741#issuecomment-921222851)

Wow, it's work, thanks
