### ISSUE TITLE
Debug test error: SyntaxError: missing ) after argument list.

### ISSUE THREAD

**Issue by 0x5457** [jest-community/vscode-jest#868]
### Environment

1. `vscode-jest version`: `v4.4.0`
2. `node -v`: `v18.1.0`
3. `npm -v` or `yarn --version`: `npm 8.10.0`
4. `npm ls jest` or `npm ls react-scripts` (if you haven’t ejected): `jest@27.5.1`
5. your vscode-jest settings if customized:
    - jest.jestCommandLine? `None`
    - jest.autoRun? `None`
    - anything else that you think might be relevant? `None`
6. Operating system: `OSX 12.3.1`

### Prerequisite
- are you able to run jest test from the command line? `yes`
- how do you run your tests from the command line? (for example: `npm run test` or `node_modules/.bin/jest`) `npm run test`

### Steps to Reproduce

I installed jest via pnpm. `pnpm i jest`

The `node_modules/.bin/jest` file is generated by pnpm as a shell script. not a nodejs script.

```
#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
     *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -z "$NODE_PATH" ]; then
   export NODE_PATH="/path/to/jest-demo/node_modules/.pnpm/node_modules"
else
   export NODE_PATH="$NODE_PATH:/path/to/jest-demo/node_modules/.pnpm/node_modules"
fi
if [ -x "$basedir/node" ]; then
   exec "$basedir/node" "$basedir/../jest/bin/jest.js" "$@"
else
   exec node "$basedir/../jest/bin/jest.js" "$@"
fi
```
Click the test item in the vscode sidebar, select any test case and click the debug button.
`/usr/local/bin/node ./node_modules/.bin/jest` will be executed in the terminal

Error in terminal `SyntaxError: missing ) after argument list`

### Relevant Debug Info
```
/path/to/jest-demo/node_modules/.bin/jest:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1033:15)
    at Module._compile (node:internal/modules/cjs/loader:1069:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Module._load (node:internal/modules/cjs/loader:827:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47
```

**Comment by connectdotz** [comment]
does setting `"jest.jestCommandLine": "npm run test --"` help?

**Comment by 0x5457** [comment]
> does setting `"jest.jestCommandLine": "npm run test --"` help?

"jest.jestCommandLine" doesn't seem to work

It will still execute commands like ‘/usr/local/bin/node ./node_modules/.bin/jest’

**Comment by 0x5457** [comment]
If I install jest via npm
cat ./node_modules/.bin/jest 
```node
#!/usr/bin/env node
/**
 * Copyright (c) Facebook, Inc. and its affiliates. All Rights Reserved.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

const importLocal = require('import-local');

if (!importLocal(__filename)) {
  require('jest-cli/bin/jest');
}
```

Install jest via pnpm
cat ./node_modules/.bin/jest 
```sh
#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
...
...
```

Anyway `./node_modules/.bin/jest` has [shebang](https://en.wikipedia.org/wiki/Shebang_(Unix)) specified.
Is it possible to run `./node_modules/.bin/jest` directly instead of `/usr/local/bin/node ./node_modules/.bin/jest`?
And  can I try to fix it.

**Comment by connectdotz** [comment]
oh wait, this only happened for debugging? I assume that means you were able to run tests fine right? In that case, you need to modify your launch.json debug config instead. You can use the Setup wizard (`"Jest: Setup Extension (Beta)"`) to help you update it.

**Comment by 0x5457** [comment]
All right, thanks

**Comment by mmmmmmmgo** [comment]
[            
](https://gist.github.com/esamattis/600d6964f3e6ab6e8e7da9a05bfe6574)
