### ISSUE TITLE
vscode startup run tests auto but get errors  `Error: EMFILE: too many open files`

### ISSUE THREAD

**Issue by GOWxx** [jest-community/vscode-jest#880]
### Environment

1. `vscode-jest version`: [v4.6.0]
2. `node -v`: [v16.14.2]
3. `npm -v` or `yarn --version`: [8.5.0]
4. `npm ls jest` or `npm ls react-scripts` (if you haven’t ejected): [jest@27.5.1]
5. your vscode-jest settings if customized:
    - jest.jestCommandLine? ["npm test --"]
    - jest.autoRun? [none]
    - anything else that you think might be relevant? [none]
6. Operating system: [m1 macos monterey]

### Prerequisite
- are you able to run jest test from the command line? [yes] 
- how do you run your tests from the command line? (for example: `npm run test` or `node_modules/.bin/jest`) [npm test / npm run test] both run jest test successful
### Steps to Reproduce

[reproduces repo]https://github.com/GOWxx/jest-study-example-for-gowxx/tree/repro/vscode_jest_open_test_failed

run vscode, jest run auto, then I get Error
![image](https://user-images.githubusercontent.com/12870715/173519654-1f9c2092-b5b4-419b-bb89-5ec48513bbf2.png)

```bash
> jest-tutorial-example@1.0.0 test
> jest "--testLocationInResults" "--json" "--useStderr" "--outputFile" "/var/folders/k5/6fyb698x6vq6v4c4km3hy2km0000gn/T/jest_runner_jest_study_example_for_gowxx.json" "--watch" "--no-coverage" "--reporters" "default" "--reporters" "/Users/gowxx/.vscode/extensions/orta.vscode-jest-4.6.0/out/reporter.js" "--colors"

node:events:504
      throw er; // Unhandled 'error' event
      ^

Error: EMFILE: too many open files, watch
    at FSEvent.FSWatcher._handle.onchange (node:internal/fs/watchers:204:21)
Emitted 'error' event on NodeWatcher instance at:
    at NodeWatcher.checkedEmitError (/Users/gowxx/code/GOWxx/jest-study-example-for-gowxx/node_modules/jest-haste-map/build/watchers/NodeWatcher.js:141:12)
    at FSWatcher.emit (node:events:526:28)
    at FSEvent.FSWatcher._handle.onchange (node:internal/fs/watchers:210:12) {
  errno: -24,
  syscall: 'watch',
  code: 'EMFILE',
  filename: null
}
Jest process "watch-tests" ended unexpectedly
 see troubleshooting: https://github.com/jest-community/vscode-jest/blob/master/README.md#troubleshooting
```
#### BUT I can run jest success by click button on vscode.jest sidebar
![image](https://user-images.githubusercontent.com/12870715/173519216-37a1c604-737e-4aad-9a3e-898cbd98a7bc.png)

### Expected Behavior
open vscode and run tests automatically without errors

### Actual Behavior

open vscode and run tests automatically WITH errors

--- 

The fastest (and the most fun) way to resolve the issue is to submit a pull-request yourself. If you are interested, feel free to check out the [contribution guide](https://github.com/jest-community/vscode-jest/CONTRIBUTING.md), we look forward to seeing your PR...

**Comment by connectdotz** [comment]
@GOWxx I tried your repo and it worked fine on my machine for both auto-run (with watch) and on-demand via sidebar/gutter menu.

From your error message, it seems that it might be related to the watchman on your machine. Did a quick google search and found some suggestions you can try: https://stackoverflow.com/questions/58675179/error-emfile-too-many-open-files-react-native-cli 

> BUT I can run jest success by click button on vscode.jest sidebar

When executing tests this way, the extension doesn't involve watchman and thus worked. It's different than when you first launch the vscode, which by default starts jest in watch mode (this can be configured via `jest.autoRun`).

**Comment by GOWxx** [comment]
> @GOWxx I tried your repo and it worked fine on my machine for both auto-run (with watch) and on-demand via sidebar/gutter menu.
> 
> From your error message, it seems that it might be related to the watchman on your machine. Did a quick google search and found some suggestions you can try: https://stackoverflow.com/questions/58675179/error-emfile-too-many-open-files-react-native-cli
> 
> > BUT I can run jest success by click button on vscode.jest sidebar
> 
> When executing tests this way, the extension doesn't involve watchman and thus worked. It's different than when you first launch the vscode, which by default starts jest in watch mode (this can be configured via `jest.autoRun`).

Thank you for your help!
After you reminded me, I realized it was watchman's problem.
https://github.com/facebook/watchman/issues/923#issuecomment-963669204

```
brew install watchman
sudo launchctl limit maxfiles 16384 16384 && ulimit -n 16384
```

I tried this and it works.
