### ISSUE TITLE
TypeError: data.map(...).toString(...).replaceAll is not a functionJest

### ISSUE THREAD

**Issue by GeorgeWL** [jest-community/vscode-jest#887]
### Environment

1. `vscode-jest version`: 4.6.0
2. `node -v`:  14.19.3
3. `npm -v` or `yarn --version`: 1.22.19
4. `npm ls jest` or `npm ls react-scripts` (if you haven’t ejected): jest@26.6.0
5. your vscode-jest settings if customized:
    - jest.jestCommandLine? `""`
    - jest.autoRun? null
6. Operating system: Windows 8

### Prerequisite
- are you able to run jest test from the command line? 

> Yes

- how do you run your tests from the command line? (for example: `npm run test` or `node_modules/.bin/jest`) 

> node --harmony node_modules/jest/bin/jest.js

### Steps to Reproduce

Whilst using a version of NodeJS which doesn't have the String.prototype.replaceAll function, view the "Testing" sidebar in a repo which has a babel config that adds that prototype, the extension UI will fail any tests which contain `x.replaceAll(string)`

### Relevant Debug Info

[fill]

### Expected Behaviour

Passes in Jest Extension UI, the same as running tests from the command

### Actual Behaviour

Jest Extension UI will fail any tests which contain `x.replaceAll(string)`, command line passes all tests

--- 

The fastest (and the most fun) way to resolve the issue is to submit a pull-request yourself. If you are interested, feel free to check out the [contribution guide](https://github.com/jest-community/vscode-jest/CONTRIBUTING.md), we look forward to seeing your PR...

**Comment by connectdotz** [comment]
If you didn't customize `jestCommandLine`, then it most likely default to plain `jest` and `node` in your env, i.e. it will not pass the `--harmony` flag like you usually do. You can try to set `jestCommandLine` to the exact command (but might need to adjust jest path as the default shell is cmd). 

You can turn on debug mode to see how the system spawns the jest command: https://github.com/jest-community/vscode-jest#how-to-see-more-debug-info-self-diagnosis

**Comment by GeorgeWL** [comment]
That's exactly as you said, thanks
