### ISSUE TITLE
How to exclude typescript build folder

### ISSUE THREAD

**Issue by fredprodibi** [jest-community/vscode-jest#900]
Hi,

in tsconfig.json I have "outDir": "./_build", the extension find this folder too, and duplicate the tests in the test explorer.

How can I exclude the _build folder from the watch?

thank you

**Comment by connectdotz** [comment]
you will need to configure jest, please see [Configuring Jest](https://jestjs.io/docs/configuration).

**Comment by connectdotz** [comment]
close the issue as not related to this extension.
