### ISSUE TITLE
Enhancement: Update individual snapshots

### ISSUE THREAD

**Issue by mynnx** [jest-community/vscode-jest#905]
### Environment

1. `vscode-jest version`: v4.6.0
2. `node -v`: v14.17.2
3. `npm -v` or `yarn --version`: 6.14.33
4. `npm ls jest` or `npm ls react-scripts` (if you haven’t ejected): `jest@28.1.3`
5. your vscode-jest settings if customized:
    - jest.jestCommandLine? `node_modules/.bin/jest` (I found this was necessary to generate a debug config using the wizard)
    - jest.autoRun? "off"
6. Operating system: VSCode Ubuntu remote host running on Mac laptop

### Prerequisite
- are you able to run jest test from the command line? yest
- how do you run your tests from the command line? (for example: `npm run test` or `node_modules/.bin/jest`)
 - actually I usually use `docker-compose exec app yarn test` but I've had to install Jest outside the container and got lucky that it worked outside the container in order to get this extension to work.  That's a whole different thing 😄 

### Steps to Reproduce / etc

(this is a feature request / question about possibly-existing functionality)

--- 

When updating Jest snapshots, we encourage team members to examine each snapshot one-by-one to ensure that the change in snapshot was _intentional_.  Thus, I turned off `jest.enableSnapshotUpdateMessages` because it encourages people to ignore changed snapshots.

I _really_ like the CodeLens on failing snapshot tests and I'm wondering - does/will this extension support updating _one_ snapshot instead of the entire suites'?  It seems like it would go really well as a context menu option when clicking the `X` in the gutter on a failed test.

**Comment by connectdotz** [comment]
I think this is a good idea, will add it to our feature todo list. thanks!

**Comment by szszoke** [comment]
It would be nice if this would be an inline option above the test case, like `Debug` is today. This should work for parameterized tests as well, if the button becomes a dropdown.

**Comment by connectdotz** [comment]
@mynnx @szszoke snapshot feature is out in [v5.0.3](https://github.com/jest-community/vscode-jest/blob/master/release-notes/release-note-v5.md), feel free to give it a spin and let us know how it works for you.

**Comment by szszoke** [comment]
Thanks! I will give it a try next week!
