### ISSUE TITLE
Syntax error on "?." constructs

### ISSUE THREAD

**Issue by ylavoie** [jest-community/vscode-jest#909]
### Environment

1. `vscode-jest version`: 4.6.0
2. `node -v`: 18.9.0
3. `npm -v` or `yarn --version`: npm 8.19.1
4. `npm ls jest` or `npm ls react-scripts` (if you haven’t ejected): jest@29.0.3
5. your vscode-jest settings if customized:
    - jest.jestCommandLine? [fill]
    - jest.autoRun? [fill]
    - anything else that you think might be relevant? [fill]
6. Operating system: Ubuntu 22.04 on Linux 5.15.0-47-generic

### Prerequisite
- are you able to run jest test from the command line? yes
- how do you run your tests from the command line? (for example: `npm run test` or `node_modules/.bin/jest`) node_modules/.bin/jest

### Steps to Reproduce

After reload VS Code window, vscode-jest don't auto run and stopped

### Relevant Debug Info

```
Scheduled test run "watch-tests-1" for "orta.vscode-jest:TestProject"
/home/ylavoie/node_modules/jest-cli/build/cli/index.js:161
    if (error?.stack) {
              ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/ylavoie/node_modules/jest-cli/build/index.js:13:12)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
[TestProject]: Jest process "watch-tests" ended unexpectedly
```
### Expected Behavior

vscode-jest auto run and launch all test

### Actual Behavior

vscode-jest stop auto run

--- 

The fastest (and the most fun) way to resolve the issue is to submit a pull-request yourself. If you are interested, feel free to check out the [contribution guide](https://github.com/jest-community/vscode-jest/CONTRIBUTING.md), we look forward to seeing your PR...

**Comment by connectdotz** [comment]
hmm... Does it still happen after restarting vscode? If it does, do you have a sample repo we can take a look at?

**Comment by ylavoie** [comment]
Misconfiguration. The above settings are for the Docker container which runs the tests, not the host where VSCode is run and where nodejs has a very old version.

**Comment by Lilpiggie0522** [comment]
How did you solve it? I am having exact same issue where I am running ssh-fs on vscode and using jest in the ssh fs command line terminal.
