### ISSUE TITLE
Suggestion: Recognise when yarn/npm install is happening and pause whilst is

### ISSUE THREAD

**Issue by GeorgeWL** [jest-community/vscode-jest#913]
### Environment

1. `vscode-jest version`: [4.6.0]
2. `node -v`: [v14.19.3]
3. `npm -v` or `yarn --version`: [yarn 1.22.19]
4. `npm ls jest` or `npm ls react-scripts` (if you haven’t ejected): [jest 24.9.0]
5. your vscode-jest settings if customized:
    - jest.jestCommandLine? [fill]
    - jest.autoRun? 
    ```json
      {
         "watch": true,
         "onStartup": ["all-tests"]
       }
     ```
    - anything else that you think might be relevant? [fill]
6. Operating system: [fill]

### Prerequisite
- are you able to run jest test from the command line? Yes
- how do you run your tests from the command line? (for example: `npm run test` or `node_modules/.bin/jest`) [`"test:unit": "jest --maxWorkers=50% tests/unit"`]

### Steps to Reproduce

- Re-install node_modules during jest autorun via `yarn install` or `npm install`
- VSCode Jest will crash and show the dialogue asking if one wants to set a new jest command

### Expected Behavior

N/A

### Actual Behavior

N/A

My suggestion is to have it pause if it is somehow able to detect that a install is in-progress (not researched if this is possible)

--- 

The fastest (and the most fun) way to resolve the issue is to submit a pull-request yourself. If you are interested, feel free to check out the [contribution guide](https://github.com/jest-community/vscode-jest/CONTRIBUTING.md), we look forward to seeing your PR...

**Comment by connectdotz** [comment]
hmmm... during watch mode the "watchman" decides what to run, this request probably should be raised to [watchman](https://facebook.github.io/watchman/) team instead.
