### ISSUE TITLE
Suggestion: support multi-root workspace launch

### ISSUE THREAD

**Issue by roddolf** [jest-community/vscode-jest#914]
### Environment

1. `vscode-jest version`: 4.6.0
2. `node -v`: 16.14.2 
3. `npm -v` or `yarn --version`: 8.19.2
4. `npm ls jest` or `npm ls react-scripts` (if you haven’t ejected): jest@26.6.3
5. your vscode-jest settings if customized:
    - jest.jestCommandLine? [fill]
    - jest.autoRun? [fill]
    - anything else that you think might be relevant? [fill]
6. Operating system: Windows

### Prerequisite
- are you able to run jest test from the command line? yes
- how do you run your tests from the command line? (for example: `npm run test` or `node_modules/.bin/jest`) vscode test explorer

### Steps to Reproduce

Execute debug option on any test in the test explorer

### Relevant Debug Info

[fill]

### Expected Behavior

[fill]

### Actual Behavior

[fill]

### Suggestion

Look up for the launch configuration in the `code-workspace.json` when no configuration found in `.vscode/launch.json`

--- 

The fastest (and the most fun) way to resolve the issue is to submit a pull-request yourself. If you are interested, feel free to check out the [contribution guide](https://github.com/jest-community/vscode-jest/CONTRIBUTING.md), we look forward to seeing your PR...

**Comment by connectdotz** [comment]
good point.

**Comment by connectdotz** [comment]
@roddolf, this issue should be fixed in [v5 pre-release](https://github.com/jest-community/vscode-jest/blob/master/release-notes/release-note-v5.md), feel free to give it a spin and let us know how it works for you. Thanks.

**Comment by roddolf** [comment]
It works perfectly for me, thank you!
