### ISSUE TITLE
camelcase args are not supported in angular cli

### ISSUE THREAD

**Issue by vhdirk** [jest-community/vscode-jest#923]
### Environment

1. `vscode-jest version`: 5.0.0
2. `node -v`: v18.10.0
3. `npm -v` or `yarn --version`: yarn 1.22.19
4. `npm ls jest` or `npm ls react-scripts` (if you haven’t ejected): 
```
webapp@1.7.0-SNAPSHOT /home/dirk/devel/webapp
├─┬ @angular-builders/jest@14.0.0
│ ├─┬ jest-preset-angular@12.1.0
│ │ └── jest@28.1.3 deduped
│ └── jest@28.1.3 deduped
├─┬ jest-extended@3.0.1
│ └── jest@28.1.3 deduped
├─┬ jest-mock-console@2.0.0
│ └── jest@28.1.3 deduped
├─┬ jest-mock-extended@2.0.7
│ └── jest@28.1.3 deduped
├─┬ jest-preset-angular@12.2.0
│ └── jest@28.1.3 deduped
├── jest@28.1.3
└─┬ ts-jest@28.0.7
  └── jest@28.1.3 deduped
```
5. your vscode-jest settings if customized:
    - jest.jestCommandLine? ` yarn run test --bail --max-workers=2`
    - jest.autoRun? [fill]
    - anything else that you think might be relevant? [fill]
6. Operating system: Debian testing

### Prerequisite
- are you able to run jest test from the command line? yes
- how do you run your tests from the command line? (for example: `npm run test` or `node_modules/.bin/jest`) `yarn run test`

### Steps to Reproduce

Yarn run test is an alias for `ng test`, which, in my case, uses the jest builder from 
https://github.com/just-jeb/angular-builders.

The relevant snippet from my `angular.json` is 
```
        "test": {
          "builder": "@angular-builders/jest:run",
          "options": {
            "configPath": "src/jest.conf.js",
            "no-cache": true,
            "polyfills": ["src/polyfills.ts"],
            "tsConfig": "src/tsconfig.spec.json"
          }
        },
```

Jest supports both camelCase as dashed arguments. Angular CLI only supports dashed argument. vscode-jest uses camelcase.
While I understand this is not an issue originating from vscode-jest, the solution can be pretty simple and should not matter for those not using angular anyway. 

See https://github.com/just-jeb/angular-builders/blob/master/MIGRATION.MD#jest-builder for more info

**Comment by ulrikdom** [comment]
It'd be great to this fixed. Haven't found any other good extensions that work with @angular-builders/jest.

**Comment by stefanrybacki** [comment]
Still not completely working: https://github.com/jest-community/vscode-jest/pull/1034#issuecomment-1656626993
