### ISSUE TITLE
EACCES: permission denied, open '/tmp/jest_runner_project_backend_2.json' on shared systems

### ISSUE THREAD

**Issue by MiguelGuthridge** [jest-community/vscode-jest#929]
### Environment

1. `vscode-jest version`: 4,6,0
2. `node -v`: 18.10.0
3. `npm -v` or `yarn --version`: 8.19.0
4. `npm ls jest` or `npm ls react-scripts` (if you haven’t ejected): [fill]
5. your vscode-jest settings if customized:
    - jest.jestCommandLine? [fill]
    - jest.autoRun? never
    - anything else that you think might be relevant? [fill]
6. Operating system: Debian 11

### Prerequisite
- are you able to run jest test from the command line? Yes
- how do you run your tests from the command line? npm t

### Steps to Reproduce

1. Use the extension on a system with multiple accounts logged in simultaneously
2. On one user, run tests for a project
3. On another user, run tests for another project with the same name

[fill]

### Relevant Debug Info

[fill]

### Expected Behavior

The tests run normally

### Actual Behavior

The runner is unable to write info to the temporary file as it is owned by another user.

I work at a university where many of our students use this extension on our shared computer systems. This bug has prevented many of them from being able to use the extension.

A suggested fix would be to save the test info within the user's own data (eg within the project folder)

--- 

The fastest (and the most fun) way to resolve the issue is to submit a pull-request yourself. If you are interested, feel free to check out the [contribution guide](https://github.com/jest-community/vscode-jest/CONTRIBUTING.md), we look forward to seeing your PR...

**Comment by connectdotz** [comment]
good point, yes we should allow users to override this.

**Comment by MiguelGuthridge** [comment]
I think it would be better to have improved error checking for it, as needing to update a configuration to get things working is somewhat frustrating for users especially when they are beginners.

**Comment by connectdotz** [comment]
I'm thinking we can use user-id as part of the fileName, do you see any issue with that approach?

**Comment by MiguelGuthridge** [comment]
Looks great! When can I expect this to be released?

**Comment by connectdotz** [comment]
@MiguelGuthridge, this issue should be fixed in [v5 pre-release](https://github.com/jest-community/vscode-jest/blob/master/release-notes/release-note-v5.md), feel free to give it a spin and let us know how it works for you. Thanks.

**Comment by MiguelGuthridge** [comment]
Tried in the pre-release and the file name appears to be `jest_runner_project_name_1000_2.json`, which is correct! Great to see this fixed!!!
