### ISSUE TITLE
[Bug] Using < or > in a describe part breaks the run

### ISSUE THREAD

**Issue by kud** [jest-community/vscode-jest#948]
### Environment

1. `vscode-jest version`: v4.6.0
2. `node -v`: v18.12.1
3. `npm -v` or `yarn --version`: 9.1.2 / 1.22.19
4. `npm ls jest` or `npm ls react-scripts` (if you haven’t ejected): [fill]
5. your vscode-jest settings if customized:
    - jest.jestCommandLine? default
    - jest.autoRun? `off`
    - anything else that you think might be relevant? Nope
6. Operating system: macOS 12.6.1

### Prerequisite
- are you able to run jest test from the command line? yes
- how do you run your tests from the command line? (for example: `npm run test` or `node_modules/.bin/jest`) npm run test

### Steps to Reproduce

- Create a test with

```
describe('<ParticipantSongFilter>', () => {
```

### Relevant Debug Info

```
[project]: executing profile: "run" for /participantSongFilter/__tests__/participantSongFilter.spec.tsx#<ParticipantSongFilter>...
/bin/sh: ParticipantSongFilter: No such file or directory
```

### Expected Behavior

Working

### Actual Behavior

Breaking because of the `<` which redirects the input shell.

---

The best way is to escape some characters when running the tests.

--- 

The fastest (and the most fun) way to resolve the issue is to submit a pull-request yourself. If you are interested, feel free to check out the [contribution guide](https://github.com/jest-community/vscode-jest/CONTRIBUTING.md), we look forward to seeing your PR...

**Comment by connectdotz** [comment]
hi, do you mind giving the latest pre-release [v5.0.2](https://github.com/jest-community/vscode-jest/releases/tag/v5.0.2) a try?

**Comment by kud** [comment]
Yes, sure, I'll do that tomorrow at work. Thanks!

**Comment by kud** [comment]
It seems to be fixed, thank you so much @connectdotz!
