### ISSUE TITLE
Debug codelens are removed about paramter decorators.

### ISSUE THREAD

**Issue by hoyori** [jest-community/vscode-jest#966]
### Environment

1. `vscode-jest version`: 4.6
2. `node -v`: 14.21.1
3. `npm -v` or `yarn --version`: 6.14.17
4. `npm ls jest` or `npm ls react-scripts` (if you haven’t ejected): 29.3.1
5. your vscode-jest settings if customized:
    - jest.jestCommandLine? na
    - jest.autoRun? none
    - anything else that you think might be relevant? na
6. Operating system: windows 10

If there is a class declaration that has a method appiled a parameter decorator in test file, debug codelens are removed.

![2022-12-17 123511](https://user-images.githubusercontent.com/4520035/208221958-e7554d40-21bc-4dbe-bce4-e802fb9d510a.png)

![2022-12-17 123441](https://user-images.githubusercontent.com/4520035/208221992-1560eb35-b950-4d12-87bf-f319db110bc9.png)

**Comment by connectdotz** [comment]
Hi @hoyori, do you have a sample repo I can take a look? I am guessing this is related to jest-community/jest-editor-support#89

**Comment by lojell** [comment]
Same for me

**Comment by connectdotz** [comment]
Hi, this has been addressed in [5.2.0 pre-release](https://github.com/jest-community/vscode-jest/blob/master/release-notes/release-note-v5.x.md#v520-pre-release); feel free to give it a try and let us know if there is any issue.
