### ISSUE TITLE
`WriteStream.prototype.hasColors()` support

### ISSUE THREAD

**Issue by mrazauskas** [jest-community/vscode-jest#971]
### Environment

1. `vscode-jest version`: 5.1.0
2. `node -v`: 19.3.0
3. `npm -v` or `yarn --version`: 3.3.1
4. `npm ls jest` or `npm ls react-scripts` (if you haven’t ejected): jest@29.3.1
5. your vscode-jest settings if customized:
    - jest.jestCommandLine? `yarn test` (see reproduction repo)
6. Operating system: MacOS

### Prerequisite
- are you able to run jest test from the command line? Yes
- how do you run your tests from the command line? `yarn test`

### Steps to Reproduce

Reproduction repo is here: https://github.com/mrazauskas/x-has-colors

### Expected Behavior

Same test result in Jest CLI and `vscode-jest`.

### Actual Behavior

The snapshot is passing via CLI, but failing via `vscode-jest`.

The reproduction is using Node’s build-in `WriteStream.prototype.hasColors()` method (see [documentation](https://nodejs.org/dist/latest-v19.x/docs/api/tty.html#writestreamhascolorscount-env)). Seems like `vscode-jest` has some issue with support of this API. I decided to open a ticket, because that is Node’s native API.

EDIT: See comment below.

~~You may notice that Jest is patched in the reproduction repo. The patch makes Jest to use Worker Threads. It has no impact in this case, because there is just one test suite (workers will not ne used).~~

~~I left the patch just to draw your attention that Jest has similar issue with Node’s `hasColors()`. When workers are used (Child Process), the `env` is overwritten here: https://github.com/facebook/jest/blob/fd8f89719912996802fe90bdeab1d5a6d8e95d8e/packages/jest-worker/src/workers/ChildProcessWorker.ts#L132-L136~~

~~As you will see in the code `supports-color` is used there, but `supports-color` does not respect Node’s environmental variables [`NODE_DISABLE_COLORS`](https://nodejs.org/dist/latest-v19.x/docs/api/cli.html#node_disable_colors1) and [`NO_COLORS`](https://nodejs.org/dist/latest-v19.x/docs/api/cli.html#no_colorany). In contrary `hasColors()` takes those into account. This is why support of `hasColors()` is broken in Jest’s Child Process workers. I can’t find a smart way to fix that, swapping to Worker Threads with a patch was better idea.~~

~~I was tying to figure out if maybe `vscode-jest` is doing something unexpected with environment variables as well. Got swamped in the codebase, found nothing relevant. Hopeful all what I wrote here will make it easier to spot the issue for someone familiar with the code (;~~

**Comment by mrazauskas** [comment]
On more idea. I just checked `process.env` and found out that `COLORTERM: 'truecolor'` is present then Jest runs via CLI, but it is gone if `vscode-jest` runs the tests. Strange.

As a work around I have set `"jest.jestCommandLine": "FORCE_COLOR='' yarn test"`.

**Comment by mrazauskas** [comment]
Would it be possible somehow to use `FORCE_COLOR=1` instead of `--colors` flag here:

https://github.com/jest-community/vscode-jest/blob/9c6f121d2bd17691c37e47dc232953357e4d00c4/src/JestProcessManagement/JestProcess.ts#L107-L109

Found it by activating `debugMode` and looking at the output in Developer Tools. `process.env` in the spawned process belongs to Electron. That’s why variables are different from the ones in Terminal.

`FORCE_COLOR=1` environmental variable and `--colors` flag are equal for Jest, because Chalk supports both: https://github.com/chalk/chalk#supportscolor

Node and `WriteStream.prototype.hasColors()` respects only `FORCE_COLOR`. Having it set should solve the issue.

**Comment by connectdotz** [comment]
@mrazauskas, thanks for your research; it helped a lot! 

Looks like we could add the `COLORTERM: 'truecolor'` to the process.env, as the vscode terminal does [here](https://github.com/microsoft/vscode/blob/7f4ac698ce84c51bec0c12e7c413eb33317e4fa6/src/vs/workbench/contrib/terminal/common/terminalEnvironment.ts#L59). 

I am glad you found a workaround, another one is to use the [jest.nodeEnv](https://github.com/jest-community/vscode-jest#customization) setting: 
```json
"jest.nodeEnv": { "COLORTERM": "truecolor" }
```

**Comment by mrazauskas** [comment]
Right, it would be better to add `COLORTERM: 'truecolor'` to `process.env`.

Would it be good idea to add `env` to options object of `Runner` class from `jest-editor-support`? It should pass it to `createProcess`, of course. This way a consumer of the API like `vscode-jest` could set any variables it needs.

If that sounds good, I could do this after holidays.

**Comment by connectdotz** [comment]
> Would it be good idea to add env to options object of Runner class from jest-editor-support?

It already is; that is how we pass along the setting `jest.nodeEnv` ([here](https://github.com/jest-community/vscode-jest/blob/3deb1af4586aaf6baf2ae30cdced34e77575a436/src/JestExt/helper.ts#L67)). 

The question is if the extension should add it, or leave it to the users as customization when needed. This use case seems to be relatively rare as you are the first user ever bumped into this issue, and I am not sure if there is any ill side-effect if we add it to all use cases...

Let's do this: Giving there is an existing setting that you can use, I will not change anything for now. But we will leave this issue open, and if more similar user cases arise, we can certainly reconsider.

**Comment by mrazauskas** [comment]
What about mocking `hasColors` in my tests:

```ts
jest.spyOn(WriteStream.prototype, "hasColors").mockReturnValue(true);
```

Simple and makes them run in any environment. I think that is better solution than keeping tests dependent on some environmental variables. At first it wasn’t clear why tests are falling, but now I think my tests were simply too fragile and needed a refactor.

Thanks for your comments!
