### ISSUE TITLE
jest environment == node not being respected and `Response` is not available

### ISSUE THREAD

**Issue by trajano** [jest-community/vscode-jest#975]
### Environment

1. `vscode-jest version`: v5.1.0
2. `node -v`: 16.18.1
3. `npm -v` or `yarn --version`:1.22.19
4. `npm ls jest` or `npm ls react-scripts` (if you haven’t ejected): [fill]
5. your vscode-jest settings if customized:
    - jest.jestCommandLine? [fill]
    - jest.autoRun? [fill]
    - anything else that you think might be relevant? [fill]
6. Operating system: [fill]

### Prerequisite
- are you able to run jest test from the command line? yes
- how do you run your tests from the command line? yarn test

### Steps to Reproduce

https://github.com/trajano/spring-cloud-demo/blob/a099666a100414180dbe1cbf411b1f8e08408a3f/packages/auth-context/src/__tests__/fetch.test.tsx#L60

Fails with this

    fetchMock.config.Response = Response;

Because Response is not defined.  Command line works correctly.

### Expected Behavior

Works the same as command line which is successful

### Actual Behavior

![image](https://user-images.githubusercontent.com/110627/209458389-619d8c9f-3d32-48f6-b94f-ed98e4499842.png)

**Comment by connectdotz** [comment]
Might be a setup issue... where do you manually run `yarn test`? Is this set up as a monorepo project? What does the auto-config say about the jestCommandLine/rootPath it detected?

Do you have a sample repo for us to take a closer look at? I tried the repo you linked above but couldn't get it to install...

**Comment by trajano** [comment]
I tweaked it so it no longer fails on both side by adding `isometric-fetch`
