### ISSUE TITLE
README: dead link to `jest command` configuration

### ISSUE THREAD

**Issue by matt-y** [jest-community/vscode-jest#978]
Omitting the extension issue template for this README issue:

[This line in the README contains a dead link to the setup of the `jest command`](https://github.com/jest-community/vscode-jest/blob/master/README.md?plain=1#L14).  It was not immediately clear to me where this link should go within the README file. [Should this link go to the `jestCommandLine` anchor in the `Settings` subheading? ](https://github.com/jest-community/vscode-jest#jestCommandLine)

For reference the line in question is:

```markdown
If the extension can find the [jest command](#how-to-set-up-the-jest-command), by default it will automatically run and monitor all tests in watch mode upon launch, and you should see tests, status, errors, coverage (if enabled) in TestExplorer and editors like this: 
```

**Comment by connectdotz** [comment]
good catch. With the auto-config in v5, I think we can just remove the link.
