### ISSUE TITLE
`Setup Monorepo Project` should not attempt to make changes to disabled workspace folders.

### ISSUE THREAD

**Issue by kassemsandarusi** [jest-community/vscode-jest#981]
### Environment

1. `vscode-jest version`: 5.1.0
1. your vscode-jest settings if customized:
    - jest.disabledWorkspaceFolders: ["root"]
1. Operating system: macOS

### Steps to Reproduce

1. Have a multi-root workspace like so (living in .vscode/):

```json
{
  "folders": [
    {
      "name": "root",
      "path": "../"
    },
    {
      "name": "packages/package-1",
      "path": "../packages/package-1"
    },
    {
      "name": "packages/package-2",
      "path": "../packages/package-2"
    }
  ],
  "settings": {
    "jest.disabledWorkspaceFolders": ["root"],
  }
}
```

In this scenario the setup tool still reads root and tries to set it up. It ends up erroneously finding another packages (package-3 not listed here) jest config instead of just skipping, and then it adds a bad `jest.rootPath` to the settings of the root project.

### Expected Behavior

A disabled workspace folder should not be evaluated during monorepo setup.

### Actual Behavior

A disabled workspace folder **is** evaluated.

**Comment by connectdotz** [comment]
good point!
