### ISSUE TITLE
`jest.autoRevealOutput` missing from settings schema

### ISSUE THREAD

**Issue by segevfiner** [jest-community/vscode-jest#992]
### Environment

1. `vscode-jest version`: v5.1.0
2. `node -v`: v16.19.0
3. `npm -v` or `yarn --version`: pnpm v7.24.3
4. `npm ls jest` or `npm ls react-scripts` (if you haven’t ejected): 29.3.1
5. your vscode-jest settings if customized:
    - jest.jestCommandLine?
    - jest.autoRun? off
    - anything else that you think might be relevant? [fill]
6. Operating system: macOS 12.6.2

### Prerequisite
- are you able to run jest test from the command line? yes
- how do you run your tests from the command line? (for example: `npm run test` or `node_modules/.bin/jest`) pnpm test

### Steps to Reproduce

Just open the settings dialog, `jest.autoRevealOutput` is missing from the settings schema in this extension `package.json`

### Relevant Debug Info

[fill]

### Expected Behavior

It should be defined in the settings schema in the `package.json`.

### Actual Behavior

It isn't.

--- 

The fastest (and the most fun) way to resolve the issue is to submit a pull-request yourself. If you are interested, feel free to check out the [contribution guide](https://github.com/jest-community/vscode-jest/CONTRIBUTING.md), we look forward to seeing your PR...

**Comment by segevfiner** [comment]
Actually... It doesn't seem to be working now either...

**Comment by connectdotz** [comment]
this was just released yesterday in [5.2.0 pre-release](https://github.com/jest-community/vscode-jest/blob/master/release-notes/release-note-v5.x.md#v520-pre-release), are you still on 5.1.0?

**Comment by segevfiner** [comment]
Yeah. Guess I read docs that are for the unreleased feature. If such, you can close this.

**Comment by connectdotz** [comment]
You can try the pre-release in vscode: https://code.visualstudio.com/updates/v1_63#_pre-release-extensions. Feel free to reopen if it doesn't resolve your issue.
