### ISSUE TITLE
I cannot turn autoRun off

### ISSUE THREAD

**Issue by Inspirateur** [jest-community/vscode-jest#993]
### Environment

1. `vscode-jest version`: 5.1.0

2. `node -v`: 18.12.1

3. `npm -v`: 9.1.2

4. `npm ls jest`: 
backend@1.0.0 D:\Documents\Repos\service-desk\backend
├── jest@27.5.1
└─┬ ts-jest@27.1.5
  └── jest@27.5.1 deduped
  
5. your vscode-jest settings if customized:
    - jest.autoRun: "off"
    
6. Operating system: Windows 10

### Prerequisite
- are you able to run jest test from the command line? yes
- how do you run your tests from the command line? npm run test

### Steps to Reproduce

Sorry I don't have time yet to recreate a repo with the same config. 

### Expected Behavior

Jest should not run on vs code startup nor should it run on save.

### Actual Behavior

It does.

**Comment by connectdotz** [comment]
The `jest.autoRun` setting should stop jest from automatically running. However, the extension might still try to examine your env to find the jest commands and parse the test files to put the run/debug menu for each test... 

Are you seeing the jest terminal reporting something? Just curious, how do you know the tests are running? If this is related to the jest terminal, please try [v5.2.0 pre-release](https://github.com/jest-community/vscode-jest/blob/master/release-notes/release-note-v5.x.md#v520-pre-release), which will only reveal when tests are run.

**Comment by NuclleaR** [comment]
Is this related?

console is empty but something is running tests. it happens only when extension enabled

sorry for video from phone IDK how to unblock os notification when screen recorders take video.

https://user-images.githubusercontent.com/6917580/214128335-37a81e10-7c98-46ab-9dea-42f0412e49ca.MOV

**Comment by connectdotz** [comment]
@NuclleaR thanks for the video, a few questions/comments:
- I did not see jest output terminal, which should be named like `Jest (your workspace name)`
- I did not see the status bar on the bottom, so not sure what jest status is. Can you take a snapshot of that?
- there is no indication from the video that the tests are running, can you elaborate how you know the tests are running?
- I did see your `index.js` showing some red underlines. The extension does create those for test errors, is `index.js` a test file? Please hover over those underlines and let us know what they show...
- you can also open the console log (perhaps with  `"jest.debugMode": true`) and see if there is any indication that tests are running

**Comment by ciriousjoker** [comment]
@connectdotz 
This terminal automatically opens whenever I launch the project:
<img width="1445" alt="Bildschirm­foto 2023-01-28 um 22 31 21" src="https://user-images.githubusercontent.com/16866223/215292131-f578f997-62cc-436b-9ffa-5b34386e8e15.png">

Here's the `settings.json`:

```json
"jest.autoRun": {
  "watch": false,
  "onStartup": []
}
```

I also tried: `"jest.autoRun": "off"`.

Here's the jest status:
<img width="237" alt="Bildschirm­foto 2023-01-28 um 22 34 14" src="https://user-images.githubusercontent.com/16866223/215292183-aaa9dcee-d9f4-462c-8def-d10368fbf1c2.png">

This is the extension output:
<img width="1323" alt="Bildschirm­foto 2023-01-28 um 22 35 16" src="https://user-images.githubusercontent.com/16866223/215292219-a3855ac2-031d-42b0-8e2a-181ab17bdafb.png">


(debugMode is true for all of these screenshots)

**Comment by connectdotz** [comment]
@ciriousjoker thanks for the info. The status bar "..." means no test has been run. The terminal issue has been fixed in v5.2 (#976), once you upgrade to the latest (v5.2.2), the terminal should only be shown when tests are run.

**Comment by ciriousjoker** [comment]
Works perfectly, thanks!

**Comment by Johann01** [comment]
Definitly not the case, it still opens a terminal, when opening a new run vscode project with jest and npm install has not run yet. (To  install dotenv)

<img width="1728" alt="Screenshot 2023-02-01 at 14 49 51" src="https://user-images.githubusercontent.com/37617663/216061066-efdeb464-de75-47cf-b83f-4adea030c2e6.png">

**Comment by connectdotz** [comment]
@Johann01 If there is a "fatal error" when the extension setting up your test env, the terminal will be revealed. This does not mean the tests are run, which is what `jest.autoRun` controls. 

Maybe the `jest.autoRun` is easily confused with _*"auto running the extension"?*_  Maybe we should rename it to `jest.autoTestRun`? 

See more explanation about the difference between test run vs. extension run: [comment](https://github.com/jest-community/vscode-jest/issues/993#issuecomment-1397888738)
