### ISSUE TITLE
alphebetical sorting isnt great if test name uses %#

### ISSUE THREAD

**Issue by skeddles** [jest-community/vscode-jest#995]
When you include %# in the test name in test.each, it prints out the index of the test. 

eg:

    test.each([ [],[],[],[],[],[],[],[],[],[],[],[] ])('test %#', async () => {});

the test titles will be "test 0", "test 1", "test 2"

The problem is in this plugin, the names get sorted alphabetically, so if there's more than 10, they end up in this order:

    test 0, test 1, test 10, test 11, test 12

As you can see here:
![Code_2023-01-20_12-13-59](https://user-images.githubusercontent.com/2721332/213762063-c2c1d298-d80f-4603-ab93-2d25bc399a85.png)

I'm not sure how it could be done, but it would just be nice if they were displayed in the proper order.

**Comment by connectdotz** [comment]
This is decided by vscode, you can file a feature request for "natural sort", especially for tests with the same location...
